### ISSUE TITLE
v6: Can't resolve 'react/jsx-runtime' in '/usr/src/app/node_modules/nuka-carousel/dist'

### ISSUE THREAD

**Issue by esetnik** [FormidableLabs/nuka-carousel#1014]
# Bugs and Questions

### Prerequisites

- [x] I've searched open [issues](https://github.com/FormidableLabs/nuka-carousel/issues) to make sure I'm not opening a duplicate issue
- [x] I have read through the docs before asking a question
- [x] I am using the latest version of nuka-carousel

### Describe Your Environment

- What version of nuka-carousel are you using? v6.0.1
- What version of React are you using? v17.0.2
- What browser are you using? N/A

### Describe the Problem

Using create-react-app and installing the latest version of nuka-carousel causes build step to fail with a compilation error.
```
#16 2.213 Creating an optimized production build...
#16 39.49 Failed to compile.
#16 39.49 
#16 39.49 Module not found: Error: Can't resolve 'react/jsx-runtime' in '/usr/src/app/node_modules/nuka-carousel/dist'
#16 39.49 Did you mean 'jsx-runtime.js'?
#16 39.49 BREAKING CHANGE: The request 'react/jsx-runtime' failed to resolve only because it was resolved as fully specified
#16 39.49 (probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
#16 39.49 The extension in the request is mandatory for it to be fully specified.
#16 39.49 Add the extension to the request.
#16 39.49 
#16 39.49 
#16 39.59 error Command failed with exit code 1.
#16 39.59 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
#16 ERROR: executor failed running [/bin/sh -c REACT_APP_ENV=$REACT_APP_ENV yarn build]: exit code: 
```

#### Expected behavior:
Working the same way as v5

#### Actual behavior
Fail to compile on v6 in create-react-app environment

**Comment by LetsPoke** [comment]
any updates on that? facing the same problem right now after updating dependencies

**Comment by carloskelly13** [comment]
Hi, we made a mistake in not setting the peer dependency for v6 to React 18, and will be fixing that in a patch. stepping up to React 18 should resolve this issue in how the jsx runtime is imported.
