### ISSUE TITLE
Can we achieve a crossfade effect between slides when animation="fade"?

### ISSUE THREAD

**Issue by henrybabbage** [FormidableLabs/nuka-carousel#1038]
# Bugs and Questions

### Prerequisites

- [x] I've searched open [issues](https://github.com/FormidableLabs/nuka-carousel/issues) to make sure I'm not opening a duplicate issue
- [x] I have read through the docs before asking a question
- [x] I am using the latest version of nuka-carousel

### Describe Your Environment

- What version of nuka-carousel are you using? ^6.0.3
- What version of React are you using? 18.2.0
- What browser are you using? Firefox

### Describe the Problem

Not a bug per se, I would just like to ask how I can achieve a "cross-fade" effect when the animation prop is set to "fade"? Currently, when changing slides with the animation prop set to "fade", we see the current image disappear, a flash of the background behind where the image was, and then the next image appear. Swiper slider has a crossfade prop for example, so that the current image fades out and the next image fades in at the same time. Could this effect be achieved another way with the Nuka Carousel?

Here is [a StackBlitz example with Nuka](https://stackblitz.com/edit/react-nuka-carousel-fca3jj-qyfj92?file=App.tsx).

Here is [an example of what I am trying to achieve](https://codesandbox.io/p/sandbox/swiper-react-effect-fade-forked-lrzrcp?welcome=true&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cloocw1xx00072e68vxi3b0q7%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cloocw1xx00032e68rcbof9rn%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cloocw1xx00052e6897hi6tzb%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cloocw1xx00062e68yc16xis1%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B60%252C40%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cloocw1xx00032e68rcbof9rn%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cloocw1xx00022e68gpk8823n%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fstyles.css%2522%257D%255D%252C%2522id%2522%253A%2522cloocw1xx00032e68rcbof9rn%2522%252C%2522activeTabId%2522%253A%2522cloocw1xx00022e68gpk8823n%2522%257D%252C%2522cloocw1xx00062e68yc16xis1%2522%253A%257B%2522id%2522%253A%2522cloocw1xx00062e68yc16xis1%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522cloocw6nx00az2e68aeap5d6j%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cloocw6nx00az2e68aeap5d6j%2522%257D%252C%2522cloocw1xx00052e6897hi6tzb%2522%253A%257B%2522id%2522%253A%2522cloocw1xx00052e6897hi6tzb%2522%252C%2522activeTabId%2522%253A%2522cloocw511008d2e68uh8ucprb%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cloocw1xx00042e685p0hl25s%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cloocw26a0002eejrhdsh4edc%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522cloocw511008d2e68uh8ucprb%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) (Swiper in this example).

#### Expected behavior: 

animation="fade"

Images fade over the top of one another.

#### Actual behavior

One image fades out. The background is momentarily visible. Then the next image fades in.

Thank you very much for your time.

**Comment by Andrewryanhyde** [comment]
+1
