### ISSUE TITLE
Uncaught Invariant Violation: Unable to find element with ID 31

### ISSUE THREAD

**Issue by cyppe** [FormidableLabs/nuka-carousel#104]
Issue when running mod pagespeed module in apache that moves inline css into external files.

This tag is generated by component:
`<style type="text/css" data-reactid="31">.slider-slide > img {width: 100%; display: block;}</style>`

But when we enable mod pagespeed this tag is removed and moved into external file or moved into bottom of page into one big `style` tag. That means that `data-reactid="31"` no longer exists and we get error in console

masterBundle.js.pagespeed.jm.4DRXBWttfT.js 
Uncaught Invariant Violation Unable to find element with ID 31

Can you set this style external file instead?

**Comment by cyppe** [comment]
Any help? Would be really appreciated so we can run pagespeed.

**Comment by cyppe** [comment]
It's this part that is the problem:
 <style type="text/css" dangerouslySetInnerHTML={{__html: self.getStyleTagStyles()}}/>

Better if this is not output as element bound to React (data-reactid)

**Comment by kenwheeler** [comment]
Looking into this

**Comment by cyppe** [comment]
Any news?

**Comment by kristian-puccio** [comment]
https://github.com/facebook/react/issues/7093

**Comment by sarmeyer** [comment]
Does anyone know if this issue is still present? The library has been rewritten since this issue was submitted, so I will close it for now. If this is still of concern, please reopen!
