### ISSUE TITLE
dragging:false is not working

### ISSUE THREAD

**Issue by maheshambiga** [FormidableLabs/nuka-carousel#106]
Passing prop {dragging:false} is not preventing dragging of slides on swipe.

**Comment by aij** [comment]
It works for me.

How are you passing the prop? Note that if you pass *anything* other than the boolean value `false`, it will be treated as true, including "false", null, and undefined. Can you use React devtools to make sure it's getting passed through as you expect?

**Comment by mikestopcontinues** [comment]
The problem isn't the prop. I think it has to do with getTweeningValue(). It's gives adjusted values as you drag.

**Comment by mikestopcontinues** [comment]
Actually, the problem is that onTouchMove doesn't check to see if dragging is enabled.

**Comment by aij** [comment]
Oh, I see. It does disable *mouse* swipe/dragging, but doesn't disable *touch* swipe/dragging.

**Comment by kenwheeler** [comment]
So does everyone think there should be a `swiping` prop to disable swiping?

**Comment by mikestopcontinues** [comment]
I think so. My use case was that users could only move in one direction,
and only through button click. I was using it like a sales squeeze page. So
it would have been great to be able to turn swipe off.


Mike

**Comment by maheshambiga** [comment]
Here, {dragging:false} should disable touchMove as well. It does not make any sense have a separate prop to restrict swipe. Dragging is nothing but mouse drag as well as touchMove.

**Comment by haxtrujillo** [comment]
https://github.com/FormidableLabs/nuka-carousel/blob/master/lib/carousel.js#L221
adding `  if (this.props.dragging === false) {
      return null;
  }`
 in /lib/carousel.js line 221 will work. I hope to see a solution on the next release.

**Comment by warmhug** [comment]
There should be a swiping prop to disable swiping.  +1
