### ISSUE TITLE
Broken Documentation site (https://commerce.nearform.com/open-source/nuka-carousel)

### ISSUE THREAD

**Issue by temtechie** [FormidableLabs/nuka-carousel#1060]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Code Sandbox link

https://commerce.nearform.com/open-source/nuka-carousel

### Bug report

```markdown
Hey 👋 ,

I have been trying to access the nuka carousel documentation to enable me make use of the library the documentation site seems unreachable , its broken
```

**Comment by FrankFan** [comment]
Yes，I had the same issue.

How long will this been fixed ?

**Comment by FrankFan** [comment]
> Yes，I had the same issue.
> 
> How long will this been fixed ?

## reply  to mylsef: 

new site url is : https://commerce.nearform.com/open-source/nuka-carousel/
