### ISSUE TITLE
Enhancement: Lazy loading for images.

### ISSUE THREAD

**Issue by abhilashsajeev** [FormidableLabs/nuka-carousel#11]
It would be nice if lazy loading is implemented for images

**Comment by shouze** [comment]
:+1:

**Comment by Merri** [comment]
*shameless advertizing*
You can use [react-lazy](https://github.com/Merri/react-lazy) to achieve this so the carousel component doesn't need to become more complex than it already is.
*/shameless advertizing*

**Comment by david-owens-akqa** [comment]
@Merri Unless I'm missing something, react-lazy doesn't seem to help. On my quick test all the images loaded before I started scrolling the gallery, both for a full page width gallery and for smaller galleries

using something like this

```javascript
<Carousel>
  <Lazy cushion={100}>
    <img src={getUrl('imagesUrl') + this.state.data.images[0]}/>
  </Lazy>
</Carousel>
```

The use case would be images don't load until the slide is scrolled to (or even better, the slide before)

**Comment by Merri** [comment]
@david-owens-akqa Right now it still lacks the feature of finding the proper nearest parent element of true visibility. So the full visible viewport works as a comparison point. This works great for mobile, but if you test on 2560 x 1440 full screen browser and have only a couple of images then yes, all of them get loaded immediately.

I've been a bit on the lazy side in adding features.

Pun intended.

**Comment by abhilashsajeev** [comment]
Any update on this?

**Comment by abhilashsajeev** [comment]
@Merri React - lazy doesn't seem to help.

**Comment by abhilashsajeev** [comment]
@kenwheeler Any updates?

**Comment by nelsieborja** [comment]
+1

**Comment by slane2016** [comment]
+1

**Comment by imperat0r** [comment]
+1

**Comment by lauterry** [comment]
Hello

I want to show you my workaround to handle lazy loading

Explanations are in the comments

https://gist.github.com/lauterry/cd3cef520644b1413471d5841645c597

Best regards

**Comment by rampageservices** [comment]
Has anyone implemented this?

**Comment by RodrigoTorresWeb** [comment]
Works with react-lazy-images... Example https://codesandbox.io/s/m4kzo330vp?from-embed

**Comment by fritz-c** [comment]
HTML-native lazy loading works:
https://codesandbox.io/s/kind-noether-gz172v
