### ISSUE TITLE
active class for current slide

### ISSUE THREAD

**Issue by Pixlschmied** [FormidableLabs/nuka-carousel#112]
Is it somehow possible to add a active class to the slide?

Like this:
`<li class="slider-slide active">...</li>`

We need this because we want to achieve a css scale effect on the current slide.

**Comment by kenwheeler** [comment]
Good call.

**Comment by KarandikarMihir** [comment]
Any progress here?

**Comment by jflayhart** [comment]
I just compare slideIndex with whatever the currentSlide index is, but this would be nice to have it handled internally.

**Comment by sarmeyer** [comment]
Pr in review for this! https://github.com/FormidableLabs/nuka-carousel/pull/432
