### ISSUE TITLE
Carousel not using <li> when there's only one img in the slider

### ISSUE THREAD

**Issue by xiaoyao1991** [FormidableLabs/nuka-carousel#116]
I found that when the Carousel contains more than 1 images, all the images are wrapped in a `<li>` tag, and somehow it's doing image autoscaling (awesome!). However, when there's only one image in the carousel, the image is not wrapped in `<li>`, but directly as a `<img>` in a `<ul>`, and auto scaling disappeared. 

Is it intentional? Would it be more consistent to always wrap an image in a `<li>` ?

**Comment by kenwheeler** [comment]
Thats likely to be this line: https://github.com/kenwheeler/nuka-carousel/blob/master/src/carousel.js#L165

Would love a PR if you're up for it.

**Comment by msevera** [comment]
I've also faced with this issue. Please fix this.

**Comment by cyppe** [comment]
Yes, I'm also running into trouble... +1

**Comment by xiaoyao1991** [comment]
I had this PR https://github.com/kenwheeler/nuka-carousel/pull/121 to fix this. Reviews and comments are welcomed

**Comment by Lukavyi** [comment]
please fix +1

**Comment by nxmohamad** [comment]
is this already merged into master?

**Comment by xiaoyao1991** [comment]
@nxmohamad I believe so, is it not? My [PR](https://github.com/FormidableLabs/nuka-carousel/issues/121) was merged long ago.

**Comment by nxmohamad** [comment]
I had to copy your updated code into the folder in node_modules to fix it. weird.
