### ISSUE TITLE
nuka carousel + react-modal = :(

### ISSUE THREAD

**Issue by lauterry** [FormidableLabs/nuka-carousel#120]
Hi 

I'm displaying a nuka-carousel in a react-modal.

The problem is that the first picture is not displayed : `slideHeight = 0`.

Here is a gist of the example provided in the nuka carousel project showing the issue  : 

https://gist.github.com/lauterry/e0a93396d40adc85f99564409da33fa7

`npm install react-modal` and run `gulp` 

Click on the Open modal button to trigger the modal and you will see the issue.

Can't figure out what the problem is.

I replace the `img` with just a `div` with text and everything is fine. So the issue seems to occur only with `img` element in the children.

Best regards

**Comment by kenwheeler** [comment]
Hmmm. I've seen this happen with my other carousel, slick, with modals. You might want to either manually fire a window resize event, or use a ref on the carousel to call this.refs.whateverRefYouCallIt.setDimensions.

**Comment by lauterry** [comment]
Hi @kenwheeler

Thanks for your reply.

Where would you call this.refs.whateverRefYouCallIt.setDimensions in the [gist](https://gist.github.com/lauterry/e0a93396d40adc85f99564409da33fa7) ?

I can't make it work :(

Thanks

**Comment by lauterry** [comment]
I have found a workaround based on @kenwheeler reply.

Here is the gist of the workaround : https://gist.github.com/lauterry/4485e6689ee1bb29eb8755a30a82cb71

Hope there will be a better solution.

@kenwheeler What do you think ?

**Comment by ahmed1490** [comment]
any update on this?

**Comment by bcbane** [comment]
The way that I "fixed" this was by triggering a window reset in ComponentWillUpdate so that as soon that the modal has rendered it makes the modal appear. 

`componentDidUpdate(){
   const {modalView} = this.props

  if (modalView !== null) {
    setTimeout(() => {
      window.dispatchEvent(new Event('resize'));
    }, 0)
  }

}`

**Comment by lauterry** [comment]
Hi

I've just test nuka-carousel with react-modal 3.3.2.

This issue seems to have been solved.

**Comment by xtatanx** [comment]
Hello, was wondering if this is something that is already fixed, trying to initialize a modal with nuka carousel and some images inside, however, once the modal loads, the images size is always 0. Does anyone know how this can be solved?
