### ISSUE TITLE
initialSlideHeight Bootstrap

### ISSUE THREAD

**Issue by cocacrave** [FormidableLabs/nuka-carousel#128]
The initialSlideHeight is set to 400.
The height of the carousel is responsive which is good and works fine on first render.
If I change state (unmount carousel) and change back state (mount carousel) the height of the carousel becomes 400 which is too big.
But if I change size of browser it snaps back to correct height. ie not 400.
I've looked over issues opened but could not find one like this.

**Comment by cocacrave** [comment]
It looks like div class slider-list gets height of whatever the original height of image and therefore frame becomes bigger than it should be. It's weird because first time render is fine but second time render (after remounting) becomes all buggy.

**Comment by wesleyyee** [comment]
+1

**Comment by ryan-roemer** [comment]
Is this still an issue on `nuka-carousel@3.1.0+` now that we've landed https://github.com/FormidableLabs/nuka-carousel/pull/291?

**Comment by ashika01** [comment]
Closing the issue because it has been fixed in a newer version(4.3.10). Please reopen with our template if you still experience this issue with the latest stable version.

Thank you.
