### ISSUE TITLE
afterSlide fires when slide does not change

### ISSUE THREAD

**Issue by BuffaloBuffalo** [FormidableLabs/nuka-carousel#129]
The documentation for the `afterSlide` event states:

> afterSlide
> `React.PropTypes.func`
> 
> Hook to be called after a slide is changed.

However, it seems like `afterSlide` is called regardless of whether the slide has changed or not.  To reproduce, add a afterSlide callback like:

```
afterSlide={(slideIndex)=>{
  console.log('new slide index', slideIndex);
})}
```

Now, when if a slide is slightly dragged but the shown slide does not change, afterSlide will continue to print to the console.

The current workaround to this is writing a function like

```
afterSlide={(slideIndex)=>{
  if(this.state.slideIndex !== slideIndex){
      console.log('new slide index', slideIndex);
  }
})}
```

 However, this seems like it should be unnecessary given the phrasing of the documentation.

**Comment by Jonwheeler** [comment]
I am running into this as well, the event appears to fire anytime the Carousel component is clicked.
