### ISSUE TITLE
cellAlign doesn't work with slidesToScroll="auto"

### ISSUE THREAD

**Issue by mlommatzsch** [FormidableLabs/nuka-carousel#132]
Hi,

after upgrading to version 2.0.2 we noticed that cellAlign="left" doesn't work with slidesToScroll="auto" and displaying more than one slide with a fixed slideWith (see attached screen).

<img width="828" alt="bildschirmfoto 2016-07-29 um 15 49 15" src="https://cloud.githubusercontent.com/assets/1668638/17250487/dbcec09e-55a4-11e6-9a4f-fead820b7d75.png">

The slides are always aligned right.

To reproduce you simply change the demo as follows:

`<Carousel
          slideWidth="70px"
          cellSpacing={10}
          framePadding={60}
          slidesToScroll="auto"
          cellAlign="left"
          ref="carousel"
          data={this.setCarouselData.bind(this, 'carousel')}
          slideIndex={this.state.slideIndex}
          afterSlide={newSlideIndex => this.setState({ slideIndex: newSlideIndex })}>
<img src="http://placehold.it/70x70&text=slide1"/>
          <img src="http://placehold.it/70x70&text=slide2"/>
          <img src="http://placehold.it/70x70&text=slide3"/>
          <img src="http://placehold.it/70x70&text=slide4"/>
          <img src="http://placehold.it/70x70&text=slide5"/>
          <img src="http://placehold.it/70x70&text=slide6"/>
        </Carousel>
`

**Comment by kenwheeler** [comment]
This is fixed in 2.0.3

**Comment by mlommatzsch** [comment]
cool. Thank you !
