### ISSUE TITLE
0 Height after Router Link?

### ISSUE THREAD

**Issue by KjellConnelly** [FormidableLabs/nuka-carousel#137]
I have a Carousel within a div. When I switch pages using react-router, and then come back to the page that has the Carousel in it, the Carousel is gone. All elements after it are there as if it's not there. After investigating, I see there is an element of class 'slider' with a height of 0. A bunch of its child elements also have a height of 0. I'm guessing they're a part of this. 

When I resize the window, the height goes back to the height it should be. Any ideas why? How to fix? Thanks!

**Comment by ViLPy** [comment]
Sounds like issue #103 
There is one hack described in comments with resize event triggering.
Plus as an option you can switch to `^1.2.0` version which is not affected

**Comment by KjellConnelly** [comment]
Thanks ViLPy!

After looking through their comments, this is a pretty good solution... simply modify your img to have this onLoad:

`<img src={image} onLoad={() => {window.dispatchEvent(new Event('resize'));}} /> `

**Comment by CharlyJazz** [comment]
@KjellConnelly Seriously do you have to do that to use this with react router? Your solution worked, but is not it better to do a PR with some solution?

**Comment by KjellConnelly** [comment]
@CharlyJazz no idea. I closed this issue two years ago and haven’t looked back at that website since then.
