### ISSUE TITLE
add scale animation to slides on hover

### ISSUE THREAD

**Issue by vgrafe** [FormidableLabs/nuka-carousel#151]
Hi, 

First thing, great job on this component. The only missing feature for my use is a way to scale up a slide upon mouse hovering, and move the surrounding slides to let room for the bigger one.

I forked and implemented my solution - what works great on my solution (contact me for the url) is (as of now) more of a hack and not working very well in the examples page. But I thought I'd share here on a PR, as a base for anyone who have that need. 

I can spend some more serious time on this if there is interest on your side.

**Comment by kenwheeler** [comment]
Thanks! I think I'll leave this out of core for now though.
