### ISSUE TITLE
use id from children for the slide key

### ISSUE THREAD

**Issue by yadahung** [FormidableLabs/nuka-carousel#154]
React key is very important for dynamic children because how React calculates the diff of DOM.

Proposal: key for each children slide can be set if child.props.id is available.

Currently we have `index` as the slide key https://github.com/FormidableLabs/nuka-carousel/blob/master/src/carousel.js#L622,

```
<li key="0"><div key="slide1" id="slide1">slide1</div></li>
<li key="1"><div key="slide2" id="slide2">slide2</div></li>
<li key="2"><div key="slide3" id="slide3">slide3</div></li>

<li key="0"><div key="slide1" id="slide1">slide1</div></li>
<li key="1"><div key="slide3" id="slide3">slide3</div></li>
```

The old slide3 will be destroyed and remount a new one.

If we set child key using `child.props.id`

```
<li key="slide1"><div key="slide1" id="slide1">slide1</div></li>
<li key="slide2"><div key="slide2" id="slide2">slide2</div></li>
<li key="slide3"><div key="slide3" id="slide3">slide3</div></li>

<li key="slide1"><div key="slide1" id="slide1">slide1</div></li>
<li key="slide3"><div key="slide3" id="slide3">slide3</div></li>
```

The old slide3 will be kept.

Reference:
https://facebook.github.io/react/docs/reconciliation.html#recursing-on-children
http://blog.arkency.com/2014/10/react-dot-js-and-dynamic-children-why-the-keys-are-important/

**Comment by sleeparrow** [comment]
#249
