### ISSUE TITLE
Pause autoplay on hover

### ISSUE THREAD

**Issue by moimael** [FormidableLabs/nuka-carousel#167]
Hi,

I find it very frustrating with autoplay when you read some carousel slide and it goes to the next one without having time to finish.

A pause autoplay on mouse hover would be a nice feature to have IMHO.

What do you think ?

Thanks.

**Comment by brybrophy** [comment]
I looked through the src and it looks like this feature is automatically implemented.

```handleMouseOver() {
    if (this.props.autoplay) {
      this.autoplayPaused = true;
      this.stopAutoplay();
    }
  },

  handleMouseOut() {
    if (this.props.autoplay && this.autoplayPaused) {
      this.startAutoplay();
      this.autoplayPaused = null;
    }
  },```

**Comment by moimael** [comment]
Yes sorry about that, I didn't test it properly it seems. Thanks !
