### ISSUE TITLE
issue integrating with next.js

### ISSUE THREAD

**Issue by johannchen** [FormidableLabs/nuka-carousel#171]
The images do not show up on the first visit of a page, but they show up after browser reload. Does nuka-carousel support SSR? Is there an example to follow?  Thanks.

**Comment by psicotropicos** [comment]
Same problem here. I created an example on Now (https://next-nuka-obityscxph.now.sh) and the code for the example is here https://github.com/psicotropicos/playground/tree/master/next-nuka

**Comment by minheq** [comment]
Same problem here :/

**Comment by jpabbuehl** [comment]
same here :(

**Comment by edwardaa** [comment]
see https://github.com/FormidableLabs/nuka-carousel/issues/103

**Comment by sarmeyer** [comment]
I've tested this locally in a next.js app and the carousel works as expected

**Comment by carlosmori** [comment]
@sarmeyer Have you tried with cellAlign: 'center' it doesnt seem to work for us using Next js

**Comment by sarmeyer** [comment]
@carlosmori What other config or props (if any) are you using with Nuka-Carousel? Do you have an example of how the `cellAlign` prop isn't working for you or a sandbox that shows the issue?

Thanks!

**Comment by carlosmori** [comment]
@sarmeyer check this repo out https://github.com/carlosmori/NukaCarouselNextJs . 

The bug occurs like this:

1- Change cellAlign property to 'left' , everything works fine
2- with HMR , change the property to 'center' , everything works fine
3- Refresh the page, it doesnt work anymore. No errors in console, no clue whats happening.

The way I handled to fixed this is by setting props in a useEffect hook, but I dont like this hack and dont understand whats really happening!

Let me know what you think

**Comment by carlosmori** [comment]
Hey @sarmeyer I think I found another bug :( 

In the Repo, I provided before if you comment one of the slides so you have a total of 3 slides when you are in the last slide the previous one disappears. Check this image I attached! 

![image](https://user-images.githubusercontent.com/14813009/106324798-8997c080-6258-11eb-800b-01238c1d847c.png)
