### ISSUE TITLE
v2.1.1 is not on npm

### ISSUE THREAD

**Issue by Alfvador** [FormidableLabs/nuka-carousel#176]
The latest version of nuka-carousel on npm is 2.0.4 : https://www.npmjs.com/package/nuka-carousel
Could you publish version 2.1.1 ?

Thx

**Comment by chinnawatp** [comment]
+1

**Comment by chinnawatp** [comment]
In the meantime, `npm install git://github.com/FormidableLabs/nuka-carousel.git#v2.1.1 --save`
it will install v.2.1.1 from github

**Comment by puredazzle** [comment]
+1

**Comment by TomiHiltunen** [comment]
+1

**Comment by AVickory** [comment]
+1

**Comment by DrewRay** [comment]
+1

**Comment by marissaAnn** [comment]
+1

**Comment by joe-schorn** [comment]
+1

**Comment by smesko85** [comment]
+1

**Comment by webyonet** [comment]
+1
