### ISSUE TITLE
afterSlide is fired before animation ends

### ISSUE THREAD

**Issue by charlesswanson** [FormidableLabs/nuka-carousel#177]
Repro: v2.0.4
Set a high value for the speed prop (ex: 2000)
Make an afterSlide callback log to the console.

It appears the the afterSlide callback is fired immediately when the animation is kicked off. Is this expected? I'd like to know when the animation finishes so that I can make an ajax call. On slower devices, doing the ajax call while the animation is in progress causes choppiness.

Thanks

**Comment by charlesswanson** [comment]
I believe this is the fix: https://github.com/FormidableLabs/nuka-carousel/compare/v2.1.1...charlesswanson:afterSlide-callback

I don't think I can do an official pull request for a tag (v2.1.1 isn't a branch). I applied the change to v2.1.1 because v2.0.4 doesn't have the previousIndex !== index check.

**Comment by joshuan** [comment]
Hey, no plan to fix it? Half a year has passed.

**Comment by yashcr07** [comment]
It seems `afterSlide` only works as expected when i have `wrapAround` set as `true` and the transition is from the LAST slide to the FIRST slide.

**Comment by cwahlfeldt** [comment]
I had issues keeping the animation after I manually set the slide index. I changed the `afterSlide` prop to be `beforeSlide` and it seemed to allow animation to work again. Hope this helps others as I think its related to this.

**Comment by ashika01** [comment]
Closing the issue because it has been fixed in a newer version. Please reopen if you still experience this issue with the latest stable version.
