### ISSUE TITLE
Infinite scroll - only rendering a small window of items

### ISSUE THREAD

**Issue by charlesswanson** [FormidableLabs/nuka-carousel#178]
I'm trying to use nuka-carousel in an infinite-scroll-like scenario. If I have an array of data with 10,000 items, I should only render a small window of items to the DOM for performance. Additionally, I'd like to keep the functionality where the carousel has an animated scroll when moving to new items.

I've modified the v2.0.4 demo and this functionality almost works: https://github.com/charlesswanson/nuka-carousel/tree/infinite-scroll-minimal-render The modified demo has 100 mock data objects. The carousel only shows 2 elements, and renders a maximum of 6 (to allow the sliding animation).

However, it demonstrates the following bug:
![bug](https://cloud.githubusercontent.com/assets/24243008/21744915/8794c5c8-d4d4-11e6-8298-88fc8c45a3fb.png)

I can fix this bug by changing '&&' to '||' in componentWillReceiveProps here: https://github.com/FormidableLabs/nuka-carousel/blob/v2.0.4/src/carousel.js#L148

However, then my component's render() and afterSlide() methods are called twice.

Has anyone implemented this type of functionality before? Any insight into this unexpected behavior?

Thanks

**Comment by charlesswanson** [comment]
I think I've got this working. I ended up changing the && to ||. Then, I modified my component's shouldComponentUpdate so my component doesn't rerender if state.carousels changes. This appears to work.
https://github.com/charlesswanson/nuka-carousel/commit/8923e50cd5aaea27618c4738e9d49605f368a9a9

I also applied two afterSlide callback fixes:
https://github.com/charlesswanson/nuka-carousel/commit/9c36c5c575bff4b86e0d4c2afe8d68a67c11be2f
https://github.com/charlesswanson/nuka-carousel/commit/c46873ee04c794d2d601b3dbd2c66236c6cfbea2

Would still be interested in whether there's a better way to do this.
Thanks!

**Comment by sarmeyer** [comment]
@charlesswanson Do you know if this is still a bug? Nuka has been refactored and updated quite a bit since this issue was submitted. 

I can try to reproduce what you've implemented in your demo branch and see if I can verify that this issue has either been fixed or is still present in 6.x, but I probably won't get to it super soon as there are some other issues I want to prioritize. If you've got any info or an updated demo, I'd be happy to take a look!

**Comment by ValGeorgiev** [comment]
I will close this due to inactivity, please reopen it if you still can reproduce it with v5. We will look to make some more performance improvements in v5.1 and v6. Thanks
