### ISSUE TITLE
trigger event once carousel images are loaded

### ISSUE THREAD

**Issue by heaversm** [FormidableLabs/nuka-carousel#179]
Hi - thanks so much for the carousel. I noticed that before the carousel is fully ready (even on localhost), it displays a little funky - then it sets the size and displays properly. Is there a way to hide the component until it is all configured and sized properly? 

I'm new to react, but I'm wondering if setting up the class with some sort of "componentDidMount" hook or something would work. Let me know if you have any ideas.

![loading](https://cloud.githubusercontent.com/assets/520541/21817200/e629904c-d717-11e6-8d40-8a0433872d98.gif)

**Comment by chinnawatp** [comment]
+1

**Comment by chinnawatp** [comment]
v2.1.1 this issue is fixed. (https://github.com/FormidableLabs/nuka-carousel/pull/135)

to install v2.1.1  https://github.com/FormidableLabs/nuka-carousel/issues/176
