### ISSUE TITLE
heightMode prop doesn't seems to work

### ISSUE THREAD

**Issue by Marcsimm** [FormidableLabs/nuka-carousel#181]
I have a nuka carousel with with 3 slides and the height off the slides depends on the size of the content. So if one slide has 5 rows of text and an anohter have 6 rows of text the one will be higher then the other.

So to fix this i found a heightMode prop where the slides height will be set after the tallest slide but when i test locally it dosen't do anything Does anybody know if heightMode prop is working or not?

**Comment by DavideDaniel** [comment]
I don't believe heightMode is in master yet.

**Comment by ryan-roemer** [comment]
Is this still an issue on `nuka-carousel@3.1.0+` now that we've landed https://github.com/FormidableLabs/nuka-carousel/pull/291?

**Comment by misstricky** [comment]
I don't think heightMode is working for me (trying 'max' setting) height mode, in either 3.1.0 or 4+

**Comment by ashika01** [comment]
heightMode issues - fixed in #408 - release v4.3.9
