### ISSUE TITLE
v2.1.1 -> v2.0.4 rollback?

### ISSUE THREAD

**Issue by navgarcha** [FormidableLabs/nuka-carousel#188]
Looks like there was two releases of the repo on the same day with a lot of functionality removed. Was there a reason for this? I can install v2.1.1 only by using the direct `git://github.com/FormidableLabs/nuka-carousel.git#v2.1.1` url - `nuka-carousel@2.1.1` doesn't work. I don't want to be using an unstable release so am curious whats happened here.

**Comment by wnordmann** [comment]
I used the following line in my package.json to call in version 2.1.1, it seems to be working fine.

`"nuka-carousel": "git://github.com/FormidableLabs/nuka-carousel.git#v2.1.1"`

**Comment by navgarcha** [comment]
Yea it does (as stated in my original issue), im more curious why this isn't a tagged release however.

**Comment by kenwheeler** [comment]
it was an unstable release. working locally to re-integrate the code that was removed and find the problem.

**Comment by navgarcha** [comment]
Thanks for the update.
