### ISSUE TITLE
dots: false

### ISSUE THREAD

**Issue by devdebonair** [FormidableLabs/nuka-carousel#19]
Is there a property to keep the dots from displaying?

**Comment by chaseadamsio** [comment]
If you look at the `decorators.js`, there are three default `decorators`: `PREV`, `NEXT` and the "dot" components, so looks like there's no way to say `dots: false`.

I know this is kinda "hacky" but you could easily set `.slider-decorator-2` to `display: none` in your `css` and that would satisfy your desire to keep the dots from displaying.

**Comment by jgliner** [comment]
Outdated issue, but after digging into the source code,
```js
        <Carousel
          decorators={Carousel.getDefaultProps().decorators.slice(0, 2)}
        >
            <InsertContentsComponentHere>
        </Carousel>
```
seems to work just fine.

**Comment by arzafran** [comment]
IMO I've found a better solution to hide those decorators:

```jsx
  <Carousel
    swiping
    renderBottomCenterControls={false}
  >
```

**Comment by eric-blue** [comment]
> IMO I've found a better solution to hide those decorators:
> 
> ```js-jsx
>   <Carousel
>     renderBottomCenterControls={false}
>   >
> ```

doesn't work for Typescript :(

**Comment by ceciliaschiebel** [comment]
```
renderBottomCenterControls={null}
```
works with Typescript now
