### ISSUE TITLE
Carousel compressed on initial render until zoom out. 

### ISSUE THREAD

**Issue by robrobkay51** [FormidableLabs/nuka-carousel#191]
I'm experiencing a weird situation when using this carousel component: on the initial render, the carousel content is collapsed unnaturally until zooming out, at which point, it displays as expected.

As far as I can see, everything else is working correctly.

How can I correct this issue? Thanks.

**Comment by DavideDaniel** [comment]
I believe this might be a duplicate of https://github.com/FormidableLabs/nuka-carousel/issues/103. If it is, the best solution we've found is to dispatch a resize event in image onLoad:

**Comment by DavideDaniel** [comment]
@robrobkay51 was the above suggestion helpful?

**Comment by robrobkay51** [comment]
@DavideDaniel This works, thanks!

**Comment by DavideDaniel** [comment]
Great! @kenwheeler, this issue can be closed.
