### ISSUE TITLE
heightMode not working 

### ISSUE THREAD

**Issue by mdshaheer** [FormidableLabs/nuka-carousel#192]
@DavideDaniel I could see the heightMode is not implemented in the latest carousel version in master. Are we planning to merge a PR suggested by a contributor?

**Comment by DavideDaniel** [comment]
https://github.com/FormidableLabs/nuka-carousel/commit/f321e5f34629c27a791dfbc32f925fb60ed10ed0 was merged. I see the changes in 2.1.1 but there was a rollback.

**Comment by owener94** [comment]
@kenwheeler Any ideas when this could make it to a published version? We're rooting for it on our project - if there's anything we can do to speed the merge for this let me know.

**Comment by kenwheeler** [comment]
That release had a lot of stuff in it besides that merge, and it was released erroneously. If you want to PR that particular fix @owener94 , I can merge and push a release out.
