### ISSUE TITLE
When displaying more than 1 slide wrapAround doesn't function as one would expect(Re: infinite looping/head to tail)

### ISSUE THREAD

**Issue by travisdmathis** [FormidableLabs/nuka-carousel#194]
An infinite wrap around should place the 1st slide at the end of the last slide.. creating an infinite loop. wrapAround when displaying multiple slides should be head to tail.

currently the way the implementation of wrapAround works is if I have 8 total slides, 6 visible and slide 1 slide at a time, it doesn't wrap until the last slide has passed creating a huge area of nothing

![broken_head_to_tail](https://cloud.githubusercontent.com/assets/1335198/22791549/c4bb0e74-eeb7-11e6-870e-2801ba9f6e06.gif)

**Comment by travisdmathis** [comment]
So, I have an infinite loop working using custom decorators for anyone who comes across this. Would be nice to have wraparound work this way.

```javascript
const decorators = [{
      component: React.createClass({
        render() {
          return (
            <button
              onClick={
                this.props.currentSlide === 3 ?
                () => this.props.goToSlide(0) : this.props.nextSlide}>
              <i className='fa fa-chevron-right fa-3x'/>
            </button>
          )
        }
      }),
      position: 'CenterRight',
      style: {
        padding: 20,
        right: 0
      }
}];

  <Carousel decorators={decorators} slidesToShow={6} slidesToScroll={1} wrapAround={true}>
     {cards}
  </Carousel>
```

**Comment by regan-karlewicz** [comment]
This issue still exists with the release of v4.0.0.

**Comment by bibblebabl** [comment]
![may-07-2018 22-43-46](https://user-images.githubusercontent.com/9008978/39721858-73ae8dde-5249-11e8-800a-e09f80967f1f.gif)

To be honest, it is annoying that the bug is not fixed to the 4th release

**Comment by bibblebabl** [comment]
@travisdmathis it works only with next/prev button? but what about swipe?

**Comment by samwhale** [comment]
Pull #369 implements a fix for this
