### ISSUE TITLE
Mixin replacement for ES6 classes?

### ISSUE THREAD

**Issue by Redmega** [FormidableLabs/nuka-carousel#195]
It's been a few months since issue #74 (React Mixins are Dead in ES6) was brought up and closed. A few months after that issue a blogpost popped up on React detailing the reasons why [Mixins are Broken (And Dangerous!)](https://facebook.github.io/react/blog/2016/07/13/mixins-considered-harmful.html).

Your response to that issue seemed to appease the user, but I am a bit concerned by the blog post, and confused about how to go forward without the Mixin. How would the ES6 syntax look, exactly? What would I add to this to make it work properly?

```js
export default class MyCarousel extends Component {

  render() {
    <Carousel>
      <Image src={images.myImage.src} />
    </Carousel>
  }
}
```

**Comment by stevedukes74** [comment]
I tried this recommended solution:

```
  constructor(props) {
    super(props);
    this.state = { carousels: {} };
    this.setCarouselData = Carousel.ControllerMixin.setCarouselData;
  }
```

No errors, but no carousel.

**Comment by Redmega** [comment]
We got it to work with the solution presented [Here](https://github.com/FormidableLabs/nuka-carousel/issues/71#issuecomment-207200038). I missed Issue #71 in my search somehow.

However, the second solution presented in #71 is more appealing. Is there a way to use the built in next and prev buttons without using the reference to the `ControllerMixin`?

**Comment by kumarharsh** [comment]
@Redmega you don't need string literals for refs. You can just use a callback.

```js
render() {
  <Carousel ref={(c) => this._carousel = c} ...>
}

handleClick = () => {
  this._carousel.nextSlide();
}
```

**Comment by webyonet** [comment]
+1

**Comment by carlospaelinck** [comment]
With Nuka 4.0 we have moved from mixins to ES6 classes.
