### ISSUE TITLE
Last slide doesnt show when property frameOverlow is visible and wrapAround=true

### ISSUE THREAD

**Issue by NikodemusLimanthie** [FormidableLabs/nuka-carousel#199]
Hi, I found an issue when using frameOverlow='visible' property and wrapAround=true.
When the current slide index is 0 (which is the first slide), the slide on the left (which is the last slide) doesn't appear.
The slide on the right (second slide) does appear though.
This only happens when current slide index = 0.

This is an example:
![image](https://cloud.githubusercontent.com/assets/22737128/23055950/63eb1b1a-f51b-11e6-9b8a-977b38922b0d.png)

The picture on the left of Cyan should be Yellow like so:
![image](https://cloud.githubusercontent.com/assets/22737128/23055931/46a2cc7e-f51b-11e6-847a-f2cdc37fc82d.png)

Note: Cyan is the 1st picture, Magenta the 2nd, and Yellow the 3rd

**Comment by wesleyyee** [comment]
+1

**Comment by maximusnikulin** [comment]
+1
