### ISSUE TITLE
Toggling autoplay - an iterator still attached

### ISSUE THREAD

**Issue by zentuit** [FormidableLabs/nuka-carousel#201]
I have a carousel requirement where the carousel has autoplay set to true by default.  Then when the user expands the "slide" to read more, the autoplay is turned off (to let them read it all w/o having mouse over the article). Then if they minimize the slide, autoplay is turned back on.

When I did this, I got a stuttering. I put in some logging and I'm seeing 2 autoplayIterator fires after turning autoplay back on.

Digging some, its looks like when I click the minimize button, that sets `this.autoplay` to true and starts another interval and assigns `autoplayID` (call it A1).  Note that `this.autoplayPaused` is still true. I also get a call to `handleMouseOut` immediately. Now since both `this.autoplay` and `this.autoplayPaused` is true, it starts another autoplay without clearing A1.

**Comment by ashika01** [comment]
@zentuit : could you give us sample code or SandBox example for us to reproduce and help you solve the issue?
