### ISSUE TITLE
Is there a way to disable an edge easing?

### ISSUE THREAD

**Issue by ivan-rudyi-personal** [FormidableLabs/nuka-carousel#203]
@kenwheeler could you please help? Is this project alive ?

**Comment by ivan-rudyi-personal** [comment]
@kenwheeler could you consider the fix for this issue https://github.com/FormidableLabs/nuka-carousel/pull/204 ?

**Comment by auglean** [comment]
Have you tried setting the edge easing to linear? Not really sure what effect you want to obtain.

**Comment by carlospaelinck** [comment]
The `edgeEasing` prop supports any D3 easing function names as strings.
