### ISSUE TITLE
is there a way to slide only when hover?

### ISSUE THREAD

**Issue by menisweet** [FormidableLabs/nuka-carousel#210]
thanks!

**Comment by kenwheeler** [comment]
Can you explain the behavior you'd like to see in a bit more depth?

**Comment by mrtysn** [comment]
I guess what menisweet is asking for autoSlide={true} if hovering and autoSlide={false} otherwise.

**Comment by ashika01** [comment]
Hi, you should be able to do that by having a state for autoSlide and use `onMouseEnter` and `onMouseLeave` to change its state. With newer version of nuka-carousel, there is a `pauseOnHover` prop you can use to do this.
