### ISSUE TITLE
PropTypes in React 16 Deprecated

### ISSUE THREAD

**Issue by fluse** [FormidableLabs/nuka-carousel#212]
Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

**Comment by AlecRust** [comment]
This is done in https://github.com/FormidableLabs/nuka-carousel/pull/214, can close.

**Comment by jrwm** [comment]
@AlecRust in which package version is it released? On npmjs.com is package version 2.0.4 which is 5 months old.

**Comment by AlecRust** [comment]
@jrwm you're right, a new release is required.

**Comment by dazlious** [comment]
@AlecRust: Can you deliver a new release pls?

**Comment by kenwheeler** [comment]
Its released
