### ISSUE TITLE
React.createClass is deprecated and will be removed in version 16

### ISSUE THREAD

**Issue by BrandonBoone** [FormidableLabs/nuka-carousel#216]
"React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement."

**Comment by paranoidjk** [comment]
any progress ?

**Comment by paranoidjk** [comment]
I'd like to create a PR to fix this.

**Comment by Le-Stagiaire** [comment]
@paranoidjk What does prevent you from doing a PR for this issue ?

**Comment by paranoidjk** [comment]
@Le-Stagiaire 
Sorry, since our team decided to mantain a fork version, see https://github.com/react-component/nuka-carousel

**Comment by kenwheeler** [comment]
Fixed https://github.com/FormidableLabs/nuka-carousel/releases/tag/v3.0.0
