### ISSUE TITLE
Is there any way to disable the right button for the current slide and enable it only when the previous  button is clicked . ?

### ISSUE THREAD

**Issue by manishjohar** [FormidableLabs/nuka-carousel#217]

**Comment by fluse** [comment]
i wrote an own navigaton decorator:

```javascript
// Dependencies
import React from 'react'
import createReactClass from 'create-react-class'

// Components
import Icon from '../icon.jsx';

const Navigation = [{
    component: createReactClass({

        getClassName() {
            const inactive = (this.props.currentSlide === 0) ? ' inactive' : '';
            return 'navigation' + inactive;
        },

        render() {
            return (
                <span className={this.getClassName()} onClick={this.props.previousSlide}>
                    <Icon name="arrow-left" size="big" />
                </span>
            )
        }
    }),
    position: 'CenterLeft'
}, {
    component: createReactClass({

        getClassName() {
            const inactive = ((this.props.currentSlide + this.props.slidesToShow) >= this.props.slideCount) ? ' inactive' : '';
            return 'navigation' + inactive;
        },

        render() {

            return (
                <span className={this.getClassName()} onClick={this.props.nextSlide}>
                    <Icon name="arrow-right" size="big" />
                </span>
            )
        }
    }),
    position: 'CenterRight'
}];

decorators={Navigation}
```

**Comment by ashika01** [comment]
@manishjohar : You can always customize your own renderControl and render it by manipulating state changes.

**Comment by ido-galili** [comment]
<Carousel {...options} className={'carousel'}
                        /* Disable Paging Dots on Slide Bottom */
                              renderBottomCenterControls={() => (
                                  null
                              )}
                        /* Change to custom arrow buttons */
                              renderCenterLeftControls={({previousSlide, currentSlide}) => (
                                  currentSlide !== 0 ?
                                      <i onClick={previousSlide} className={'arrow left'}/>
                                      : ''
                              )}
                              renderCenterRightControls={({nextSlide, slideCount, currentSlide}) => (
                                  currentSlide !== slideCount - 1 ?
                                      <i onClick={nextSlide} className={'arrow right'}/>
                                      : ''
                              )}
                    >
