### ISSUE TITLE
Slider Height always 81px

### ISSUE THREAD

**Issue by morningLemon** [FormidableLabs/nuka-carousel#219]
I am using Nuka as a responsive carousel component. When the page loads that I am testing the slider on the '.slider-list' element always loads with a '81px' height (this is set on the element style tag). When i focus or click on the slider it then renders the correct '.slider-list' height.

All slides are the same height & have varying sizes across screens sizes. I don't set the initialSlideHeight.

`<Carousel
        ref="carousel"
        decorators={decorators}
        slidesToShow={this.state.slidesToShow}
        slideIndex={this.state.slideIndex}
        slidesToScroll={this.state.slidesToScroll}
        easing={this.state.easing}
      >
        {CarouselSlides}
</Carousel>

constructor(props) {
    super(props)
    this.state = {
      slides: props.Slides,
      slideIndex: 0,
      slidesToShow: 3,
      slidesToScroll: 1,
      easing: 'easeInOutQuart'
    }
  }`

**Comment by Skeptron** [comment]
Getting the same issue as well

**Comment by morningLemon** [comment]
Set the height of your slider in your CSS, on the 'slider-list' class

**Comment by ryan-roemer** [comment]
Is this still an issue on `nuka-carousel@3.1.0+` now that we've landed https://github.com/FormidableLabs/nuka-carousel/pull/291?

**Comment by sarmeyer** [comment]
I've verified that this isn't an issue anymore. The slide height is dynamic
