### ISSUE TITLE
custom arrows

### ISSUE THREAD

**Issue by brennanerbz** [FormidableLabs/nuka-carousel#22]
How would you include custom arrows if using ES6 (no mixin support)?

**Comment by rafaelbiten** [comment]
This is how I did:

```javascript
import Carousel from 'nuka-carousel';
import carouselArrows from './common/carouselArrows';

// Then I use them like this
<Carousel decorators={carouselArrows}></Carousel>
```

And my carouselArrows file looks like this:
```javascript
import React from 'react';

export default [{
	component: class LeftArrow {
		render() {
			return (
				<div
					style={this.styleArrow(this.props.currentSlide === 0)}
					onClick={this.props.previousSlide}>
					Previous Slide
				</div>
			);
		}
		styleArrow(disabled) { return { opacity: disabled ? 0 : 1 }; }
	}
}, {
	component: class RightArrow {
		render() {
			return (
				<div
					style={this.styleArrow(this.props.currentSlide === this.props.slideCount - 1)}
					onClick={this.props.nextSlide}>
					Next Slide
				</div>
			);
		}
		styleArrow(disabled) { return { opacity: disabled ? 0 : 1 }; }
	}
}];
```

**Comment by brennanerbz** [comment]
Looks perfect. Thank you for sharing.

**Comment by rafaelbiten** [comment]
@brennanerbz, there was an issue on the code I share. For some reason, the slider is causing lots of re-renders on those arrows on drag/swipe, even when they don't need to re-render (not first or last slides).

To **kinda** fix this, I added `shouldComponentUpdate` to both arrows like this:

```javascript
shouldComponentUpdate() { return this.props.currentSlide === 0; } // left
shouldComponentUpdate() { return this.props.currentSlide === this.props.slideCount - 1; } // right
```

Please check the full updated code above... Also, if you leave those console.logs, check your console when you're on your first or last slide and try to drag/swipe the slide.

We're discussing this here: https://github.com/kenwheeler/nuka-carousel/issues/24

**Comment by shouze** [comment]
:+1:

**Comment by lcvbeek** [comment]
I solved it using CSS only, as following:

`.slider {
   &-decorator-0 { /* Previous */
      & > button {
        visibility: hidden;

        &::after {
          position: absolute;
          left: -100%;
          padding: 10px;
          visibility: visible !important;
          width: 2rem;
          height: 2rem;
          border-radius: 100px;
          background: rgba(0, 0, 0, 0.5);
          color: #fff;
          content: '\25C5';
          font-family: SSAir;
        }
      }
    }

    &-decorator-1 { /* Next */
      & > button {
        visibility: hidden;

        &::after {
          position: absolute;
          right: -100%;
          padding: 10px;
          visibility: visible !important;
          width: 2rem;
          height: 2rem;
          border-radius: 100px;
          background: rgba(0, 0, 0, 0.5);
          color: #fff;
          content: '\25BB';
          font-family: SSAir;
        }
      }
    }
}`
