### ISSUE TITLE
createClass deprecated in React Fiber  

### ISSUE THREAD

**Issue by spyworldxp** [FormidableLabs/nuka-carousel#230]
React Fiber is under beta version.
[https://github.com/facebook/react/issues/10294](https://github.com/facebook/react/issues/10294)

Once complete updated, this error message will show up:
``` 
uncaught TypeError: _react2.default.createClass is not a function
```

**Comment by kenwheeler** [comment]
Fixed in https://github.com/FormidableLabs/nuka-carousel/releases/tag/v3.0.0
