### ISSUE TITLE
React.createClass is deprecated

### ISSUE THREAD

**Issue by ido-ofir** [FormidableLabs/nuka-carousel#236]
When you try to run nuka-carousel with React >= 15.6.0 some warnings appear because React.createClass is being deprecated.

occurrences:
/master/src/carousel.js:
![image](https://user-images.githubusercontent.com/6238323/29073939-34fbfab4-7c56-11e7-919b-359ad7ed783b.png)

/master/src/decorators.js:
![image](https://user-images.githubusercontent.com/6238323/29074001-6b7c0232-7c56-11e7-9e7a-92a0aba26b1f.png)

![image](https://user-images.githubusercontent.com/6238323/29074022-7d3f0438-7c56-11e7-965b-7c6ab9acf9a8.png)

![image](https://user-images.githubusercontent.com/6238323/29074041-8b90ce72-7c56-11e7-8cbd-6616403f8d4c.png)

should use [create-react-class](https://www.npmjs.com/package/create-react-class) instead.

Thanks :)

**Comment by jonkwheeler** [comment]
I created a PR for this https://github.com/FormidableLabs/nuka-carousel/pull/237

**Comment by kenwheeler** [comment]
Fixed in https://github.com/FormidableLabs/nuka-carousel/releases/tag/v3.0.0
