### ISSUE TITLE
Responsiveness for Groups at certain breakpoints?

### ISSUE THREAD

**Issue by jonkwheeler** [FormidableLabs/nuka-carousel#238]
Anyone doing responsive groups? Like SlidesToShow=3 for desktop at 1024px, 2 for tablet at 768px, and 1 for mobile at 600px. 

Any help would be appreciated. The original Slick carousel had this option. Thanks.

**Comment by kenwheeler** [comment]
I would do that in your react code. We built responsive containers that would pass option sets as props at certain string breakpoint definitions.
