### ISSUE TITLE
After slide broke analytics on our carousels

### ISSUE THREAD

**Issue by ajoshi0** [FormidableLabs/nuka-carousel#239]
https://github.com/FormidableLabs/nuka-carousel/commit/a5ed5aada530ddd5e678f09fa6bf7e1c2b393621

This change broke analytics on all walmart carousels can we revert this change by any chance or fix it like this

```
    if (index !== this.state.currentSlide) {
      this.props.afterSlide(index);
    }
    this.setState({
      currentSlide: index
    }, function () {
      self.animateSlide();
      self.resetAutoplay();
      self.setExternalData();
    });
```

2.0.4 release is working fine after that you have only one release 2.2.0 which has https://github.com/FormidableLabs/nuka-carousel/commit/a5ed5aada530ddd5e678f09fa6bf7e1c2b393621 change

@kenwheeler

**Comment by kenwheeler** [comment]
Fixed
