### ISSUE TITLE
the "create-react-class" SHOULD in the dependencies

### ISSUE THREAD

**Issue by horizon0514** [FormidableLabs/nuka-carousel#241]
RT
version: 2.3.0
I found the "create-react-class" in the devDependencies, it caused the nuka-carousel not install the "create-react-class" package, then webpack cant resolve it.

please put the "create-react-class" to the dependencies

**Comment by jonkwheeler** [comment]
https://github.com/FormidableLabs/nuka-carousel/pull/242

**Comment by kenwheeler** [comment]
fixed in https://github.com/FormidableLabs/nuka-carousel/releases/tag/v3.0.0
