### ISSUE TITLE
get current slide index function

### ISSUE THREAD

**Issue by lauterry** [FormidableLabs/nuka-carousel#244]
Hello

Actually, I have a use case where I need to get the current slide index.

It would be great to provide a function getCurrentSlideIndex() like goToSlide()

Thanks

**Comment by nicksp** [comment]
MR is ready for review.

**Comment by carlospaelinck** [comment]
The current slide index can be exposed through the `afterSlide={currentIndex => ... }` prop or controlled by the parent component through the `slideIndex` prop.
