### ISSUE TITLE
Remove dots

### ISSUE THREAD

**Issue by nehiljain** [FormidableLabs/nuka-carousel#245]
Is there a way to remove the dots at the bottom of the slider?

**Comment by aszmyd** [comment]
You can probably hide them with css. I believe its an element with class `slider-decorator-2` but there should definitely be an option to disable them from configuration.

**Comment by asis** [comment]
I think you can remove all the "decorators" ("prev" and "next" buttons, and dots) passing an empty array to the `decorators` prop:
```
<Carousel decorators={[]}>{ /* slides here */}</Carousel>
```
If you want to remove the dots but keep the buttons... you can import the default decorators, slicing them to remove the dots. Something like:
```
var DefaultDecorators = require("nuka-decorators/lib/decorators");

<Carousel decorators={DefaultDecorators.slice(0,2)}/>{ /* slides */ }</Carousel>
```
But this solution is quite brittle, as it is coupled with the actual implementation and may break unexpectedly if the library changes 😞

**Comment by kenwheeler** [comment]
Yeah you would remove them from decorators

**Comment by arzafran** [comment]
IMO I've found a better solution to hide those decorators:

```jsx
  <Carousel
    swiping
    renderBottomCenterControls={false}
  >
```

**Comment by asis** [comment]
It is a better solution, now that you can do it ;)
I think this render*Controls props were added after this issue was closed :D

**Comment by karthikmurugadoss** [comment]
Setting renderBottomCenterControls as false works but raises a console warning though!

**Comment by bmoquist** [comment]
No warning --- 

```js
renderBottomCenterControls={() => {}}
```

**Comment by burakguneli** [comment]
Also `renderBottomCenterControls={null}` works without error.

**Comment by gzcisco720** [comment]
just use `withoutControls ={false}`

**Comment by freakk101** [comment]
> just use `withoutControls ={false}`

`withoutControls ={true}`

**Comment by Abhay7845** [comment]
hide previous and next button from Carousel  in react JS

<Carousel controls={false}  interval ={null} >
//code statements
</Carousel >
