### ISSUE TITLE
was there a git accident?

### ISSUE THREAD

**Issue by sleeparrow** [FormidableLabs/nuka-carousel#249]
i notice there's commits missing from the end of 2016...

here's some PRs that were merged that i can't find in there:
#155 #156 #160 #163 

there's probably more between #155 and #165 but they're less obvious so i haven't included them

**Comment by marhalpert** [comment]
Have a look here
https://github.com/FormidableLabs/nuka-carousel/issues/172/#issuecomment-272213552

**Comment by sleeparrow** [comment]
kk. from that thread:

<img width="776" alt="screen shot 2017-10-26 at 8 46 55 am" src="https://user-images.githubusercontent.com/6981186/32053782-4c7073ca-ba2a-11e7-8d69-21a1b12b09ab.png">

**Comment by ryan-roemer** [comment]
Closing this as everything is focused on going forward post-v4. Feel free to open up new individual issues if anything is missing in v4... Thanks!

**Comment by sleeparrow** [comment]
maybe you should open/reopen issues for the PRs that are no longer merged if you're gonna close this. that seems like a better resolution for this issue.
