### ISSUE TITLE
autoplayInterval is not working consistently for longer time intervals

### ISSUE THREAD

**Issue by rajkumar215** [FormidableLabs/nuka-carousel#250]
Hi,
I have the requirement to rotate each slider with 40 mins time interval ( 
autoplayInterval : 2400000 ). It is not working as expected if I give longer time intervals. Works perfectly if I input shorter time intervals something below 5 mins.

Is there any limit set for autoplayInterval ?

Thanks for your help

Raj

**Comment by kenwheeler** [comment]
I mean, this gets passed directly to setInterval, so I would examine the capabilities of that API https://github.com/FormidableLabs/nuka-carousel/blob/master/src/carousel.js#L522

I'm unsure as to how the limits work there.
