### ISSUE TITLE
Module not found: Can't resolve 'create-react-class'

### ISSUE THREAD

**Issue by mariacheline** [FormidableLabs/nuka-carousel#254]
Module not found in ...\node_modules\nuka-carousel\lib'

Hi I keep having this error. Any idea how to solve it?

**Comment by zlv-thisF** [comment]
+1

**Comment by hamedmam** [comment]
it seems to be a problem with new update (React 16) since I got it working on 15 and when I installed it on 16 I got the same error. I think react 16 stopped supporting create-react-class and this tool has been created a long time ago

**Comment by kenwheeler** [comment]
Fixed in https://github.com/FormidableLabs/nuka-carousel/releases/tag/v3.0.0

**Comment by mariacheline** [comment]
I ended up installing create-react-class.
