### ISSUE TITLE
kw-react-tween-state does not support react 16

### ISSUE THREAD

**Issue by nickspiel** [FormidableLabs/nuka-carousel#258]
After the upgrade to support react 16 #255  it looks like one dependency update was missed. `kw-react-tween-state` only support react and react-dom ^0.14.8 and ^15.0.1.

`npm ls` yields the following:

```
npm ERR! peer dep missing: react@^0.14.8 || ^15.0.1, required by kw-react-tween-state@0.1.5
npm ERR! peer dep missing: react-dom@^0.14.8 || ^15.0.1, required by kw-react-tween-state@0.1.5
npm ERR! extraneous: react@15.6.2 /Users/nick.spiel/Projects/listing-ui/project/node_modules/kw-react-tween-state/node_modules/react
```

It looks like the library has been deprecated or moved to [react-tween-state](https://github.com/chenglou/react-tween-state/)

**Comment by jeffnicholson-arcurve** [comment]
@kenwheeler any chance on getting #260 merged and released in the near future?

**Comment by ryan-roemer** [comment]
Fixed in https://github.com/FormidableLabs/nuka-carousel/pull/275
