### ISSUE TITLE
Last slide won't center when using fractional number for slidesToShow

### ISSUE THREAD

**Issue by ericdvb** [FormidableLabs/nuka-carousel#264]
When using a fractional number for `slidesToShow` (i.e. 1.667) and with `cellAlign` set to `center`, advancing through slides works properly until the last slide, when the slider list will only translate far enough to get the last slide aligned to the right of the frame. Dragging the slider list to the left after this threshold triggers the ease animation.

Expected behavior would be: show focused slide plus one third (for the slidesToShow value cited above) of previous and next slides at all times. If first or last slide is focused, show empty space before or after the focused slide respectively. Focused slide should always be centered.

Behavior is as expected when passing in the aforementioned props on http://kenwheeler.github.io/nuka-carousel/, so I'm wondering if this is something about my setup? Or if the version that's pulling from npm is not the same as what's being demoed on the github.io page?

**Comment by ashika01** [comment]
@ericdvb: The link that shows the behavior is outdated. The code based has changed a lot since the link. What you see is the expected behavior.
