### ISSUE TITLE
React 16 support

### ISSUE THREAD

**Issue by bliitzkrieg** [FormidableLabs/nuka-carousel#267]
Any idea when this will support R16? It looks like PR's are made that resolve the issue but haven't been merged.

Specifically: 
https://github.com/FormidableLabs/nuka-carousel/issues/258

**Comment by dschinkel** [comment]
if this is a port off `react-slick` and there has not been a response to this yet in here, probably never. In fact the owner of react-slick is absent and his still doesn't work in React 16 either...and I believe nuka-carousel is a port off that if I'm not wrong...

**Comment by ryan-roemer** [comment]
Fixed in https://github.com/FormidableLabs/nuka-carousel/pull/275
