### ISSUE TITLE
cdnjs hosting

### ISSUE THREAD

**Issue by sashberd** [FormidableLabs/nuka-carousel#268]
Hi
We would like to [add](https://github.com/cdnjs/cdnjs/issues/9662) your library to cdnjs hosting
What exact files should we add?
Thanks

**Comment by sashberd** [comment]
@kenwheeler Could you help us with this one. Thanks

**Comment by ryan-roemer** [comment]
@sashberd once we publish our v4.0 release, you'll want everything that is available at https://unpkg.com/nuka-carousel/dist assuming we publish `dist` standalone build. (Watch #295 to check if we do this beyond babel'ed directories `es/` and `lib/`)

Thanks!
