### ISSUE TITLE
reference internal carousel controls by separate props instead of decorators array

### ISSUE THREAD

**Issue by mvanroon** [FormidableLabs/nuka-carousel#270]
What is the idea behind using:

```
<Carousel
    decorators={[PrevButton, NextButton, Dots]}
>
```

instead of for example:

```
<Carousel
    prevSlide: PrevButton,
    nextSlide: NextButton,
    dots: Dots
>
```

If you agree that the latter might work better, I'll make a PR. I won't if there's good reason you went for the decorators array.

Cheers

**Comment by carlospaelinck** [comment]
There are 8 positions for decorators which we are going to rename controls. There will be render props for each of the 8 positions for version 4.0.

**Comment by mackermans** [comment]
Hi @carlospaelinck, not sure if I missed a changelog somewhere, however, I would definitely appreciate knowing what breaking changes were introduced and how I would have to upgrade from v3 to v4 (and I'm sure other people too, that include your package in their projects). It took me a little while to figure out what changed, but I managed to upgrade in the end by finding this issue and changing the decorators to render props.

Anyway, just a suggestion coming from a slightly painful experience upgrading 👍 

Thanks!

**Comment by carlospaelinck** [comment]
@mackermans Updated the release entry with changes.
