### ISSUE TITLE
Does This Work With React v16?

### ISSUE THREAD

**Issue by dschinkel** [FormidableLabs/nuka-carousel#273]
Has anyone used this successfully over React v16? Did you have any issues on that version of React with this? Just checking before I try to play with it.  Doesn't look like it does, this is an old post about it [267](https://github.com/FormidableLabs/nuka-carousel/issues/267) in the issues list and it's still open.

react-slick is not compatible with React 16 so I'm looking for an alternative carousel.

**Comment by bliitzkrieg** [comment]
This library works with R16 just yells are you on NPM install regarding deps issue. We went ahead and went forward with it regardless and so far so good. We have a backlog task to move away from this dependency when we can though just incase it comes and bites us in the ass in the future.

**Comment by ryan-roemer** [comment]
Fixed in https://github.com/FormidableLabs/nuka-carousel/pull/275
