### ISSUE TITLE
wrapAround problem for slidesToShow>1

### ISSUE THREAD

**Issue by nimatrueway** [FormidableLabs/nuka-carousel#276]
Thanks for the neat library ! This is the little problem I bumped into. In case you set `slidesToShow` a number bigger than one like `3`, when scrolling back from index `0` in the middle of the way `item0` disappears.

[item0 hides when scrolling back from index0 - recorded](https://gfycat.com/gifs/detail/MassiveFalseBarnswallow)

Minimal sandbox of the problem:

[![Edit m57o4yjm89](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/m57o4yjm89)

**Comment by fjaskolski** [comment]
Hi there! Got a similar problem (#259). For me, the @ddcrogerk's fix did the job.

**Comment by carlospaelinck** [comment]
@nimatrueway We have refactored the internals for Nuka. In our testing `slidesToShow` works with `wrapAround` provided `slidesToShow` is `slides - 1`.
