### ISSUE TITLE
ReferenceError: Unknown plugin "add-module-exports"

### ISSUE THREAD

**Issue by jcfariadias** [FormidableLabs/nuka-carousel#280]
Hello,

I've upgraded nuka-carousel to the latest version and I got this error when building with browserify
`
ReferenceError: Unknown plugin "add-module-exports" specified in node_modules/nuka-carousel/.babelrc" at 0, attempted to resolve relative to node_modules/nuka-carousel`

Anyone having this problem?

**Comment by ryan-roemer** [comment]
Your build tool shouldn't read other packages' `.babelrc`.

And at any rate, this will go away when we publish the next version of Nuka since it has an npm whitelist at https://github.com/FormidableLabs/nuka-carousel/blob/master/.npmignore and won't publish our `.babelrc` any more.

**Comment by ryan-roemer** [comment]
Also, `master` no longer has that plugin anyways, so closing this issue :)

https://github.com/FormidableLabs/nuka-carousel/blob/master/.babelrc
