### ISSUE TITLE
Infrastructure: Update `es` build, modern webpack, yadda, yadda

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/nuka-carousel#282]
- [x] Remove `gulp`. Switch to npm workflows.
- [x] Remove + `.gitignore` `package-lock.json` and switch to `yarn`.
- [x] Update Travis to use Yarn.
- [x] Use an `.npmignore` whitelist to remove all the unnecessary cruft you can currently see in: https://unpkg.com/nuka-carousel@3.0.1/
- [x] Bump all relevant dependencies.
- [x] Update babel stuff
- [x] Update webpack versions
- [x] Export an `es/` directory
- [x] Remove `lib` from git source. Fixes #224
- [x] Replace phantom in Karma with headless chrome. (See Radium)

**Comment by ryan-roemer** [comment]
Headless chrome is only a work item if we're still doing PhantomJS.

Jest just uses jsdom so not needed for any tests using Jest.

We could separately do functional tests with headless chrome, but I'd prefer we just ticket out and scope new work like that to properly plan.

**Comment by carlospaelinck** [comment]
Yeah. That sounds good.

**Comment by ryan-roemer** [comment]
Fantastic work @carlospaelinck !!!

I've moved the remaining `npm version` work (which is one of our final things for v4 release) to https://github.com/FormidableLabs/nuka-carousel/issues/295 with specific instructions.
