### ISSUE TITLE
carousel with dynamic data using `map` not working as expected

### ISSUE THREAD

**Issue by Deniscapp** [FormidableLabs/nuka-carousel#284]
Hey guys, I am trying to accomplish a carousel with components coming accordingly with this `keys` array. However, it's not working as expected. I end up with all the components side by side, creating a huge horizontal scroll with the carousel navigator in the middle. What am I doing wrong?
Thanks!
```
<NukaCarousel>
          {keys.map(key => (
              <LevelIndicatorNew
                key={key}
                levels={levels}
                indicator={key}
                person={person}
                byLevel={dataByIndicator[key]}
                cycle={cycle}
                changeRoute={this.context.changeRoute}
              />
            ))}
</NukaCarousel>
```

**Comment by sefeek** [comment]
having same problem . found any solution?

**Comment by Deniscapp** [comment]
Take it a look here https://github.com/FormidableLabs/nuka-carousel/issues/349

**Comment by sefeek** [comment]
for me the value is not displaying
this is my carousel

 <Carousel
             wrapAround
             
             slideIndex={this.state.slideIndex}
             afterSlide={slideIndex => this.setState({ slideIndex })}>

                    {this.state.explanations.map((Explanation,i) => (
                    <div key={i}>
                       <h2>{Explanation.explanation_name}</h2>
                      <MathJax math={Explanation.text.toString('html',null)} />
                      </div>
                    ))}  
          </Carousel>
