### ISSUE TITLE
Decorators positioning is hard-coded

### ISSUE THREAD

**Issue by RickSlijkhuis** [FormidableLabs/nuka-carousel#29]
getDecoratorStyles() on line 635 should have a way to be overwritten. I cannot position decorators on another position then the cases that have been set here.

**Comment by aij** [comment]
getDecoratorStyles() is only used for the parent <div>. You can use any style you want in your decorators.

It does seem like a somewhat odd design though.

**Comment by robertleeplummerjr** [comment]
All this privatizing of code is an illusion of power, there is always a way around it:

```js
class MyNukaCarousel extends NukaCarousel {
  constructor(props) {
    super(props);
    
    this.getDecoratorStyles = function(position) {
      //put whatever position styles you want here
      return {
        position: 'absolute',
        top: 0,
        left: 0
      };
    };
  }
}
```

Not pretty, but like ![](http://www.techzonics.com/hammer-vise-grips-a.jpg), it gets the job done.  Ideally there would be a better way, or just fork, extend, repeat.
