### ISSUE TITLE
Image placement lag on large number of slides

### ISSUE THREAD

**Issue by lerayne** [FormidableLabs/nuka-carousel#307]
https://youtu.be/JlBBt3HyKac

On this video is an example of the wrong behavior: This particular instance has relatively large number of photos (about 18) and the longer I go with the "next" button, the more prominent becomes the issue: previous photo disappears before sliding animation ends. The same goes for the reverse direction, image that appears from the left appears few milliseconds later than it has to be.

Of source this requires "wrapAround" to be turned on

**Comment by alexlande** [comment]
Hi @lerayne! I can't reproduce this behavior in the demo. If you could share your example that would make it a lot easier to track down the problem. Thanks!

**Comment by sutriptaroy** [comment]
Taking too much time to show the carousel after all api data loaded successfully on the page. after loaded all data, it's takes more than 3-4 secs and suddenly coming. is there any solution? why it is taking so much time? is there any idea?

**Comment by hogvarce** [comment]
have the same problem. Is there any solution?

**Comment by sarmeyer** [comment]
Can you please provide a minimal repository or a CodeSandbox with install + error reproduction steps so we can jump and see what you see? Thanks!

**Comment by sarmeyer** [comment]
Would anyone be able to pass along a repo or CodeSandbox to help us investigate this issue? Thanks!
