### ISSUE TITLE
V4.0 Could u add new props like `withoutControls`

### ISSUE THREAD

**Issue by rkovalyov** [FormidableLabs/nuka-carousel#313]
For avoiding awful declaration
```js
<Carousel
  renderTopCenterControls={()=>null}
  renderCenterLeftControls={()=>null}
  renderCenterRightControls={()=>null}
  renderBottomCenterControls={()=>null}
/>
```

**Comment by Klaasvaak** [comment]
Maybe there should be 1 render prop for controls. And let the implementer figure out where to position the controls. 

An other options could be not having control render props at all and make sure the implementer can make these by theirselves using the other callbacks. So this library can focus on only doing the carousel part correctly, which it also does btw 👍

**Comment by davidbucka** [comment]
Hey guys, I just checked in a new pull request that adds the desired prop `withoutControls` 🍻
