### ISSUE TITLE
Failed to compile with react-create-app

### ISSUE THREAD

**Issue by maxdyy** [FormidableLabs/nuka-carousel#323]
I'm trying to npm run build on my react-create-app project and I'm having this issue:

> Creating an optimized production build...
> Failed to compile.
> 
> Failed to minify the code from this file:

 	./node_modules/nuka-carousel/lib/decorators.js:93

> Read more here: http://bit.ly/2tRViJ9
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1

Everything runs perfectly on dev.

Rreate-react-app says that some third-party packages don't compile their code to ES5 before publishing to npm.

Also suggested to open this issue and ask that the package be published pre-compiled.

Any suggestions on what to do in this case?

Thanks

**Comment by maxdyy** [comment]
Solved manually recompiling 

`node_modules/nuka-carousel/lib/drousel.js && decorators.js`

I literally copy-pasted to https://babeljs.io/repl/

**Comment by ryan-roemer** [comment]
Can you post a github repo of the minimal amount of code that exhibited the failure with install + error reproduction steps? Our `lib` directory is fully es5. https://unpkg.com/nuka-carousel@4.0.3/lib/decorators.js
