### ISSUE TITLE
First and last slide are not displayed when wrapAround is set and slidesToShow is a decimal number

### ISSUE THREAD

**Issue by mdimovska** [FormidableLabs/nuka-carousel#324]
Having the following options set:
```
cellAlign='center'
slidesToShow={1.25}
wrapAround
```
the last slide is not shown when the 1st slide is active:
![image](https://user-images.githubusercontent.com/6908242/38234400-15c3796e-371e-11e8-88ef-765906355285.png)

Same applies for the first slide (it's not shown when the last slide is active):
![image](https://user-images.githubusercontent.com/6908242/38234430-26a30614-371e-11e8-96a8-04bd31b09fbc.png)

The other slides are displayed properly:
![image](https://user-images.githubusercontent.com/6908242/38234445-33bf6180-371e-11e8-9c90-c9aa089476e6.png)

**How to reproduce the issue:**
Set the following options in the Carousel in the demo app:
```
cellAlign='center'
slidesToShow={1.25}
wrapAround
```

**Comment by nicomfe** [comment]
any news about this? having the same issue
