### ISSUE TITLE
`slideIndex` can not set  correctly

### ISSUE THREAD

**Issue by warmhug** [FormidableLabs/nuka-carousel#327]
https://github.com/FormidableLabs/nuka-carousel/blob/a92efc089bca0e4b755ce62de9b35d2791b54cc0/src/index.js#L432

If `goToSlide`  invoked from `componentWillReceiveProps` and `this.pros.children.length < nextProps.children.length`, thus cannot set `slideIndex` correctly. Is it a bug?

**Comment by alexlande** [comment]
Hi @warmhug! I don't think this is a bug. The carousel can't move to a slide that hasn't been rendered yet. If you call `goToSlide` from `componentDidUpdate` you should get the behavior you're looking for.
