### ISSUE TITLE
Dots color

### ISSUE THREAD

**Issue by s-l-ivanov** [FormidableLabs/nuka-carousel#333]
Is there are any way to change the dots color?

**Comment by alexlande** [comment]
Not directly. If you want to customize the default controls, you can use the `render*Controls` props to render custom controls that look and behave however you like. Docs on those are here: https://github.com/FormidableLabs/nuka-carousel#rendercontrols

So to replace the dots, you could use `renderBottomCenterControls`, which is called with `goToSlide`, `currentSlide` and `slideCount` to build custom controls.
