### ISSUE TITLE
Nuka doesn't react to render controls prop change

### ISSUE THREAD

**Issue by moimael** [FormidableLabs/nuka-carousel#339]
Hi,

I'm trying to upgrade to v4, and I have an issue with the new control render props. They work fine when set the first time, but upon changing their value (in my case I'm changing the previous/next control depending on when you are on mobile or desktop), the carousel doesn't rerender the controls.

I can see the renderCenterCenterControls and renderBottomCenterControls props change when I resize my browser window, but it's not reflected in the carousel. If I do a full page reload, I can see the correct controls being displayed. Even calling react forceUpdate after a resize doesn't fix it.

It worked well in v3 with decorators prop.

Thanks.

**Comment by zhaostan** [comment]
Hey @moimael do you think you can provide a snippet of what you are trying to do? I can't reproduce what you described above, but I might be missing something 😄

**Comment by moimael** [comment]
Yes of course, here you go:

https://codesandbox.io/s/54p0lx1pwp

It's a stripped down version of the code I use. If you resize the preview you will see the isMobile state changing, which trigger a prop change for control rendering, but the controls stay the same.

**Comment by zhaostan** [comment]
Hey @moimael. I see the problem now. First of all, as of right now in the nuka-carousel source code we have this: 
```
constructor() {
    super(...arguments);
    this.controlsMap = [
      { func: this.props.renderTopLeftControls, key: 'TopLeft' },
      { func: this.props.renderTopCenterControls, key: 'TopCenter' },
      { func: this.props.renderTopRightControls, key: 'TopRight' },
      { func: this.props.renderCenterLeftControls, key: 'CenterLeft' },
      { func: this.props.renderCenterCenterControls, key: 'CenterCenter' },
      { func: this.props.renderCenterRightControls, key: 'CenterRight' },
      { func: this.props.renderBottomLeftControls, key: 'BottomLeft' },
      { func: this.props.renderBottomCenterControls, key: 'BottomCenter' },
      { func: this.props.renderBottomRightControls, key: 'BottomRight' }
    ];
```

So when you pass in an initial value of `null` as a prop, the Carousel render function will reference that null value even after updating. We can fix this by adding a `componentDidUpdate`.

However right now you can do this as a workaround: 
```
         renderCenterCenterControls={(...arg) =>
            this.state.isMobile ? null : renderCenterCenterControls(...arg);
          }
          renderBottomCenterControls={(...arg) =>
            this.state.isMobile ? renderBottomCenterControls(...arg) : null
          }
```
Also notice that I used this.state.isMobile instead of a reference to this.state.isMobile. Using a reference will not work because it will always reference the initial `null` value in the closure.

**Comment by moimael** [comment]
Thanks a lot !
