### ISSUE TITLE
NEXT button / infinite loop

### ISSUE THREAD

**Issue by sbroadhurst** [FormidableLabs/nuka-carousel#340]
is there a way to make the NEXT button nonfunctional after the last slide is displayed, because right now my carousel has a bunch of blank slides after the last slide with material. Or have we figured out the infinite loop yet? wrapAround doesn't work like an infinite loop , or it could be those blank slides ?

**Comment by bibblebabl** [comment]
@sbroadhurst do I get you right, you are talking about #194 issue?

I have same problem and it seems not to be solved 
![may-07-2018 22-43-46](https://user-images.githubusercontent.com/9008978/39722818-7b2239dc-524c-11e8-9324-85a8ee2fe2aa.gif)

**Comment by sbroadhurst** [comment]
yep same issue as you bibblebabl

**Comment by BrandonS8** [comment]
Having the same issue and noticed if I click and hold (like you would to drag) to the right of the last slide the other slides show up where they should but disappear as soon as I release the mouse

**Comment by sbroadhurst** [comment]
do we have a possible fix or solution in the works?

**Comment by gislenescarvalho** [comment]
I have the same problem with my carousel.

**Comment by samwhale** [comment]
Pull #369 implements a fix for this
