### ISSUE TITLE
Pagination dots style

### ISSUE THREAD

**Issue by sharoneh** [FormidableLabs/nuka-carousel#343]
How can I style the pagination dots?

**Comment by sharoneh** [comment]
got it:

<Carousel
            renderBottomRightControls={(props) => {
                let indexes = [];

                for(let i = 0; i < props.slideCount; i++) {
                    indexes.push(i);
                }

                return (
                        <div className="paging-dots">
                            { indexes.map(index => (
                                <button
                                    key={index}
                                    onClick={props.goToSlide.bind(null, index)}
                                    className={(props.currentSlide === index) ? 'active' : ''}
                                >
                                    &bull;
                                </button>
                            )) }
                        </div>
                );
            }}
        >

**Comment by carry555** [comment]
加上这段代码后 为什么原来的分页点样式没有被去掉 ？
