### ISSUE TITLE
Wrong initialSlideHeight

### ISSUE THREAD

**Issue by ncuillery** [FormidableLabs/nuka-carousel#348]
I used the carousel with: 

```jsx
<Carousel
  slidesToShow={2}
  initialSlideHeight={64}
>
```

The resulting height of the slide is not 64 but 128. I've digged into the source and I think it is caused by:

https://github.com/FormidableLabs/nuka-carousel/blob/46de64584c296b2c464435565588e28289338bb5/src/index.js#L665-L671

I guess the multiplication L670 should only be done if `this.props.vertical` is truthy.

**Comment by ryan-roemer** [comment]
@ncuillery -- Thanks for looking into this! Would you be able to open a PR with a regression test?

**Comment by ncuillery** [comment]
I'm pretty busy these days, that's why I've just open the issue for now. But yeah I'll keep that in mind
