### ISSUE TITLE
Nuka is miscalculating width

### ISSUE THREAD

**Issue by Deniscapp** [FormidableLabs/nuka-carousel#349]
I am currently using the last version, however, I've been having this same problem since many versions ago.

I simply have something like this:
```
 <NukaCarousel
        autoplay
        dragging
        wrapAround
        renderCenterLeftControls={LeftArrow }
        renderCenterRightControls={RightArrow}
        renderBottomCenterControls={Indicators}
      >
        {banner.images.map(url => <img key={url} src={url} />)}
 </NukaCarousel>
```

If I only have an image on my array, it's fine. But if I have > 1, somehow `Nuka` miscalculates its own size and I end up with a huge carousel, creating an enormous `width` on my page, breaking everything.

EDIT: If I use `vertical={true}`, its size is correctly calculated.

Any help on this?
Thank you!

**Comment by Deniscapp** [comment]
The problem is exactly here: https://github.com/FormidableLabs/nuka-carousel/blob/master/src/index.js#L801

If I override this style to be `auto`, everything works fine. Why can't we make `auto` default?

**Comment by stunaz** [comment]
got the same issue, to fix it you should have a wrapper with a max width.
the problem is that my parent width is unknown, I use flex-box. can't figure out what to set.

**Comment by Deniscapp** [comment]
@stunaz, this worked for me:
```
.slider > .slider-frame > .slider-list {
   width: auto !important;
 }
```

**Comment by stunaz** [comment]
I found [react-container-dimensions](https://github.com/okonet/react-container-dimensions) , worked really good for me. used it like:
```javascript
            <ContainerDimensions>
                    {({ width }) => (
                        <Carousel
                            width={`${width - 16}px`}
                        >
                           ...
                        </Carousel>
                    )}
                </ContainerDimensions>
```

**Comment by Deniscapp** [comment]
That's quite interesting! I will take a look. Thanks!

**Comment by cphoover** [comment]
:+1:  Experiencing the same thing

**Comment by cphoover** [comment]
And none of these ideas work

**Comment by lewtur** [comment]
> @stunaz, this worked for me:
> 
> ```
> .slider > .slider-frame > .slider-list {
>    width: auto !important;
>  }
> ```

We had an issue where the react app was being loaded in an iframe, and on iOS devices only the iframe had a width equal to the full size of the carousel, i.e., all the slides side by side, which caused rendering issues as it was bigger than the phone screen. This fixed it, thanks!

**Comment by fmturati** [comment]
> > @stunaz, this worked for me:
> > ```
> > .slider > .slider-frame > .slider-list {
> >    width: auto !important;
> >  }
> > ```
> 
> We had an issue where the react app was being loaded in an iframe, and on iOS devices only the iframe had a width equal to the full size of the carousel, i.e., all the slides side by side, which caused rendering issues as it was bigger than the phone screen. This fixed it, thanks!

Where did you find this? I can't find this code anywhere..

**Comment by BatuhanW** [comment]
> I found [react-container-dimensions](https://github.com/okonet/react-container-dimensions) , worked really good for me. used it like:
> 
> ```js
>             <ContainerDimensions>
>                     {({ width }) => (
>                         <Carousel
>                             width={`${width}px`}
>                         >
>                            ...
>                         </Carousel>
>                     )}
>                 </ContainerDimensions>
> ```

Works for me! Thanks ❤️

**Comment by polarathene** [comment]
Another alternative is to set `min-width: 0;` on parent container(eg div with flex: 1 on it), this fixed the carousel as a flex item to get the appropriate width expected.

**Comment by lucacaputo** [comment]
> @stunaz, this worked for me:
> 
> ```
> .slider > .slider-frame > .slider-list {
>    width: auto !important;
>  }
> ```

the issue is still present, this is the only working solution at the moment. thanks

**Comment by abdelrahmanbaher1** [comment]
this one fixed it for me 
  <Carousel
                slideWidth={'400'}
                slidesToShow={2}
                
   Specify the slide width for each children component , add the 'slideWidth' prop to the carousel component
