### ISSUE TITLE
React-Router with Carousel

### ISSUE THREAD

**Issue by pnitto** [FormidableLabs/nuka-carousel#35]
I have been trying to set up my carousel with links to another page but it looks like the carousel obliterates  my react-router links. Is this possible to do?

**Comment by aij** [comment]
FWIW, I'm using <Link> from react-router inside the carousel and it works fine...

**Comment by zuizuihao** [comment]
+1

**Comment by ashika01** [comment]
Closing the issue because it can not be reproduced in newer version(4.3.10). Please reopen if you still experience this issue with the latest stable version.

Thank you.
