### ISSUE TITLE
Initial height fixed to 20 px

### ISSUE THREAD

**Issue by Sashkan** [FormidableLabs/nuka-carousel#352]
I'm using nuka-carousel to display a list of images, but no matter what I try, the first image is always cropped: even if my image is 600x600px, the carousel (and more precisely, it's ```.slide-list``` element) gets a height of 20px.

The only way to get the correct size is to use arrows to get to next image, and then get back to first image. How can I make sure that my Carousel gets initialized at his first slide's height ?

**Comment by sarmeyer** [comment]
@Sashkan are you still experiencing this issue with the latest release 4.4.0? I cannot reproduce.

**Comment by jflayhart** [comment]
I am experiencing this as well! Not until resizing or clicking to next slide does it work.

**Comment by jflayhart** [comment]
This has been the best solution so far:

```
// snippet of class method
handleLoadImage = () => {
  this.carouselRef.setDimensions()
}
// snippet of component
<Carousel ref={node => { this.carouselRef = node }}>
  <img onLoad={this.handleLoadImage} />
</Carousel>
```

**Comment by sarahbethfederman** [comment]
I'm also experiencing this with a height of 21
