### ISSUE TITLE
define is not a function

### ISSUE THREAD

**Issue by HarryFaulkner** [FormidableLabs/nuka-carousel#356]
I'm getting an Error when importing (`import Carousel from 'nuka-carousel`). I also noticed the component name didn't auto complete on import like all of other modules do. It has definitely installed and is in the node-modules directory.

I'm sure I have all the necessary dependencies installed so I don't know where to look next. 

Here's the error 
![error](https://user-images.githubusercontent.com/28293997/40983701-18ea5360-68d8-11e8-8032-f45dcaddd566.jpeg)

Any advice on this would be greatly appreciated, Thanks.

**Comment by ryan-roemer** [comment]
@HarryFaulkner -- Can you create a minimal repository with install + error reproduction steps so we can clone it down and see what you're seeing? Thanks!

**Comment by HarryFaulkner** [comment]
@ryan-roemer Thanks for the quick reply. No need, It was a problem with my Webpack setup I haven't changed it in a while and the config had some stale rules.

Removing`
{
    test: /\.js/,
        use: 'imports-loader?define=>false '
},` from my module rules did the trick. 

Thanks anyway 👍
