### ISSUE TITLE
wrapAround unbind onClick on most of the slides

### ISSUE THREAD

**Issue by michalg42** [FormidableLabs/nuka-carousel#362]
Here is fragment of code: https://codesandbox.io/s/19rn7v91j

Clicking through first seven slides work perfectly fine, the problem start where wrapAround takes places and slide is back to number 1. All slides except last one has unworking onClick events (I guess they were unbound somehow?). Very similar effect is when you try to go left with this difference, that there the last one slide isn't working and rest (in my case six of them) are working perfectly fine.
Also as I checked that's problem with onClick event, as OnMouseEnter and onMouseLeave works no matter what.

**Comment by koellcode** [comment]
we have the same issue here. 

thank you @michalg42 for that very clear codesandbox example 👍

**Comment by ryan-roemer** [comment]
@michalg42 -- Thanks for the example. Would you be able to open a WIP PR with just a failing regression test in https://github.com/FormidableLabs/nuka-carousel/blob/master/test/specs/carousel.test.js against this repo? Thanks!

**Comment by michalg42** [comment]
I tried to create test for this case, but I have "TypeError: event.nativeEvent.stopPropagation is not a function" when I try to run my test and I'm not exactly sure what causes it...
Here is my test code: https://github.com/michalg42/nuka-carousel/blob/fix/wrapAroundLoseOnClick/test/specs/carousel.test.js#L601

**Comment by wimbush** [comment]
Confirmed I have this issue.
