### ISSUE TITLE
Remove d3-ease

### ISSUE THREAD

**Issue by mschipperheyn** [FormidableLabs/nuka-carousel#363]
I was reviewing the my bundle size and I noticed that Nuka is fairly large. It also imports an old package called d3-ease which is also large. My suggestion would be to remove d3-ease and use React Transition Group or straight css animations. It would be much kinder on bundle size.

**Comment by CharlyJazz** [comment]
I am very agree with this that proposal. @kenwheeler Please...

**Comment by taisuke-j** [comment]
Maybe we can consider the size of `react-move` as well

<img width="563" alt="nuka_src" src="https://user-images.githubusercontent.com/7695790/46841185-5881f080-ce01-11e8-9ede-84475b2f5377.png">

**Comment by gauthierm** [comment]
Animations like elastic and bounce are not possible with pure css transitions.

**Comment by sghall** [comment]
Author of react-move here.  Yeah, you could drop the size of this bundle dramatically.  React-move depends on d3-interpolate which depends on d3-color.  It's a lot of code if you're only interpolating numbers. 

Looks like you're only using it here:
https://github.com/FormidableLabs/nuka-carousel/blob/cc26ac9fcf6a2073b7a9f5ed03e4065cf9f41264/src/index.js#L899

React-move can interpolate numbers, paths, SVG transforms but you don't need all that code (if I understand correctly).  I'm actually moving the code that does transitions out of react-move to make a hooks library.  I could put a local `Animate` component in this repo that would drop 5 or 6 kbs (gzipped) out of the bundle pretty easily. 

On d3-ease, yes, have the user pass in an easing function.  You could export the d3-ease functions from this library for convenience but allow them to bundle just the one they use.

**Comment by sghall** [comment]
@taisuke-j well, there's two pieces.  I'm going to abstract out the piece that runs the transitions.  That is not react specific.  That library will power react-move and a new react hooks library.

**Comment by sghall** [comment]
I just made a PR for react-move 5.0 (https://github.com/FormidableLabs/nuka-carousel/pull/496) . We removed the hard dependency on d3-interpolate.  React-move is much smaller now. It's the same size as react-transition-group.   This should reduce the bundle size quite a bit.
