### ISSUE TITLE
Children with falsy values are rendered as an empty slide

### ISSUE THREAD

**Issue by andreidobrinski** [FormidableLabs/nuka-carousel#370]
Steps
- Create a carousel with conditional rendering
- Set the values to be falsy
- Run

Expectation
- A carousel slide would not be rendered for the falsy value

What happens
- An empty slide is presented

Example
```
<Carousel>
  <Component />
  {boolean && <AnotherComponent />}
</Carousel>
```

**Comment by sarmeyer** [comment]
@andreidobrinski our team was unable to reproduce this issue. When the condition was false (`undefined, null, false`), the slide component was not rendered. If you have a minimal repository or a CodeSandbox so we can jump and see what you see, we can continue to investigate. Thanks!
