### ISSUE TITLE
Carousel component is doing nothing with the decorators attribute

### ISSUE THREAD

**Issue by YamesSays** [FormidableLabs/nuka-carousel#374]
I am trying to do some custom arrows for my slider component by using the decorators attribute and it does not seem to even recognize it.  I downloaded the demo and added decorators={[]} to the Carousel component just to see if it was my app but it is still doing nothing.  decorators={[]} is supposed to hide the prev/next buttons and the dots but it is not doing this.  I am not seeing any console errors and I am seeing the decorators in React dev tools.

Please let me know what I need to do.  I would be very grateful!  I looked through the documentation and also some of the open/closed issues.  I also tried `npm install babel-plugin-transform-decorators-legacy` after finding [this page on decorators in React](https://medium.com/@jihdeh/es7-decorators-in-reactjs-22f701a678cd)

Like I said, I am using the Demo but here a snippet of my code anyways:

```
<Carousel
          decorators={[]}
          cellAlign={this.state.cellAlign}
          slidesToShow={this.state.slidesToShow}
          wrapAround={this.state.wrapAround}
          slideIndex={this.state.slideIndex}
          renderTopCenterControls={({ currentSlide }) => (
            <div
              style={{
                fontFamily: 'Helvetica',
                color: '#fff',
                textDecoration: this.state.underlineHeader
                  ? 'underline'
                  : 'none'
              }}
            >
              Nuka Carousel: Slide {currentSlide + 1}
            </div>
          )}
        >
...
</Carousel>

```

**Comment by tol-is** [comment]
The decorators array prop has been deprecated, not sure which release. Now the controls are passed as individual props for each position.

renderTopLeftControls
renderTopCenterControls
renderTopRightControls
renderCenterLeftControls
renderCenterCenterControls
renderCenterRightControls
renderBottomLeftControls
renderBottomCenterControls
renderBottomRightControls

**Comment by YamesSays** [comment]
decorators property is deprecated use renderCenterLeftControl and renderCenterRightControls
