### ISSUE TITLE
When dynamically adding new slides, slideIndex cannot be simultaneously set beyond original slideCount.

### ISSUE THREAD

**Issue by mariano-formidable** [FormidableLabs/nuka-carousel#377]
**Repro Steps**
1. Create 3 slide carousel.
2. Add button outside carousel to do the following `onClick`:
   *  Add 3 additional slides to carousel
   *  Set `slideIndex` prop to `4` (which is an index beyond the original 3 slides)

**Current Results**
- Carousel slides increase by 3.
- Carousel does *not* navigate to slide with index of `4`.

**Expected Results**
- Carousel slides increase by 3.
- Carousel *does* navigate to slide with index of `4`.

This issue was created based off PR #166 which was too old to merge.

**Comment by sarmeyer** [comment]
fix in PR #392
