### ISSUE TITLE
When dragging to change slides, a click event is triggered against the slide.

### ISSUE THREAD

**Issue by mariano-formidable** [FormidableLabs/nuka-carousel#381]
**Repro Steps**

1. Navigate to Nuka demo app.
2. Observe that "Nuka Carousel: Slide 1" is *not* underlined.
3. Use your mouse to drag `slide 1` to `slide 2`.

**Current Results**
- Carousel transitions to `slide 2`.
- An onclick event is trigger and "Nuka Carousel: Slide 2" becomes underlined.

**Expected Results**
- Carousel transitions to `slide 2`.
- "Nuka Carousel: Slide 2" remains *not* underlined.

**Note:**
If you use chrome dev tools to simulate touch interacts, you can successfully drag between slides *without* triggering click events.  The unexpected clicks only occur when using mouse drag events.

This issue is based off PR #220 which is too old to merge.

**Comment by sarmeyer** [comment]
Fix in #220 prevents click event from triggering when dragging slides
