### ISSUE TITLE
is there a way to change the position of the carousel dots?

### ISSUE THREAD

**Issue by petervijeh** [FormidableLabs/nuka-carousel#382]
?

**Comment by kumarvish** [comment]
`
export class PagingDots extends React.Component {
  getIndexes(count, inc) {
    const arr = [];
    for (let i = 0; i < count; i += inc) {
      arr.push(i);
    }
    return arr;
  }

  getListStyles() {
    return {
      position: 'relative',
      margin: 0,
      top: 50,
      padding: 0,
    };
  }

  getListItemStyles() {
    return {
      listStyleType: 'none',
      display: 'inline-block',
    };
  }

  getButtonStyles(active) {
    return {
      border: 0,
      background: 'transparent',
      color: 'black',
      cursor: 'pointer',
      padding: 10,
      outline: 0,
      fontSize: 24,
      opacity: active ? 1 : 0.5,
    };
  }

  render() {
    const indexes = this.getIndexes(
      this.props.slideCount,
      this.props.slidesToScroll,
    );
    return (
      <ul style={this.getListStyles()}>
        {indexes.map(index => {
          return (
            <li style={this.getListItemStyles()} key={index}>
              <button
                style={this.getButtonStyles(this.props.currentSlide === index)}
                onClick={this.props.goToSlide.bind(null, index)}
              >
                &bull;
              </button>
            </li>
          );
        })}
      </ul>
    );
  }
}

<Carousel renderBottomCenterControls={props => <PagingDots {...props} />}>>

`

Try this, you need to override renderBottomCenterControls and have a custom implementation, i have just modified top position in PagingDots control

**Comment by joelosx** [comment]
I am struggling with this same issue. Are you recommending a custom implementation that replaces PagingDots?

**Comment by sobchenyuk** [comment]
`import React from 'react';
import PropTypes from 'prop-types';

const styles = {
listStyles: {
position: 'relative',
margin: 0,
top: 50,
padding: 0,
},
listItemStyles: {
listStyleType: 'none',
display: 'inline-block',
},
buttonStyles: {
backgroundColor: '#2ecc71',
width: 11,
height: 11,
display: 'block',
padding: 0,
margin: 10,
borderRadius: '50%',
fontSize: 0,
border: 0,
cursor: 'pointer',
},
};

const PagingDots = (props) => (

{PagingDots.getIndexes(props.slideCount, props.slidesToScroll).map(index => { return (
•
); })}
);
PagingDots.getIndexes = (count, inc) => {
const arr = [];
for (let i = 0; i < count; i += inc) {
arr.push(i);
}
return arr;
};

PagingDots.propTypes = {
slideCount: PropTypes.number,
slidesToScroll: PropTypes.number,
goToSlide: PropTypes.func,
currentSlide: PropTypes.number,
};

export default PagingDots;`

**Comment by sobchenyuk** [comment]
import React from 'react';
import PropTypes from 'prop-types';

const styles = {
  listStyles: {
    position: 'relative',
    margin: 0,
    top: 50,
    padding: 0,
  },
  listItemStyles: {
    listStyleType: 'none',
    display: 'inline-block',
  },
  buttonStyles: {
    backgroundColor: '#2ecc71',
    width: 11,
    height: 11,
    display: 'block',
    padding: 0,
    margin: 10,
    borderRadius: '50%',
    fontSize: 0,
    border: 0,
    cursor: 'pointer',
  },
};

const PagingDots = (props) => (
  <ul style={{...styles.listStyles}}>
    {PagingDots.getIndexes(props.slideCount, props.slidesToScroll).map(index => {
      return (
        <li style={{...styles.listItemStyles}} key={index}>
          <button
            style={{...styles.buttonStyles, opacity: props.currentSlide === index ? 1 : 0.5}}
            onClick={props.goToSlide.bind(null, index)}
          >
            &bull;
          </button>
        </li>
      );
    })}
  </ul>
);

PagingDots.getIndexes = (count, inc) => {
  const arr = [];
  for (let i = 0; i < count; i += inc) {
    arr.push(i);
  }
  return arr;
};

PagingDots.propTypes = {
  slideCount: PropTypes.number,
  slidesToScroll: PropTypes.number,
  goToSlide: PropTypes.func,
  currentSlide: PropTypes.number,
};

export default PagingDots;

**Comment by ashika01** [comment]
Using `render*Controls` prop, you should be able to render your custom paging dots or any other elements at 9 different positions.

**Comment by YLemelin09** [comment]
Why not just expose the classes of the different elements as props so we can override their styles? Example: 
`<Carousel
     bottomControls: ("some jsx element to change de icon style", {{container: style.container, dot: style.dot}})
     previousControl:  ("some jsx element to change de icon style", {{container: style.container, previous: style.previousArrow}})
>
    {this.props.children}
</Carousel>
`
