### ISSUE TITLE
Responsive Example

### ISSUE THREAD

**Issue by cadday** [FormidableLabs/nuka-carousel#388]
Would someone please provide a responsive example. I like to define slidesToShow properties for different breakpoints. 
Thanks

**Comment by cadday** [comment]
Anyone? 
Is it even possible to change totalSlides based on window width?

**Comment by richardscarrott** [comment]
@cadday I wondered the same -- but I was hoping it would compute the `slidesToScroll` based on the size of the container / viewport. That way you wouldn't have to define explicit `slidesToScroll` at specific breakpoints allowing the carousel to scale based on a percentage width.

It would require reading the item width from the DOM before being able to compute the page count -- or at least accepting the width of an item as a prop but it'd offer a lot of flexibility.

I remember implementing a carousel like this here https://github.com/richardscarrott/jquery-ui-carousel many years ago (try resizing the window).

**Comment by cadday** [comment]
@richardscarrott thanks for your answer. I think the idea of computing slide count automatically sounds good by i don't think it is practical.

It is not just the screen width that changes when switched from a desktop size to mobil size. Orientation change should also be considered. 

For example, user might want to hide detail text on smaller screens and this can cause a necessity to show more items on smaller screen than large ones. Or lets say carousel items are structred as image on left text on right. On smaller screens user might want to change the structure and shows image up text bottom. This scenario also causes a necessity showing more or same number of items on smaller screens.

**Comment by AllanPooley** [comment]
Hi @cadday, anyone else looking for an example.

This is how I got it done:

```
const isClient = typeof window !== 'undefined';

class NukaCarouselSlider extends Component {
  state = {
    viewportWidth: 0,
  };

  componentDidMount() {
    if (isClient) {
      window.addEventListener('resize', this.updateWindowDimensions);
      setTimeout(() => {
        this.updateWindowDimensions();
      }, 500);
    }
  }

  componentWillUnmount() {
    if (isClient) window.removeEventListener('resize', this.updateWindowDimensions);
  }

  updateWindowDimensions = () => {
    this.setState({ viewportWidth: window.innerWidth });
  }

  render() {
    const {
      viewportWidth,
    } = this.state;
    const {
      gallery,
    } = this.props;
    const isMobile = Boolean(viewportWidth <= 800);
    return (
      <section className="nuka-carousel">
        <div className="slides">
          <Carousel
            ref={(carousel) => { this.carousel = carousel; }}
            wrapAround
            cellAlign="center"
            cellSpacing={!isMobile ? 30 : 15}
            slideWidth={!isMobile ? 0.8 : 0.85}
            withoutControls
          >
            {gallery.map((item, index) => <Slide />}
          </Carousel>
        </div>
      </section>
    );
  }
}

export default NukaCarouselSlider;
```

**Comment by PogosyanArtur** [comment]
Hi cadday I use material ui, but it dos't meter the logic is same.

import React from 'react'
import { makeStyles, useTheme } from '@material-ui/styles'
import { Card, CardMedia, CardContent, Typography } from '@material-ui/core'
import { unstable_useMediaQuery as useMediaQuery } from '@material-ui/core/useMediaQuery'
import Carousel from 'nuka-carousel';
import { sideImagesData } from '../../data'
import Wrapper from '../Wrapper'

const useStyles = makeStyles(theme => ({
    GalleryContainer: {
        backgroundColor: theme.palette.primary.main,
        paddingTop: theme.spacing.unit * 9,
        paddingBottom: theme.spacing.unit * 10,
    },
    Card: {
        minWidth: '300px',
    },
    CardMedia: {
        height: '250px'
    },
    CardTitle: {
        color: theme.palette.info.main
    }
}))

export default () => {
    const classes = useStyles()
    const theme = useTheme();
    const mdUp = useMediaQuery(theme.breakpoints.up('md'))
    const xlUp = useMediaQuery(theme.breakpoints.up('xl'))

    let SlideToShowNumber = 1;
    if(mdUp){
        SlideToShowNumber = 2;
    }
    if(xlUp){
        SlideToShowNumber = 3;
    }

    return (
        <section className={ classes.GalleryContainer }>
            <Wrapper>
                <Carousel slidesToShow={SlideToShowNumber} swiping withoutControls cellAlign="left" cellSpacing={20}>
                    {
                        sideImagesData.map((item, index) => (
                            <Card key={ item } className={ classes.Card } elevation={ 0 }>
                                <CardMedia className={ classes.CardMedia } image={ `${ require(`../../static/images/${ item }.jpg`) }` } />
                                <CardContent>
                                    <Typography variant="h6" className={ classes.CardTitle }>Трактор при исполнение </Typography>
                                </CardContent>
                            </Card>
                        ))
                    }
                </Carousel>
            </Wrapper>
        </section>
    )
}

**Comment by PogosyanArtur** [comment]
The mane idea is here 
let SlideToShowNumber = 1;
if(mdUp){
    SlideToShowNumber = 2;
}
if(xlUp){
    SlideToShowNumber = 3;
}

            <Carousel slidesToShow={SlideToShowNumber}>
             /* your slides*/
            </Carousel>

**Comment by sarmeyer** [comment]
I don't believe this is something we'll be adding to the lib as it seems there are a few ways to achieve it otherwise. if there is strong desire for something like this to be added, we can reconsider, but for the sake of complexity I'll leave it out for now. Thanks!

**Comment by captainkovalsky** [comment]
I think that changing `slidesToShow` for mobile devices is not fixing the issue, just hiding

**Comment by barbgegrasse** [comment]
If there is no props for it "for the sake of complexity" it would be lovely to get a nice example in the documentation  on how to implement it.
Thank you for everything

**Comment by ziserman** [comment]
Unfortunately, all of this examples can't work with server-side rendering :(
