### ISSUE TITLE
Carousel does't work in firefox.

### ISSUE THREAD

**Issue by weslei-dias** [FormidableLabs/nuka-carousel#389]
The carousel work perfect in Chrome, but in firefox version > 53 doesn't work.

**Comment by Klaasvaak** [comment]
I have one running in production and seems to work in Firefox 61.0.1 The demo http://kenwheeler.github.io/nuka-carousel/#/ also seems to work on Firefox.

**Comment by roshanDaruka** [comment]
unable to slide on firefox mobile.
