### ISSUE TITLE
transitionMode TypeScript

### ISSUE THREAD

**Issue by davidgtu** [FormidableLabs/nuka-carousel#395]
I'm using This carousel like so:

```js
<NukaCarousel transitionMode="fade">
```

but Typescript is complaining: 

```ts 
Property 'transitionMode' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Carousel> & Readonly<{ children?: ReactNode; }> & ...'.
```

I'm new to typescript and i'm not too sure on how to resolve this? adding `any` to my component didn't seem to work neither.

**Comment by ashika01** [comment]
@davidgtu : any update on this? could you give us sample in code Sandbox so we can reproduce and help resolve the issue.

**Comment by altaudio** [comment]
You need to install types for `nuka-carousel` eg. `npm install --save-dev @types/nuka-carousel`

However the types file does not currently include the prop `transitionMode`

As a short term solution, you can grab the file `node_modules/@types/nuka-carousel/index.d.ts`  and modify it to include the prop.

As a helpful programmer you could create a PR for [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) adding your modification to the `index.d.ts` file to fix this for the good of the JS community!

I had the same issue with `withoutControls`
