### ISSUE TITLE
state.frameWidth becomes out of sync with dom on resize

### ISSUE THREAD

**Issue by jdeagle** [FormidableLabs/nuka-carousel#402]
Using version 4.3.5

I have a break point that changes the size of children in the carousel. Once the resize event is triggered (lets say width), several rerenders occur due to `setState` changes in `setDimensions` and `setLeft`. However, `frameWidth` is never recalculated after these updates so the position offset from `getTargetLeft` is incorrect (because of its dependency on `frameWidth`). Triggering an additional resize event (say height change) causes `frameWidth` to be updated via `setDimensions` but there doesn't seem to be a way to detect and trigger a fix from outside the component. 

Locally I added `componentDidUpdate` to check `state.frameWidth` against `frame.offsetWidth` or `props.width` and call `setDimensions` if they don't match. Either seem to work but I am unsure of how that will affect other use cases.

```
componentDidUpdate(prevProps, prevState) {
    if(this.state.frameWidth !== this.frame.offsetWidth) {
      console.warn('frame width is off, run setDimensions', this.state.frameWidth, this.frame.offsetWidth);
      this.setDimensions();
    }
    // OR
    if(this.state.frameWidth !== parseInt(this.props.width, 10)) {
      console.warn(`frame width is off from props.width, run setDimensions ${this.state.frameWidth} ${parseInt(this.props.width, 10)}`);
      this.setDimensions();
    }
  }
```

There might be other/better places to handle updating `frameWidth`...

**Comment by ashika01** [comment]
Fixed in #408.
