### ISSUE TITLE
Input Elements not focusing

### ISSUE THREAD

**Issue by carloquilala** [FormidableLabs/nuka-carousel#406]
see this sandbox https://codesandbox.io/s/4qomvjlqy9

can't focus on input element

**Comment by ashika01** [comment]
@carloquilala : Try overriding the default by using event handlers. it should work. I just reproduced your issue and handle the event and it works. For example, open our demo app in the repo and you should be able to figure out.

**Comment by carloquilala** [comment]
i've already set a window event outside nuka carousel

added an onclick window event in the element targetting the id

**Comment by ashika01** [comment]
@carloquilala : That is the exact same way I used to focus on the input element. If you have any interesting ideas to include this, make a PR with our template. We can review and shall introduce it.

**Comment by sylviestephanies** [comment]
can you give example?

**Comment by gstaykov** [comment]
`
onClick = () => {
        document.getElementById("email").focus();
}

...
<Carousel>
                        <div>
                            <input id="email"  onClick={this.onClick} />
                        </div>
</Carousel>
`

**Comment by yungkittty** [comment]
This is probably a more convenient workaround depending on your needs :

```javascript
const Component = () => {
  return (
    <Carousel>
      <div onClick={(event) => {
        event.preventDefault();
      }}>
        <input />
      </div>
    </Carousel>
  )
}
```

**Comment by Galzk** [comment]
```const handleClick = ({target}) => {
    target.focus()
    e.stopPropagation();
    e.preventDefault();
  };```
I got this far, but I have to drop this approach as there are a few downsides such as:
- Cannot select text
- No exact cursor positioning, it's always focusing at the end
- Other functionality is broken, such as <input type="number"> arrows are not working

**Comment by Galzk** [comment]
Ok after some time I've found a somewhat "elegant" solution
I don't completely like it as it's a bit complicated in terms of flow but anyway, here we go:
```js
      <Carousel>
        <Slide>
          <div id='portal-target'/>
        <Slide>
      <Carousel>
```

Then **outside** of the <Carousel> component render the <input> / <modal> or any other interactive component, and portal it in:
```js
import React from 'react';
import { createPortal } from 'react-dom';

const DataInput = ({ portalTo }) => {
  const domEl = document.querySelector(portalTo);
  if (!domEl) return null;

  return createPortal(<Input />, domEl);
};
```

So, end result should look something like:
```js
    <>
      <Carousel>
        <Slide>
          <div id='portal-target'/>
        <Slide>
      <Carousel>
      <DataInput portalTo='#portal-target'>
    </>
```

**Comment by DGafetdinov** [comment]
why is the issue closed? the problem is still being reproduced!

**Comment by Galzk** [comment]
> Hey guys, I've found possible solution which is working for me very well. And it's pretty simple :) 
> 
> You just need to stop propagation of click event and right after that focus the element programatically.
> 
> Like this:
> 
> ```js
> <Carousel>
>   <Slide>
>     <input
>       type='text'
>       placeholder="You can't focus on me"
>       onClick={e => {
>         e.stopPropagation();
>         e.currentTarget.focus();
>       }}
>     />
>   </Slide>
> </Carousel>
> ```
> 
> I've also edited Original code with this solution:
>  https://codesandbox.io/s/inspiring-yalow-mp9zy
> 
> I hope this helps ! ☺️ 
> 
> 

I think the issue I faced was that I was not able to select text or click a certain position specifically

If you have the same issue, try my method as it works as expected :)

**Comment by fritz-c** [comment]
This appears to be working in v5.2.0
demo: https://codesandbox.io/s/silly-roentgen-mylgix
