### ISSUE TITLE
Infinite slider wrapAround is not working

### ISSUE THREAD

**Issue by wimbush** [FormidableLabs/nuka-carousel#410]
By default, the infinite scrolling breaks after reaching the end of the first time. 

I'm using the slider in a Gatsby instance. Happy to provide more details if I can help.

**Comment by joshiefishbein** [comment]
My implementation (using v4.3.10) is still blinking on the dynamic last-to-first slide transition. I see PRs fixing this but this is not reflected in my install. Any thoughts on this? Thanks!

**Comment by ethanryan** [comment]
In Chrome, I'm seeing the active slide blink or flick when the Carousel is set to infinite scroll as well, via wrapAround={true}. 

This is happening when clicking previous to go from the first to last slide, or when clicking next to go from the last to first slide.
