### ISSUE TITLE
Video inside carousel

### ISSUE THREAD

**Issue by sudhiryadav** [FormidableLabs/nuka-carousel#414]
I have a situation. In the carousel i have vides to be played in each slide. The slider works well with draggable scrollable using swipes but the problem is that when i want to drag the slider of the video  player (which is at the bottom of video) then the entire slide slides. How could i avoid this behaviour of carousel.

**Comment by ashika01** [comment]
@sudhiryadav : on what context are you using this? Could you provide us with more details? embedded videos works fine in nuka and I was able to drag and slide an embedded video.

Just in case if have you haven't tried these: 

- try disabling `dragging` and `swiping` and setting `renderBottomCenterControls` to null
- if render controls is distrubing, try `withoutControls`

**Comment by ashika01** [comment]
@sudhiryadav : you can always customize and have your own usage of render controls. My best bet for your use case, would be to use embed video code. This way i think you should be able to achieve your result.
