### ISSUE TITLE
Where is the changelog?

### ISSUE THREAD

**Issue by stunaz** [FormidableLabs/nuka-carousel#418]
Hi, Sorry, looked everywhere, but I could not find the change log? Do I need to read the commits?

**Comment by ermik** [comment]
@sarmeyer you seem to be putting a lot into this repo and I am loving every bit of it, but perhaps we could have some sort of notes, even if they are just made out of commit messages.

**Comment by boygirl** [comment]
@sarmeyer @ashika01 If you're looking for a template to follow, this might help:
https://github.com/FormidableLabs/victory/releases

or if you prefer `CHANGELOG.md` style notes:
https://github.com/FormidableLabs/victory/blob/master/CHANGELOG.md

**Comment by sarmeyer** [comment]
@stunaz added a changelog, will be updating retroactively over the next few days

**Comment by stunaz** [comment]
I did not
