### ISSUE TITLE
Add Online demo

### ISSUE THREAD

**Issue by balazsorban44** [FormidableLabs/nuka-carousel#420]
# Bugs and Questions

### Describe Your Environment
- What version of nuka-carousel are you using? latest
- What version of React are you using? latest
- What browser are you using? Any
- What machine are you on? Any

### Describe the Problem
**Expected behavior:**
There should be an online demo

**Actual behavior:** 

There is none

### Additional Information
It should be relatively easy to add a basic example:
https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/

To go a little bit further, consider something like https://github.com/storybooks/storybook

**Comment by cardiv** [comment]
How about [that](http://kenwheeler.github.io/nuka-carousel/#/)? Should be linked, if kinda _official_.

**Comment by balazsorban44** [comment]
@cardiv It is not linked anywhere in the README, probably with a reason, it looks like the previous maintainer's work.

@ashika01 Don't really understand what you mean, I know what a demo is? If you talk about the localhost one, I get it, but it would be more convenient to have an online demo since most people who are just discovering this package won't bother downloading it first. There are so many free static site hosts now, or even Github Pages as I mentioned. So that should be no problem. 

Maybe, if I will have some free time, I'll make a PR myself then.

**Comment by balazsorban44** [comment]
I mean the only thing you would need to do, is to rename the demo folder to docs for starters. Then you would need to enable Github Pages in the settings and it's done. Check out https://pages.github.com
(Remember to add the new demo link to the README.md)

I understand if you don't want to use too much time if you plan to create a consistent documentation in the future, but making the current demo available online is little effort with a positive effect.

**Comment by sarmeyer** [comment]
@balazsorban44 An online demo is now available in the Readme - https://codesandbox.io/s/mjxwl64p2y
