### ISSUE TITLE
 When wrapAround pictures do not have time to load.

### ISSUE THREAD

**Issue by maystrenkoYurii** [FormidableLabs/nuka-carousel#424]
# Bugs and Questions

### Prerequisites

**Feel free to delete this section if you have checked off all of the following.**

- [ ] I've searched open [issues](https://github.com/FormidableLabs/nuka-carousel/issues) to make sure I'm not opening a duplicate issue
- [ ] I have read through the docs before asking a question
- [ ] I am using the latest version of nuka-carousel

### Describe Your Environment

- What version of nuka-carousel are you using?
- What version of React are you using?
- What browser are you using?
- What machine are you on?

### Describe the Problem

It's easier to show us than tell us what's going wrong with your code. Because of this, we ask that you do one of three things to help us reproduce the bug:

1. Create a public minimal repository that we can `git clone`, with install + error reproduction steps in the README.
2. Create a sandbox, reproduce your issue in the code, and paste the link here.
3. Open up a PR, include "WIP" and the Issue # in the title, and point us to the failing regression tests.

**Expected behavior:** [What you expect to happen]
**Actual behavior:** [What actually happens]

### Additional Information
Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by sarmeyer** [comment]
@maystrenkoYurii would you mind filling out the issue template to tell us what issue you're seeing?
