### ISSUE TITLE
How to jump to a specific index instantly?

### ISSUE THREAD

**Issue by DualWield** [FormidableLabs/nuka-carousel#426]
# Bugs and Questions

### Prerequisites

**Feel free to delete this section if you have checked off all of the following.**

- [x] I've searched open [issues](https://github.com/FormidableLabs/nuka-carousel/issues) to make sure I'm not opening a duplicate issue
- [x] I have read through the docs before asking a question
- [x] I am using the latest version of nuka-carousel

### Describe Your Environment

- What version of nuka-carousel are you using?
4.4.1
- What version of React are you using?
16.2
- What browser are you using?
chrome
- What machine are you on?
mac

### Describe the Problem
How to jump to a slide instantly?
For examples, Every time I open a dialog, there is a slider in dialog. I want the slide index different.But I don't want user see the transition. I want to jump to a specific index when I open the dialog.

**Expected behavior:** []
**Actual behavior:** []

**Comment by DualWield** [comment]
for examples, https://codesandbox.io/s/7y6z4my4yj . I don't want to see the transition

**Comment by ashika01** [comment]
Setting your `speed` prop to 0 and `SlideIndex` to your desired slide number should achieve this. Hope this helps. If this is what your looking for, please close this issue.

**Comment by DualWield** [comment]
@ashika01 Thanks.
I have known this solution. But it looks like a trick. What I really want is goToSlideInstantly or initialSlideIndex.
