### ISSUE TITLE
It's possible to move my buttons/dots to other container?

### ISSUE THREAD

**Issue by pedropcruz** [FormidableLabs/nuka-carousel#428]
FEATURE

Basically i have this at my code:

```javascript
import React, { Component } from 'react';
import Carousel from 'nuka-carousel';
import SliderStyles from './slider.css';

export default class Slider extends Component {
  state = {
	sliderIndex: 0
  }
  render(){
    return(
     <SliderStyles>
	<Carousel 
	sliderIndex={this.state.sliderIndex} 
	afterSlide={sliderIndex => this.setState({sliderIndex})}
	wrapAround={true}
	renderCenterLeftControls={({ previousSlide }) => (
		<button onClick={previousSlide}><i className="icon-018-left-arrow"></i></button>
	)}
	renderCenterRightControls={({ nextSlide }) => (
		<button onClick={nextSlide}><i className="icon-019-right-arrow"></i></button>
	)}>
		<img src="https://source.unsplash.com/1600x900/?nature,water" alt="img1" />
	        <img src="https://source.unsplash.com/1600x900/?house" alt="img2" />
		<img src="https://source.unsplash.com/1600x900/?love" alt="img3" />
		<img src="https://source.unsplash.com/1600x900/?code" alt="img4" />
		<img src="https://source.unsplash.com/1600x900/?apartment" alt="img5" />
	</Carousel>
	<div className="container">
	   <h1>{this.state.sliderIndex + 1}</h1>
	    {/* Here i want my buttons/dots. It's Possible? */}
	</div>
      </SliderStyles>
    )
  }
}
```
What to change the container of buttons/dots for css purposes. It's possible?

- What version of nuka-carousel are you using? 4.4.1
- What version of React are you using? I'm using 16.2
- What browser are you using? Chrome
- What machine are you on? MacbookPro 15'' 2015

**Comment by ashika01** [comment]
@pedropcruz : have you tried using `withoutControls` for rendering with no controls and place you custom

**Comment by ashika01** [comment]
You can see the controls implementation from our code.  Basically how I would go about here would be, create the controls and navigate between different slide using `SlideIndex`. See the demo app in the `app.js` where you will find our implementation of having navigation through buttons outside slides.

**Comment by vilkazz** [comment]
my (probably very hacky) solution to this was to override dots absolute positioning with 
`.slider-control-bottomcenter {
    position: relative !important;
}
`
then pass custom component to renderBottomCenterControls and then control the dots positioning with the container element in the custom component. 

If I do it that way, the buttons/dots are interacting with the holder container thus achieving the needed result.

**Comment by sarmeyer** [comment]
Sounds like this one has been solved? if not, please reopen!
