### ISSUE TITLE
Feature request: Add support of slick slide change events and lazy loading images

### ISSUE THREAD

**Issue by niki4810** [FormidableLabs/nuka-carousel#43]
@kenwheeler  as per our discussion, creating this ticket for adding support for 
- carousel events like on slide change, before slide change. 
- `data-lazy` functionality for lazy loading images with in slick carousel

Thanks,
Nikhilesh

**Comment by jherr** [comment]
:+1:

**Comment by aij** [comment]
I have a slightly different use case for lazy loading: We're rendering thousands of slides and -- for performance -- would like to avoid even creating DOM elements for all the slides that will not be visible anyway.

Currently, we're using react-slick but it is sluggish and the lazyLoad option is iffy...
