### ISSUE TITLE
Dragging only scroll one item

### ISSUE THREAD

**Issue by borisyordanov** [FormidableLabs/nuka-carousel#437]
### Describe Your Environment

- What version of nuka-carousel are you using?
4.4.2

- What version of React are you using?
16.5.2

- What browser are you using?
Chrome
- What machine are you on?
Windows 10

### Describe the Problem
When I drag to scroll through images, no matter how much i drag, the carousel transitions to the next item, and not to the point i dragged to. You can test that here - [Sandbox](https://codesandbox.io/s/j43jzy1pp5).

Is there an option to disable this behavior? I want it to work like the [slick carousel](http://kenwheeler.github.io/slick/).

**Comment by sarmeyer** [comment]
I see - this is when you have more than one slide showing at a time. We'll investigate this and get back to you!

**Comment by borisyordanov** [comment]
@sarmeyer I figured it out. You need to set the slidesToShow AND slidesToScroll. I had omitted the second one which is what was causing the issues.

Example:
`<Carousel slidesToShow={5} slidesToScroll={5}>{items}</Carousel>`

**Comment by sarmeyer** [comment]
@borisyordanov I see you reopened this issue. Are you experiencing the same issue even after adding the slidesToScroll prop?

**Comment by borisyordanov** [comment]
@sarmeyer 
I reopened it, but forgot to write why!

I realise this is how the original slick carousel work, but i'd argue it's a bad user experience. If i'm looking at a multiple item carousel and drag it a little bit, i expect it to scroll only the amount i dragged, not whatever was specified in slidesToShow.

I guess this is more of a feature request than a bug report at this point.

**Comment by pleopardi** [comment]
Any update regarding this issue?

I'm trying to achieve the same result but with no success so far.

I  agree with @borisyordanov  about the expected behaviour: different scroll amounts should reflect on different item selections, not always select the previous or next item.

**Comment by Finesse** [comment]
I face this issue too.

> @sarmeyer I figured it out. You need to set the slidesToShow AND slidesToScroll. I had omitted the second one which is what was causing the issues.
> 
> Example:
> `<Carousel slidesToShow={5} slidesToScroll={5}>{items}</Carousel>`
> or
> `<Carousel slidesToShow={5} slidesToScroll="auto">{items}</Carousel>`

This is not a good solution because you still can scroll only a fixed amount of slides (5 in your case). You can't scroll only 1 slide by swiping a bit.

You can use [Swiper](https://github.com/kidjp85/react-id-swiper) to achieve the desired effect.

**Comment by samhadr** [comment]
Upvote - this feature has been requested by several of my clients.

**Comment by Karyum** [comment]
is there an update on the matter ? this feature would be really helpful

**Comment by arkadiuszizycki** [comment]
Any progress on that?

**Comment by brybrophy** [comment]
@sarmeyer We should be able to dynamically increment/decrement the `slidesToScroll` prop as users drag through the carousel. Maybe we could allow devs to set `slidesToScroll="auto"` to enable this functionality.
