### ISSUE TITLE
Swiping/dragging and `wrapAround`

### ISSUE THREAD

**Issue by alvinsight** [FormidableLabs/nuka-carousel#438]
Hi Nuka team, thanks for your work on this project!

### Describe Your Environment

- What version of nuka-carousel are you using? `4.4.2`
- What version of React are you using? `16.4.1`
- What browser are you using? `Chrome`
- What machine are you on? `OSX Sierra`

### Describe the Problem

When `wrapAround` is set to true and you swipe or drag to the left, the slide flickers.

It can be reproduced on your own CodeSandbox url : https://codesandbox.io/s/mjxwl64p2y

![nuka-wraparound-flicker](https://user-images.githubusercontent.com/4254030/47809901-ddde2e00-dd39-11e8-9be1-3b432df51f4e.gif)

**Expected behavior:** I can swipe or drag and the slides should move smoothly
**Actual behavior:** There is a noticeable flicker 

### Additional Information
As far as my testing goes, it only seems to happen when `wrapAround` is set

**Comment by funkeeflow** [comment]
I can reproduce this issue on my set up as well. When `wrapAround` is set to true, i'm experiencing flickering between slides.

Any news on this?

**Comment by alvinsight** [comment]
@funkeeflow I switched to `react-slick` and it went away, I recommend it, there's loads of documentation and examples too

**Comment by susheelachoudry** [comment]
I suppose the issue still happens when partial slides are used. Can be replicated by enabling `Toggle Wrap Around` and `Toggle Partial Visible Slides` in the code sandbox demo. I tried debugging, but not sure as to what's going wrong.
