### ISSUE TITLE
`display:grid` on any of the parent's style does not render the carousel properly.

### ISSUE THREAD

**Issue by nabinked** [FormidableLabs/nuka-carousel#440]
- [x] I've searched open [issues](https://github.com/FormidableLabs/nuka-carousel/issues) to make sure I'm not opening a duplicate issue
- [x] I have read through the docs before asking a question
- [x] I am using the latest version of nuka-carousel

### Describe Your Environment

- What version of nuka-carousel are you using?
4.4.2
- What version of React are you using?
16.6
- What browser are you using?
Chrome
- What machine are you on?
Windows WSL

### Describe the Problem
When the carousel is nested inside any parent or evens any parent's parent with style `display` set to `grid` the carousel does not render properly
Clone [this](https://github.com/nabinked/nuka-carousel-grid-bug) and `yarn start` to reproduce 

**Expected behavior:** Should render properly
**Actual behavior:** Does not

**Comment by ElreyB** [comment]
@nabinked The slides in the carousel have a width of 100% thus will grow to 100% of it’s parent element. Since the grid does not have any set dimensions it keeps growing to accommodate it. If you style the grid to not go past current dimensions for your uses case it will render properly for you. 

```
/* eslint-disable jsx-a11y/alt-text */
import React from 'react';
import Carousel from 'nuka-carousel';

export default class extends React.Component {
  render() {
    return (
      <main style={{ display: 'grid', gridTemplateColumns: 'minmax(0, 1fr)' }}>
        <div>
          <Carousel>
            <img src="http://placehold.it/1000x400/ffffff/c0392b/&text=slide1" />
            <img src="http://placehold.it/1000x400/ffffff/c0392b/&text=slide2" />
            <img src="http://placehold.it/1000x400/ffffff/c0392b/&text=slide3" />
            <img src="http://placehold.it/1000x400/ffffff/c0392b/&text=slide4" />
            <img src="http://placehold.it/1000x400/ffffff/c0392b/&text=slide5" />
            <img src="http://placehold.it/1000x400/ffffff/c0392b/&text=slide6" />
          </Carousel>
        </div>
      </main>
    );
  }
}
```

Hope this was helpful. Happy coding!!!

**Comment by sarmeyer** [comment]
@nabinked Did the above comment solve the issue for you?

**Comment by nabinked** [comment]
@sarmeyer Yes. Not the exact same solution but a similar one.
