### ISSUE TITLE
Disable keyboard shortcuts

### ISSUE THREAD

**Issue by ryanwalters** [FormidableLabs/nuka-carousel#443]
# Bugs and Questions

Is it possible to disable keyboard shortcuts? If not, I'd be happy to create a PR to add something like a `disableShortcuts` prop.

In our case, the carousel is part of a page that contains forms. When typing in the form, the carousel starts going crazy.

### Describe Your Environment

- What version of nuka-carousel are you using?
4.4.2
- What version of React are you using?
16.6.0
- What browser are you using?
Chrome 70
- What machine are you on?
Mac

**Comment by lndgalante** [comment]
Same issue here, hope a little gif helps

![keyboard-issue](https://user-images.githubusercontent.com/2475912/48105735-687dcc00-e217-11e8-8a51-506d80dfa001.gif)

**Comment by brense** [comment]
Using nuka-carousel version 4.4.9 this appears to still be an issue.
