### ISSUE TITLE
Scroll disabled with swiping === false

### ISSUE THREAD

**Issue by PeterKottas** [FormidableLabs/nuka-carousel#447]
### Describe Your Environment

- What version of nuka-carousel are you using?
4.4.2
- What version of React are you using?
16.6.1
- What browser are you using?
Chrome
- What machine are you on?
Windows

### Describe the Problem

https://codesandbox.io/s/mjxwl64p2y
Just add swiping={false} into carousel props
Then use chrome dev tools to simulate a mobile device (CTRL + SHIFT + M) 

**Expected behavior:** [What you expect to happen]
I expect the touch swiping to be disabled, and to be able to scroll the window while touching (vertically) on the slide.
**Actual behavior:** [What actually happens]
Swiping indeed is disabled, but sometimes (in codesandbox sometimes, in my code always for some reason) if you scroll using touch, when you start the scroll inside the slide, it will not scroll. Therefore if your slide is full-screen (like mine is), it can easily happen that you get stuck with no option of scrolling out of the slide.

### Additional Information
Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by PeterKottas** [comment]
For now, I've hacked around this using 

```
.slider-frame{
  pointer-events: none;
}
```

Which obviously is far from ideal.

**Comment by ScottSmith95** [comment]
I have seen this issue as well on mobile Chrome, although not on mobile Safari.

**Comment by mobcoder-kiran** [comment]
The below solution is good until you have radio button inside the slide.  with radio inside card will block radio selection.

.slider-frame{
  pointer-events: none;
}

**Comment by fritz-c** [comment]
This appears to be working normally in v5.2.0
