### ISSUE TITLE
Is there an easy way to hide/show left/right controls?

### ISSUE THREAD

**Issue by clayhan** [FormidableLabs/nuka-carousel#456]
I would like to create custom left/right controls and being able to hide the left when we're at the start of the carousel and hide the right when we're at the end of the carousel. Reading through the docs I was unable to tell if there's something that is able to tell me where the user is relative to carousel? Thanks a ton for your time!

**Comment by akhil-gautam** [comment]
Currently, there is no such way to do that but you can add css for those buttons. Make sure to scope the css with that specific component only in order to prevent other buttons getting screwed up.
`button{ display: none; }`

I will try to add the feature to pass a props for hiding those controll buttons not from css but preventing it getting it rendered. But that will be available in later releases. Till then, hack the css.

**Comment by akhil-gautam** [comment]
Try the below snippet:
```
      <Carousel
        renderCenterLeftControls={({ previousSlide }) => (
          null
        )}
        renderCenterRightControls={({ nextSlide }) => (
          null
        )}
      >
        <img src="http://placehold.it/1000x400/ffffff/c0392b/&text=slide1" />
        <img src="http://placehold.it/1000x400/ffffff/c0392b/&text=slide2" />
        <img src="http://placehold.it/1000x400/ffffff/c0392b/&text=slide3" />
        <img src="http://placehold.it/1000x400/ffffff/c0392b/&text=slide4" />
        <img src="http://placehold.it/1000x400/ffffff/c0392b/&text=slide5" />
        <img src="http://placehold.it/1000x400/ffffff/c0392b/&text=slide6" />
      </Carousel>
```

**Comment by akhil-gautam** [comment]
Please close the issue if the above thing works.

**Comment by clayhan** [comment]
@akhil-gautam Thanks a ton for your help. I was not quite sure how to accomplish what you were saying via CSS (to know whether I was at the start or end of the carousel).

Right now I'm implementing something like this:
`
// This would be like my array of elements that I want to turn into slides.
const myArrayOfSlidesLength = 6;

return (
 <Carousel
          renderCenterLeftControls={({ previousSlide, currentSlide }) => currentSlide === 0 : null ? <button>{currentSlide}</button>}
          renderCenterRightControls={({ nextSlide, currentSlide }) => currentSlide === myArrayOfSlidesLength - 1  : null ?}
        >
          <img src="http://placehold.it/1000x400/ffffff/c0392b/&text=slide1" />
          <img src="http://placehold.it/1000x400/ffffff/c0392b/&text=slide2" />
          <img src="http://placehold.it/1000x400/ffffff/c0392b/&text=slide3" />
          <img src="http://placehold.it/1000x400/ffffff/c0392b/&text=slide4" />
          <img src="http://placehold.it/1000x400/ffffff/c0392b/&text=slide5" />
          <img src="http://placehold.it/1000x400/ffffff/c0392b/&text=slide6" />
        </Carousel>
);
`
