### ISSUE TITLE
Customized Bottom Controls

### ISSUE THREAD

**Issue by carloquilala** [FormidableLabs/nuka-carousel#461]
Is there a way to customize bottom controls? the dots? I would like to calculate the dots as per page based on the slideToShow prop

ie, I have 5 slides, and I want to show 3 slides per page, the rendered dots would be 2

**Comment by LuisSaybe** [comment]
https://github.com/FormidableLabs/nuka-carousel#user-content-rendercontrols

**Comment by carloquilala** [comment]
I mean how can I change the default ul/li elements as I want to render my custom component for the dots

**Comment by sarmeyer** [comment]
Hi @carloquilala, yes you should be able to render your custom components with the `renderBottomCenterControls` prop. For the demo, we are rendering a `PagingDots` component, but you could set the `renderBottomCenterControls`  prop to which ever customer component you would like.

**Comment by LeyliAbbas** [comment]
I did like this: 

`renderBottomCenterControls={({ slideCount, currentSlide, goToSlide }) =>
                <div className="slider-control-bottomcenter">
                    <ul>
                        {[...Array(slideCount)].map((e, key) =>
                            <li className={currentSlide == key ? "active" : undefined} key={key}>
                                <button type="button" aria-label="slide 1 bullet" onClick={() => goToSlide(key)}>
                                    <svg width="12" height="12">
                                        <rect width="10" height="10" />
                                    </svg>
                                </button>
                            </li>
                        )}
                    </ul>
                </div >
            }`

And for SCSS:

`.slider-control-bottomcenter {
    position: absolute;
    bottom: 45px;
    left: 50%;
    transform: translateX(-50%);

    ul {
        position: relative;
        top: -10px;
        display: flex;
        margin: 0px;
        padding: 0px;
        list-style-type: none;

        li {
            button {
                cursor: pointer;
                opacity: 1;
                background: transparent;
                border: none;
                fill: white;
            }
        }
    }

    .active {
        button {
            fill: #0B296C !important;
        }
    }
}`

**Comment by LeyliAbbas** [comment]
I did like this:

```
            renderBottomCenterControls={({ slideCount, currentSlide, goToSlide }) =>
                <div className="slider-control-bottomcenter">
                    <ul>
                        {[...Array(slideCount)].map((e, key) =>
                            <li className={currentSlide == key ? "active" : undefined} key={key}>
                                <button type="button" aria-label="slide 1 bullet" onClick={() => goToSlide(key)}>
                                    <svg width="12" height="12">
                                        <rect width="10" height="10" />
                                    </svg>
                                </button>
                            </li>
                        )}
                    </ul>
                </div >
            }
```

And SCSS:

```
.slider-control-bottomcenter {
    position: absolute;
    bottom: 45px;
    left: 50%;
    transform: translateX(-50%);

    ul {
        position: relative;
        top: -10px;
        display: flex;
        margin: 0px;
        padding: 0px;
        list-style-type: none;

        li {
            button {
                cursor: pointer;
                opacity: 1;
                background: transparent;
                border: none;
                fill: white;
            }
        }
    }

    .active {
        button {
            fill: #0B296C !important;
        }
    }
}
```
