### ISSUE TITLE
 Externally controlled carousel will not advance to next slide

### ISSUE THREAD

**Issue by LuisSaybe** [FormidableLabs/nuka-carousel#462]
https://codesandbox.io/s/ko4zr05r7

externally controlled carousel will not advance to next slide, am I am missing something here?

**Comment by j0nd0n7** [comment]
Facing the same issue. Looking also for a solution...

**Comment by LuisSaybe** [comment]
any updates on this?

**Comment by twankruiswijk** [comment]
Also having the same issue, setting `dragging` to false fixes the issue. Only I want the user to be able to drag or click a button. 😅
