### ISSUE TITLE
Hidden when render with `ReactDOMServer.renderToString`

### ISSUE THREAD

**Issue by Xdudu** [FormidableLabs/nuka-carousel#463]
In my project there is a need to render with `ReactDOMServer.renderToString`, which causes `visibility: hidden` in style of the carousel, does anybody have any idea? Here is a [CodeSandBox](https://codesandbox.io/s/1059v3pw63) representing it.

**Comment by yestoall** [comment]
i have the same problem with SSR

**Comment by bslinger** [comment]
I'm having this issue too, not sure what the best solution is but I'll probably need to make a fork and bang away at a solution for our site for now.
