### ISSUE TITLE
afterSlide was called with NaN

### ISSUE THREAD

**Issue by DualWield** [FormidableLabs/nuka-carousel#471]
### Describe Your Environment

- What version of nuka-carousel are you using?
4.4.4
- What version of React are you using?
16.5.2
- What browser are you using?
chrome
- What machine are you on?
mac os

### Describe the Problem

When I swipe the slider, the argument passed in by the afterSlide function is **NaN**

https://codesandbox.io/s/4q19xp78kx

**Expected behavior:** [What you expect to happen]
the argument is the correct index
**Actual behavior:** [What actually happens]
the argument is the **NaN**

### Additional Information
4.4.1 version won't have this problem

**Comment by sarmeyer** [comment]
@DualWield this is fixed in #466
