### ISSUE TITLE
Click on child card could not correctly render

### ISSUE THREAD

**Issue by iSophia** [FormidableLabs/nuka-carousel#476]
Click on child card intent to swipe to the clicked card, but could not correctly render

I have found the bug. When user click on the child card, Carousel will invoke touchEnd function, and then touchend will set isTransitioning=true, so when the sildeIndex changed and invoke propsWillReceive, the isTransitioning is still true, it will won't excute goToSlide function. May I suggest adding a condition in goToSlide. if the changingIndex === state.currentSlide the core function of goToSlide will not excute.

**Comment by sarmeyer** [comment]
@iSophia Can you please provide a minimal repository or a CodeSandbox with install + error reproduction steps so we can jump and see what you see? Thanks!
