### ISSUE TITLE
TypeScript types are missing in v4.4.6

### ISSUE THREAD

**Issue by formatlos** [FormidableLabs/nuka-carousel#478]
obviously `index.d.ts` doens't get published with npm

**Comment by ryan-roemer** [comment]
Suggest we update https://github.com/FormidableLabs/nuka-carousel/blob/master/.npmignore to include:

```
!index.js
!index.d.ts
```

(Index.js is already in the published package, but let's be explicit).

**Comment by sarmeyer** [comment]
I'll fix this and get it out in a release today. thanks @formatlos

**Comment by sarmeyer** [comment]
fixed: https://github.com/FormidableLabs/nuka-carousel/pull/480
