### ISSUE TITLE
Opt-in for new features via props, instead of opt-out

### ISSUE THREAD

**Issue by pimverlangen** [FormidableLabs/nuka-carousel#479]
Would it be possible to have new features to be disabled by default? Features like the zoom and keyboard controls can cause unexpected behaviour after updating this library to the newest version. Instead of having a `disableKeyboardControls`, wouldn't it be easier to have an `enableKeyboardControls`, in which you opt-in to this feature?

**Comment by sarmeyer** [comment]
@pimverlangen Yes! This is a great idea. I'll work on switching them around today

**Comment by sarmeyer** [comment]
@pimverlangen did you have a specific issue with the zoom animation? That prop is `undefined` by default, so you would have to pass it in to observe its behavior.

**Comment by pimverlangen** [comment]
@sarmeyer perhaps I was too eager with saying that the zoom feature had it as well (seems it does not ;) ).  I would not change the current defaults, as that would cause unexpected behaviour again in a new release. I think it's best to have only the new features disabled by default.

**Comment by sarmeyer** [comment]
@pimverlangen I understand! Just wanted to make sure I didn't miss something with the zoom animation. Good call on having new props be "opt-in"

**Comment by sarmeyer** [comment]
fixed disableKeyboardControls and made note of this for future new props - https://github.com/FormidableLabs/nuka-carousel/pull/480
