### ISSUE TITLE
regression : swipe less smooth on mobile since 4.4.4

### ISSUE THREAD

**Issue by lauterry** [FormidableLabs/nuka-carousel#493]
# Bugs and Questions

### Describe Your Environment

- What version of nuka-carousel are you using? 4.4.4
- What version of React are you using? 15.6.1
- What browser are you using? Chrome mobile
- What machine are you on? Android

### Describe the Problem

Please try the carousel on a mobile device and swipe the photos. https://codesandbox.io/s/407wz93p79

You can see a difference on how the photo swipes between v4.4.3 and v4.4.4. (Please change the version in the package in the codesanbox)

**Expected behavior:** I expect the photos to slide more smoothly
**Actual behavior:** The slide animation is not smooth

**Comment by shunxing** [comment]
Hi ! 
I guess it comes with PR #458. I rollbacked the changes on this PR and it seems to have smoother transitions.  Can we do something about this rollback ? 

@sarmeyer

**Comment by lauterry** [comment]
Hi 

With the new release of version 4.4.8, this issue is still here :(

**Comment by lauterry** [comment]
Hi

I've just tried @shunxing 's PR https://github.com/FormidableLabs/nuka-carousel/pull/508 and there is no more swipe animation issue.

It fixes this issue.

Please accept the PR asap if it is good for you. 

Thx
