### ISSUE TITLE
Migrate from Slick Carousel

### ISSUE THREAD

**Issue by davthu** [FormidableLabs/nuka-carousel#497]
This is not an issue but rather a question. Hopefully it is ok to post it here ☺️

We want to migrate from Slick Carousel (which uses jQuery) to Nuka Carousel and my question is if it is possible to render multiple items with a responsive setting just like it is possible to do with Slick?

**Comment by sarmeyer** [comment]
Hi @davthu! what do you mean "responsive setting"?

**Comment by davthu** [comment]
@sarmeyer Look under the ’responsive’ setting on Slick: https://github.com/kenwheeler/slick/blob/master/README.markdown#settings

**Comment by BDMayhem** [comment]
@davthu Check out this comment for a responsive workaround
https://github.com/FormidableLabs/nuka-carousel/issues/388#issuecomment-464581940

**Comment by sarmeyer** [comment]
hey @davthu! This has been stale for quite a while - has your question been answered?
