### ISSUE TITLE
The Google Chrome memory issue.

### ISSUE THREAD

**Issue by SmirnovW** [FormidableLabs/nuka-carousel#498]
# Bugs and Questions

### Describe Your Environment

- version 4.4.7 
- React 16.6.0
- Chrome 72
- Ubuntu

### Describe the Problem

There is the AnnounceSlide component, and it has the styles with the property "left" equals to "-10000px".
In some cases, the Google Chrome does "squashing" of the layers because of the performance reasons, and it creates a huge layer with the "width" more than "10000px". The browser needs a pretty much memory to process it.

Example: https://codesandbox.io/s/40zj6kq22w

I've tried to remove this property and it affects nothing. What the reason having the "left" equals to "-10000px"?

The memory estimate with "left: -10000px"
![screenshot from 2019-02-04 11-33-53](https://user-images.githubusercontent.com/12068000/52195425-51c82f00-2871-11e9-925d-534013a11c58.png)

without
![screenshot from 2019-02-04 11-35-19](https://user-images.githubusercontent.com/12068000/52195409-407f2280-2871-11e9-9a59-fbb3487d8955.png)

**Comment by john-d-pelingo** [comment]
@SmirnovW Out of topic and curious question but what steps did you take to display that Details pane?

**Comment by MilllerTime** [comment]
Using an empty element with the `aria-label` attribute would likely be preferable over a huge `left` value.

Instead of the following:

https://github.com/FormidableLabs/nuka-carousel/blob/bb73af942a201b2ed9f81666598a9cd076d2b9f4/src/announce-slide.js#L3-L17

Would this be suitable? Maybe there's a problem I'm missing.

```js
const AnnounceSlide = ({ message }) => {
  return (
    <div
      aria-label={message}
      aria-live="polite"
      aria-atomic="true"
      tabIndex={-1}
    />
  );
};
```

@john-d-pelingo The layer details pane is visible within the top-level "Layers" tab in dev tools.

**Comment by lucafraser** [comment]
I fixed this issue by using[ react-lazyload](https://www.npmjs.com/package/react-lazyload), perhaps it helps you too.

**Comment by yoavniran** [comment]
was testing my page locally with chrome's dev-tools. after implementing the carousel and every time i switched to responsive mode my page would go blank.
Drove me crazy until i realized it was the Announce slide and its weird style. 
Very annoying that I cant decide I dont want it (let me control whether its rendered or not) so i ended up using a css rule on its container to display none...

```
const Container = styled.div`
   ...
   div[aria-live] {
		display:none;
	}
`;
```
definitely not happy with this solution but needed a quick win to let me get on with my testing...

**Comment by fritz-c** [comment]
It appears we don't use the large negative `left` value for `AnnounceSlide` any more, so presumably this issue as described is fixed.
