### ISSUE TITLE
v.4.5.1 can't dragging for desktop screen but works fine on v.4.4.6 but there is no zoomScale Feature on v.4.4.6

### ISSUE THREAD

**Issue by gagahkharismanuary** [FormidableLabs/nuka-carousel#514]
I found some issues for dragging on the desktop screen but dragging works fine only on the mobile screen.

I tried the v4.5.1 and that's the issue I found, but when I try to change the version for v4.4.6, either mobile and desktop works fine for dragging feature. Only in v4.4.6 there is no zoomScale Props.

can we just fix this for the next version to works fine for dragging and zoomScale  ?

here, I got some diff for considering the codebase from nuka-carousel in src/index

previously(4.4.6) and current (4.5.1)

https://www.diffchecker.com/fCNs5cNm

**Comment by oliverholliday** [comment]
Same issue. Updated to 4.5.1 and mouse dragging doesn't work.

**Comment by sarmeyer** [comment]
Fixed in 4.5.2
