### ISSUE TITLE
autoGenerateStyleTag prop is missing in types for TypeScript

### ISSUE THREAD

**Issue by Ronny25** [FormidableLabs/nuka-carousel#515]
### Prerequisites

**Expected behavior:** 
I want to use autoGenerateStyleTag prop

**Actual behavior:** 
TypeScript complaining that this prop does not exist

**Comment by sarmeyer** [comment]
@Ronny25 if you'd like to add it to the index.d.ts file, feel free! Otherwise, I'll get to this after the weekend.
