### ISSUE TITLE
Problem using PreviousSlide or NextSlide function

### ISSUE THREAD

**Issue by whereismysoft** [FormidableLabs/nuka-carousel#518]
# Bugs and Questions
nuka-carousel v 4.5.2
react v 16.8.4

i have a problem when im invoke function below: 

```
onSlideChange(fn, typeOfSlide) {
    const slidesToMove = () => typeOfSlide === 'prev' ? -1 : 1;

    if (this.state.slideIndex === 0 && typeOfSlide === 'prev' || this.state.slideIndex === this.props.images.length - 1 && typeOfSlide === 'next') {
        return
    }
 
    this.setState((prevState, props) => ({
        slideIndex: prevState.slideIndex + slidesToMove(),
     }), fn())
}
```

this function im invoke inside button method onClick 

```
<Carousel
    disableAnimation
    swiping={false}
    renderBottomCenterControls={ () => null}
    slideIndex={this.state.slideIndex}
    renderCenterLeftControls={({ previousSlide }) => (
         <button onClick={() => this.onSlideChange(previousSlide, 'prev')}>Previous</button>
     )}
    renderCenterRightControls={({ nextSlide }) => (
        <button onClick={() => this.onSlideChange(nextSlide, 'next')}>Next</button>
    )}
>
```

the problem is when button have multiple clicks in a row,  nextSlide or previousSlide changes slide only onсе, while state value changes on count of clicks

**UPD:**
 in my situation i found solution using returned value in beforeSlide method by comparing its second parameter in array with my value in state

**Comment by johannam999** [comment]
@whereismysoft Thanks for sharing your solution! Do you have any questions related to this issue or are you hoping to find a different solution?

**Comment by sho13** [comment]
@whereismysoft can you update with an example of your solution, your explanation isn't really clear to me, thanks!

**Comment by whereismysoft** [comment]
hi @yomanmf
I think part of this code is lost

the idea was that **beforeSlide** method invokes on every click
you can open a new issue and i will happy to help you
