### ISSUE TITLE
Warning: `ul` was passed a style object that has previously been mutated

### ISSUE THREAD

**Issue by JonathanWi** [FormidableLabs/nuka-carousel#52]
Hello!

When using your component, I'm prompted with the following warning 
<img width="431" alt="capture d ecran 2016-02-04 a 12 37 23" src="https://cloud.githubusercontent.com/assets/1074479/12814024/2b652c68-cb3c-11e5-9277-df206adef077.png">

Any idea of what is happening?

Thanks a lot

**Comment by abhilashsajeev** [comment]
@kenwheeler  +1 for this issue

**Comment by kenwheeler** [comment]
This should be fixed in the latest release. Still seeing it? It's due to NaN values

**Comment by senkevichdv** [comment]
@kenwheeler yes, still have this warning.
