### ISSUE TITLE
Question about Size

### ISSUE THREAD

**Issue by jessicabyrne** [FormidableLabs/nuka-carousel#520]
# Questions

### Describe the Problem

We are using a forked version of nuka-carousel from 3.x and want to upgrade to the latest due to React 16 upgrades. However, the bundle size of nuka-carousel is making us balk. 

It is 2x as big as the package size of the 3.x branch, from 33kB to 63kB
https://bundlephobia.com/result?p=nuka-carousel@4.5.3
<img width="1630" alt="Screen Shot 2019-03-21 at 4 23 17 PM" src="https://user-images.githubusercontent.com/17936686/54837181-fe743980-4c82-11e9-9f1c-82ddb0a3f568.png">

Are there plans in motion to try to trim this down? I am planning on looking into it but was wondering if there already is a plan or if this has been addressed before.

### Additional Information
We are tempted to upgrade what we have on 3.x to stop using create-react-class and mixins, but of course we'd like to keep up-to-date and help contribute to OSS. If there is a path to trim down or make a mini-nuka we would be on board for it!

**Comment by sarmeyer** [comment]
Hey @jessicabyrne - there are no active plans underway to reduce the bundle size, but it definitely seems to be an issue so I'd love to get it slimmed down. Are you interested in looking into it and attempting to reduce the bundle size?

**Comment by ljones87** [comment]
Hi @jessicabyrne! I am currently looking into and working on reducing nuka's bundle size. I'll keep this issue updated as I make progress.

**Comment by bogdansoare** [comment]
any news on this?

**Comment by ValGeorgiev** [comment]
Hey all, v5 is now released, and you can install and use it. Here is a comparison between v5 and v4

v4
![image](https://user-images.githubusercontent.com/12056467/154492830-1d921b1a-8e97-4f1a-bbbc-1f519cc9d755.png)


v5
![image](https://user-images.githubusercontent.com/12056467/154492786-619b11cc-8567-4c19-ad3b-64bb4bd0df88.png)

There is 0 dependencies in v5 (for now). In the near future we will introduce only one. I will close this now. Feel free to raise another issue if you have more concerns.
