### ISSUE TITLE
Miscalculation of width or height on first paint until there is resize event 

### ISSUE THREAD

**Issue by stunaz** [FormidableLabs/nuka-carousel#521]
# Bug

### Prerequisites

**Feel free to delete this section if you have checked off all of the following.**

- [x] I've searched open [issues](https://github.com/FormidableLabs/nuka-carousel/issues) to make sure I'm not opening a duplicate issue : related to https://github.com/FormidableLabs/nuka-carousel/issues/349
- [x] I have read through the docs before asking a question
- [x] I am using the latest version of nuka-carousel

### Describe Your Environment

- What version of nuka-carousel are you using? latest
- What version of React are you using? latest
- What browser are you using? chrome
- What machine are you on? windoes

### Describe the Problem

The width or height are miscalculated on first paint until there is resize event :
https://codesandbox.io/s/xpz69xnx94

just using the following code:
```javascript
    <Carousel>
      <img src="http://placehold.it/1000x400/ffffff/c0392b/&text=slide1" />
      <img src="http://placehold.it/1000x400/ffffff/c0392b/&text=slide2" />
      <img src="http://placehold.it/1000x400/ffffff/c0392b/&text=slide3" />
      <img src="http://placehold.it/1000x400/ffffff/c0392b/&text=slide4" />
      <img src="http://placehold.it/1000x400/ffffff/c0392b/&text=slide5" />
      <img src="http://placehold.it/1000x400/ffffff/c0392b/&text=slide6" />
    </Carousel>
```
![bug](https://user-images.githubusercontent.com/1305483/54834863-69c80680-4c97-11e9-88a6-5fb341d64bb9.png)

If i run `window.dispatchEvent(new Event("resize"));` on the console, it will display correctly

**Comment by agonsalves** [comment]
I am also experiencing this issue.

My workaround is to use a hook:
```
    useEffect(() => {
        setTimeout(() => window.dispatchEvent(new Event("resize")), 0)
    }, [])
```

Would love a better solution that doesn't have any flicker.

**Comment by YLemelin09** [comment]
It would be great to not have to set  a height value to the carousel and have it sized automatically according to its children

**Comment by lucas3fonseca** [comment]
Any updates on this issue?

**Comment by TimMeade** [comment]
Hit this also.   width=100% killing mobile. 

Workaround was to wrap everything in a div with max-width: 100vw;   Constrained it.  but certainly a hack fix.

**Comment by YLemelin09** [comment]
This is still an issue. I tried calling a window resize on componentdidmount but it did nothing

**Comment by pragmatic84** [comment]
Just started using this carousel today, same issue here. First image is like 25px high (container is around 300px) until you either resize or click next slide, then everything sorts itself out.
Any help would be very much appreciated.....I got kids to feed man.... :P

**Comment by sarmeyer** [comment]
@pragmatic84 do you have a reproducible example I can look at? I'm having trouble reproducing the issue consistently and any new code examples are greatly appreciated!

**Comment by lpetkovic** [comment]
Best solution I found for this is to add a ref to Carousel component and then call: 

`this.carousel.setDimensions()`

when needed. I had trouble since all elements in Carousel were images, so the height/width wasn't calculated properly since images loaded after Carousel was initialized, so calling
`onLoad={this.carousel.setDimensions}` solved it for me.

**Comment by lpetkovic** [comment]
Best solution I found for this is to add a ref to Carousel component and then call:

this.carousel.setDimensions()

when needed. I had trouble since all elements in Carousel were images, so the height/width wasn't calculated properly since images loaded after Carousel was initialized, so calling
onLoad={this.carousel.setDimensions} solved it for me.

**Comment by stunaz** [comment]
updated the sandadbox with the last lib. its better, but still broken.
if you try to refresh the browser within codesandbox, you will get the error at least 1 out of 10 times

**Comment by sarmeyer** [comment]
@stunaz I made a small change that I think fixes the issue (at least it does in the codesandbox) https://github.com/FormidableLabs/nuka-carousel/pull/582

**Comment by wwwebman** [comment]
@sarmeyer, IMHO, sanbox fix -> `style={{height:'inherit'}}` looks more like a workaround, bc then we need to set height explicitly in carousel wrapper.  Would be much better if  height could be taken from children on the very beginning. 

How we see the bug:
![screencast-localhost-3001-2019 09 09-10-55-13](https://user-images.githubusercontent.com/13425833/64517501-bf997500-d2f0-11e9-8fd3-a099ee81b79b.gif)

**Comment by stunaz** [comment]
Seems fixed to me 🥇

**Comment by jibin2706** [comment]
@stunaz still not fixed

**Comment by stunaz** [comment]
indeed not fixed

**Comment by YLemelin09** [comment]
The way I fixed it in my code was to add a fixed ratio on the image part of my child elements in the carousel. ex: padding-top: 56.25%
This way the carousel renders with the height forced from the children element before the images load

**Comment by jibin2706** [comment]
@YLemelin09 That didn't work for me

**Comment by jibin2706** [comment]
heightMode="max" seems to fix the issue for me. But can't say for sure.
