### ISSUE TITLE
How to add jpg/png images? 

### ISSUE THREAD

**Issue by swoodivyesh** [FormidableLabs/nuka-carousel#533]
# Bugs and Questions
### Describe Your Environment

- What version of nuka-carousel are you using? 4.5.4
- What version of React are you using? 16.8.6
- What browser are you using? Google Chrome
- What machine are you on? Macbook Pro 2017 15"

### Describe the Problem

https://gyazo.com/5ce88e6f2dff7d293af3ae5979e46003

<img width="636" alt="Screenshot 2019-04-17 at 12 55 58 PM" src="https://user-images.githubusercontent.com/44566237/56268971-36e72600-6110-11e9-9d8a-35625ced120f.png">

see the above GIF file I have added the first image which is jpg file but it isn't loading. I am only able to load SVG files. 

```jsx
import {ReactComponent as Group4} from '../../assets/Mobile BG.svg';
import {ReactComponent as Group27} from '../../assets/Group 27.svg';

<div className="carousel2">
   <Carousel
	cellSpacing={5}
	dragging={true}
	slidesToShow={1.5}
	withoutControls={true}
   >
      <img src="../../assets/fallingthrough.jpg"/>
      <Group4/>
      <Group27/>
   </Carousel>
</div>
```

**Expected behavior:** [What you expect to happen] : I want that images to be loaded in the carousel item itself
**Actual behavior:** [What actually happens] image is not loading.

### Additional Information
Also how do I adjust the height of the carousel with it? I have other carousels on the same page as well but it isn't showing with the full height and width? 

Suppose I want carousel items to render following details then how do I entail them in one carousel item?

```jsx
<div className="commentsection">
<Carousel
   cellSpacing={5}
   dragging={true}
   slidesToShow={1}
   withoutControls={false}
>
	<h3>profile</h3>
	<p>Username</p>
	<p>userhandle</p>
	<p>comment</p>
</Carousel>
</div>
```
<img width="673" alt="Screenshot 2019-04-17 at 12 54 36 PM" src="https://user-images.githubusercontent.com/44566237/56268916-18812a80-6110-11e9-9a69-10721ed6845a.png">

**Comment by sarmeyer** [comment]
Hi @swoodivyesh - I am unable to reproduce the issue you're seeing with a jpg image. I would be curious what the error is. Could you send it over to me? Or even better, would it be possible to replicate your code in a codesandbox so I could locally test the issue out?

For your second question, I would wrap the h3 and p tags in a div and you can set the height on that div.

**Comment by swoodivyesh** [comment]
Hi @sarmeyer thank you for the response, I got to know that I was using it the wrong way. Actually while using `Create-react-app` if one wants to add images with `img` tag, it should be written as follows: 

```jsx
<img src={require('../path/myimages.png')} />
```

One needs to add the image by `require`. I guess this justifies my query please close this thread.
Thanks

**Comment by sarmeyer** [comment]
@swoodivyesh Thanks for letting me know!

**Comment by abouzeyd** [comment]
hi i'hve same issue i need to help

**Comment by abouzeyd** [comment]
![Screen Shot 2021-04-13 at 15 42 24](https://user-images.githubusercontent.com/47893442/114581008-e3f8c880-9c6e-11eb-9d20-3d267afa86a1.png)
