### ISSUE TITLE
Applying custom styles

### ISSUE THREAD

**Issue by AnalogMemory** [FormidableLabs/nuka-carousel#539]
What's the recommended way to pass styles to the carousel elements? I don't see any way to pass a style object. My current workaround is to override all styles, but because everything is inline it requires an ugly `!important` after every style prop.

**Comment by sarmeyer** [comment]
@AnalogMemory Which carousel elements are you trying to target? Can you provide an example of what styles you are attempting to apply?

Thanks!

**Comment by AnalogMemory** [comment]
@sarmeyer So mostly the sider control elements e.g. `.slider-control-bottomcenter`, `.slider-control-topcenter`, also the slider element `.slider-slide`

**Comment by AnalogMemory** [comment]
@sarmeyer Following up with this, here's a live example of what I'm trying to do. At a basic level I'm trying to push styles to the pager dots. 
Would this be the best way to customize them? 
The `! important` after every style change is pretty annoying.

https://codesandbox.io/s/nukacarouselcustompagerstyles-pob7c

**Comment by sarmeyer** [comment]
this might be fixed in this PR https://github.com/FormidableLabs/nuka-carousel/pull/564
I will release this today!

**Comment by AnalogMemory** [comment]
@sarmeyer oh nice, I see that PagingDots & Nav components will be exported separately. Which should make styling easier. Thanks!

**Comment by sarmeyer** [comment]
Solved in recent versions, if this is still a concern, please reopen!

**Comment by roman-veryovkin** [comment]
Hi @sarmeyer,

Could you show an example of how can I apply custom styles to the `.slider-slide` elements? For instance, how to make margin-right to each slide except the last one?

**Comment by sk-izsk** [comment]
yes would like to see an example, my concern is regarding `slider-frame`
