### ISSUE TITLE
Disable scroll before first slide and after last slide

### ISSUE THREAD

**Issue by maurispalletti** [FormidableLabs/nuka-carousel#542]
Is there a way to disable scroll before the first slide and after the last slide? And also is it possible to disable edge animations?

**Comment by sarmeyer** [comment]
Hi @maurispalletti Nuka has an optional prop `disableAnimation` you can pass in `true` to disable animations. 

What do you mean by "disable scroll"? Are you referencing dragging?

**Comment by YLemelin09** [comment]
I think he meant to not render the left control when you're at the beginning slide and the right one when you're at the last slide.

**Comment by maurispalletti** [comment]
It is actually the white space that appears before the first slide or after last slide when swiping. I was searching for an option to disable that (like instagram does, that lock you from swiping to edges.

**Comment by r0kan** [comment]
some issue
