### ISSUE TITLE
wrapAround and slidesToShow number being 1 less than number of slides leads to bad display

### ISSUE THREAD

**Issue by povilaspin** [FormidableLabs/nuka-carousel#548]
# Bugs and Questions

- What version of nuka-carousel are you using? - 4.5.5
- What version of React are you using? - 16.8.6 (reproducible on any react version)
- What browser are you using? - bug isn't related to browser
- What machine are you on? - macbook pro 2018, but not related to machine.

### Describe the Problem

When you have wrapAround set to true, slidesToShow set f.e to 4, and have 5 slides in the slider, the last one is not shown, leaving a white gap in the place of it.

Sandbox to reproduce: https://codesandbox.io/s/v0n97j1yq3

**Comment by the-fedorr** [comment]
Having same issue. The number of slides should be 2 times more then `slidesToShow` value, then it works fine.
As workaround - i multiply slides to match slidesToShow*2 count.

**Comment by MrAvantiC** [comment]
Same issue here.
The behaviour can be reproduced pretty easily with the Demo-Sandbox by changing `slidesToShow` to 6 and `wrapAround` to `true`, see:
https://codesandbox.io/s/admiring-lamarr-60du4

**Comment by Weffe** [comment]
I am also getting this issue. Same scenario and same result.
