### ISSUE TITLE
`disableEdgeSwiping` prevents from going back to first slide

### ISSUE THREAD

**Issue by feather-aurelie** [FormidableLabs/nuka-carousel#552]
# Bugs and Questions

- What version of nuka-carousel are you using?
4.5.8
- What version of React are you using?
16.2.0 (tried with 16.8.6 too)
- What browser are you using?
chrome & iOs Safari
- What machine are you on?
Macbook & Iphone

### Describe the Problem
`disableEdgeSwiping` creates a bug - it prevents from scrolling back to the first slide, the carousel is blocked and we only see half of the first image.

see here minimal demo: https://codesandbox.io/s/wonderful-hugle-t4lfi?fontsize=14

**Comment by sarmeyer** [comment]
hey @feather-aurelie it seems to be an issue with the `cellSpacing` prop. I'm looking into why that prop is causing the bug. Do you need the `cellSpacing` prop for a specific reason in your app? If there is a workaround to achieve what that prop is doing, that could be a hacky fix to get `disableEdgeSwiping` enabled and working correctly while I work on this!

**Comment by feather-aurelie** [comment]
thanks for looking into this @sarmeyer, unfortunately I don't think that `cellSpacing` is the issue here. After looking into it a little bit more, the `cellAlign` prop seems to be causing the bug.
