### ISSUE TITLE
Pressing enter on other form elements triggers transition

### ISSUE THREAD

**Issue by JohnSocialisten** [FormidableLabs/nuka-carousel#554]
- What version of nuka-carousel are you using? 4.5.8
- What version of React are you using? 16.8.6
- What browser are you using? Chrome
- What machine are you on? Mac

### Describe the Problem

We have the Carousel inside a large form. When highlighting any totally independent element on the form (e.g. a select list), and repeatedly hitting enter on that element, the Carousel constantly toggles between the first and second image every time Enter is pressed.

The problem has nothing to do with Redux or local State, in fact **when I hard code `slideIndex={1}` the behaviour persists**. I have no clue how this can be.

- Do you know how this carousel can toggle between two images when the slideIndex value is fixed?

- Do you know how hitting Enter on completely unrelated input elements can trigger activity on this Carousel component?

I've checked the props coming into the Carousel component and they are completely unchanging, but then Carousel toggles from 0 -> 1 -> 0 -> 1 etc...

Thanks for your time

**Comment by paulathevalley** [comment]
Thanks for the bug report, @JohnSocialisten!

> Do you know how hitting Enter on completely unrelated input elements can trigger activity on this Carousel component?

The default for `button` has an implicit `button type="submit"`, which means the `NextButton` and `PreviousButton` are trying to submit the form on pressing enter. Opened PR here: https://github.com/FormidableLabs/nuka-carousel/pull/571
