### ISSUE TITLE
`heightMode: 'current'` + `slidesToShow: [>1]` should set the height to the height of the tallest visible slide

### ISSUE THREAD

**Issue by dallanlee** [FormidableLabs/nuka-carousel#556]
Firstly, thank you to the author and contributors of this carousel 👏🏼

### Describe Your Environment

- What version of nuka-carousel are you using? **latest**
- What version of React are you using? **latest**
- What browser are you using? **Chrome, latest**
- What machine are you on? **MBP 2018 running macOS Mojave, latest**

#### Expected behavior:
When showing more than one slide and using the `'current'` value for the `heightMode` option, the height should be determined by any of the _current_-ly visible slides and not just the "active" slide.

#### Actual behavior:
When setting the `slidesToShow` to a value >1 and the `heightMode` to `'current'`, the slider's height is determined only by the "active" or left most slide of the slides showing, not taking into account the height(s) of additional slide(s) visible.

For example, you set `slidesToShow={3}` and if the first three slides are showing—this means the first slide is active—the slider's height is determined by the first slide's height even though the second and/or third slides may be taller.

--------------------------

Maybe I'm missing something. Is there currently a way to achieve this? If not, I would like to recommend that this be changed to behave the way I've described. Thanks!

**Comment by sarmeyer** [comment]
Hi @dallanlee I agree, this is how the carousel should behave, or there should at least be a way to access that behavior. I can spend a little time on it today and see if I can get a solution going!

**Comment by dallanlee** [comment]
👋🏼 @sarmeyer Any progress on this so far?

**Comment by sarmeyer** [comment]
@dallanlee I haven't been able to get a solution working fully yet. I can get it to work for a specific set of props, but not for all scenarios. So I'm continuing to work on that. I have a WIP branch pushed up if you or anyone else wants to take a look! `bug/fix-current-height-slidestoshow`
