### ISSUE TITLE
v4.5.9 manual set slideIndex not working

### ISSUE THREAD

**Issue by shauvet** [FormidableLabs/nuka-carousel#558]
- What version of nuka-carousel are you using? 4.5.9
- What version of React are you using? 15.6.1
- What browser are you using?  chrome
- What machine are you on? mac

**Expected behavior:** 
set slideIndex will auto change to new image 
**Actual behavior:**
set slideIndex no response

### Additional Information
I was try to debugger into the lib/index.js file. And I found set slideIndex would into the
componentWillReceiveProps, this is correct,  but then it not go into the goToSlide function, 
this is strange indeed.

**Comment by sarmeyer** [comment]
@shauvet Are you able to provide more information about the issue you're having? A codesandbox or code example of how you're trying to manually set slideIndex would be helpful in our investigation of this issue. Thanks
