### ISSUE TITLE
Using wrapAround and Fade transitionMode Causes Gap in Carousel

### ISSUE THREAD

**Issue by devolasvegas** [FormidableLabs/nuka-carousel#559]
# Bugs and Questions

### Describe Your Environment

- What version of nuka-carousel are you using?
^4.5.9
- What version of React are you using?
^16.8.4
- What browser are you using?
Chrome Version 75.0.3770.100
- What machine are you on?
Windows 10

### Describe the Problem
With "transitionMode={'fade'}" and "wrapAround={true}," when the carousel comes back around to the first slide, the first slide displays momentarily, then disappears, leaving no slide displaying, then comes back again before the carousel transitions to the next slide. It appears there is a period where all slides' opacity is set to 0.

**Expected behavior:**
Carousel wraps back around to the first slide and proceeds smoothly on with the rest.

**Actual behavior:** 
There is a period where all slides have their opacity set to 0.

**Comment by sarmeyer** [comment]
@devolasvegas is this with `autoPlay=true`? You said, "when the carousel comes back around". I'm trying to reproduce and having issues. I see a flash when autoPlay is on and the carousel gets back around to the 1st slide, but that is a known issue. So I'm wondering if this is something different.

**Comment by devolasvegas** [comment]
Ah yes, @sarmeyer, this is with autoPlay set to true. I suppose in my haste I didn't come across the other issue in my search. Thanks.

I look forward to the issue being cleared up! I really like Nuka.

**Comment by rogerchi** [comment]
I'm also still getting this issue in v4.6.1.  If I have a carousel with two slides (autoPlay=true, transitionMode=fade, wrapAround=true), after the first transition back to slide 1, I can see that slide 1's opacity = 1, but then as soon as slide 2's opacity finishes transitioning to 0, slide 1's opacity is instantly set to 0, even though slide 1 is still visible.  Then slide 1's opacity get's set back to 1 before transitioning back to 0 when slide 2 gets displayed.
