### ISSUE TITLE
vertical autoscroll crashes on zoom in action on Chrome

### ISSUE THREAD

**Issue by NeilKwon** [FormidableLabs/nuka-carousel#560]
- What version of nuka-carousel are you using?
4.5.9 (latest)
- What version of React are you using?
16.8.6
- What browser are you using?
Chrome Version 75.0.3770.100 (Official Build) (64-bit)
- What machine are you on?
Macbook pro

### Describe the Problem
I wrote below code to auto play with vertical scrolling.

`<Carousel heightMode={'max'} vertical={true} autoplay={true} autoplayInterval={5000} withoutControls={true} wrapAround={true} initialSlideHeight={50} pauseOnHover={true}>
</Carousel>
`

But, once zoom in (command + '+') few steps on chrome browser, 
cpu usage hit over 100% and console said '[Violation] 'resize' ~~~' 

then I eliminated vertical={true} and works fine.

I guess this is caused by chrome bug ( not happens on the others)
It's possible to avoid this crash with few modification of codes.

Thanks

**Comment by sarmeyer** [comment]
@NeilKwon I tried to reproduce this with your configuration and was unable to. Do you know what percent zoomed in you were? I went up to 400% and didn't see an error from chrome. I'm on v75.0.3770.142

**Comment by NeilKwon** [comment]
It occurred since 110% zoom in.
then I updated chrome version to 
- Version 76.0.3809.87 (Official Build) (64-bit)
still hanging.

I think I need to provide snippet which I used 

```
// style scss
.list-notice { flex: 1; display: block; margin-left: 40px; height: 49px;
		li {max-height: 49px; min-height: 49px; line-height: 49px;}
		.notice-item { max-height: 49px; min-height: 49px; line-height: 49px;
			a { font-size: rem(14); color: #585859;
				time { display: none; }
			}
		}
	}

// code
genList = () => {
        return this.props.noticeList.map(notice => {
            return (
                <div className="notice-item" key={notice.id}>
                    <Link to={'/notice/detail/'}>~~~~</Link>
                </div>)
        })
    }

 render() {
        if (this.props.noticeList.size > 0) {
            return (
                <div className="list-notice">
                    <Carousel heightMode={'max'} vertical={true} autoplay={true} autoplayInterval={5000} withoutControls={true} wrapAround={true} initialSlideHeight={50} pauseOnHover={true}>
                        {this.genList()}
                    </Carousel>
                </div>
            )
        } else {
            return (<div className="list-notice"></div>)
        }
    }
```

**Comment by sarmeyer** [comment]
hi @NeilKwon thank you for sending that snippet over. After some more testing, I think the issue is the `font-size: rem(14)`. When I remove that property, the issue is resolved and I can zoom in as much as I want without Chrome freezing up. I am thinking this is a Chrome issue and not an issue with Nuka.
