### ISSUE TITLE
Animation mismatch when wrapping past the starting slide

### ISSUE THREAD

**Issue by dbangerter2** [FormidableLabs/nuka-carousel#563]
- What version of nuka-carousel are you using? 4.5.9
- What version of React are you using? 16.8.6
- What browser are you using? Version 76.0.3809.87 (Official Build) (64-bit)
- What machine are you on? Macbook Pro

Sandbox demo: https://codesandbox.io/s/sweet-khayyam-q3jv5
Same as the standard demo, just with the addition of `slidesToScroll={4}` and `wrapAround={true}`.

**Expected behavior:** [What you expect to happen]
1st click on "Next": Goes from Slide 1 to 5
2nd click on "Next": Goes from Slide 5 to either 1 or 3 with appropriate animation.

**Actual behavior:** [What actually happens]
1st click on "Next": Goes from Slide 1 to 5
2nd click on "Next": Animation goes from Slide 5 to 3, but upon animation completion gets immediately replaced by Slide 1.

**Comment by dbangerter2** [comment]
Also, there should only be 2 navigation dots at the bottom for this example instead of 3. Let me know if you'd like me to open a separate issue for that!

**Comment by sarmeyer** [comment]
Hi @dbangerter2 no need to open a second issue. this is a known problem. we're working on a fix, but if you'd like to play around with it and see if you can get the paging dots to calculate correctly, we're open to PRs!

**Comment by dbangerter2** [comment]
Thanks @sarmeyer! Not sure if/when I'll get to the paging dots issue, but I just put out a PR for the original wrap-around bug if you don't mind taking a look in your free time: https://github.com/FormidableLabs/nuka-carousel/pull/584
