### ISSUE TITLE
Pagination is broken when slidesToScroll value is one less than the slidesToShow value

### ISSUE THREAD

**Issue by Alexander-Hagemeier** [FormidableLabs/nuka-carousel#567]
# Bugs and Questions

### Describe Your Environment

- What version of nuka-carousel are you using?  - 4.5.9
- What version of React are you using? - 16.9.0
- What browser are you using?  - bug isn't related to browser
- What machine are you on? -  bug isn't related to machine

### Describe the Problem

When the value of `slidesToScroll` is one less than the value of `slidesToShow` the pagination won't work once you reach the last page.

What I mean with the pagination won't work: There is no active pagination dot anymore.

This behaviour can be reproduced here: https://codesandbox.io/s/fervent-breeze-yustc

**Comment by sarmeyer** [comment]
@Alexander-Hagemeier The codesandbox you sent over (thank you btw!) is on Nuka v4.4.1. After updating the nuka package, I no longer see the issue you describe. There is also a similar issue here #537 that addresses paging dot issues in general when slidesToShow and slidesToScroll don't match up. I'm not actively working on this issue atm, but let me know if you're still experiencing the issue when you upgrade, and if so reply to the other issue with your example so we can track all paging dot issues in the same place.

Thanks!
