### ISSUE TITLE
componentWillReceiveProps is not recommended for use

### ISSUE THREAD

**Issue by meeq** [FormidableLabs/nuka-carousel#568]
# Bugs and Questions

### Describe Your Environment

- *What version of nuka-carousel are you using?* **4.5.9**
- *What version of React are you using?* **16.9.0**
- *What browser are you using?* **This bug isn't related to browser**
- *What machine are you on?* **This bug isn't related to machine**

### Describe the Problem

There is a warning in the JavaScript Console when using nuka-carousel:

>Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.
>
>* Move data fetching code or side effects to componentDidUpdate.
>* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
>* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

*From https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html:*
>These lifecycle methods have often been misunderstood and subtly misused; furthermore, we anticipate that their potential misuse may be more problematic with async rendering. Because of this, we will be adding an “UNSAFE_” prefix to these lifecycles in an upcoming release. (Here, “unsafe” refers not to security but instead conveys that code using these lifecycles will be more likely to have bugs in future versions of React, especially once async rendering is enabled.)

If not addressed, this **will cause breakage** in React 17.x

### Additional Information

Related to https://github.com/FormidableLabs/nuka-carousel/issues/357

This appears to be a known TODO in the code:
https://github.com/FormidableLabs/nuka-carousel/blob/5fc99a95c4df9c4262c2d75c57e9a9b521679be4/src/index.js#L109-L111

**Comment by sarmeyer** [comment]
UNSAFE has been added in the latest release, we're still working on converting over to functional components and hooks as a whole 🙌
