### ISSUE TITLE
Infinite controlled slider

### ISSUE THREAD

**Issue by olup** [FormidableLabs/nuka-carousel#570]
Hi ! Couldn't find more data about this so I am posting a new issue :
Not sure if it is even implemented, but using a controlled slider (with `slideIndex` prop), the infinite mode provided by `wrapAround` doesn't seem to work. As a workaround I go back to first slide, but it's obviously not the same. Am I missing something ?
Cheers !

**Comment by sarmeyer** [comment]
Hey @olup, are you able to send a codesandbox or basic example of how you're using the Carousel so I can try to reproduce the issue you're seeing? Thank you!

**Comment by olup** [comment]
Sorry it has been months and I am not working on the team and project that was using this library anymore.

**Comment by sarmeyer** [comment]
Gotcha - well if you ever do need any help with Nuka again, reach out!
