### ISSUE TITLE
onDragStart is invoked prematurely when tapping on a slide

### ISSUE THREAD

**Issue by jflayhart** [FormidableLabs/nuka-carousel#579]
# Bugs and Questions

### Describe Your Environment

- Nuka 4.5.9
- React 16.8.6
- Chrome 76
- Mac OS

### Describe the Problem

`onDragStart` is firing when merely clicking (desktop) or touching (mobile) a slide item. This causes behavior I made within this callback to act prematurely (think, disable vertical scroll) when it should only happen during dragging/swiping behavior.

**Expected behavior:** I expected `onDragStart` to only happen when swiping begins, not a click.

**Actual behavior:** `onDragStart` happens any time a mouse down or touch event occurs on a slide item.

![actual](https://user-images.githubusercontent.com/6808172/64193604-b9178300-ce42-11e9-8de6-f4c8764ff128.gif)

**Comment by jflayhart** [comment]
@sarmeyer Could you please consider this issue and the potential fix (https://github.com/FormidableLabs/nuka-carousel/pull/585)? Trying to rush this out for shop.shipt.com 👍

**Comment by miguel-square** [comment]
> # Bugs and Questions
> ### Describe Your Environment
> * Nuka 4.5.9
> * React 16.8.6
> * Chrome 76
> * Mac OS
> 
> ### Describe the Problem
> `onDragStart` is firing when merely clicking (desktop) or touching (mobile) a slide item. This causes behavior I made within this callback to act prematurely (think, disable vertical scroll) when it should only happen during dragging/swiping behavior.
> 
> **Expected behavior:** I expected `onDragStart` to only happen when swiping begins, not a click.
> 
> **Actual behavior:** `onDragStart` happens any time a mouse down or touch event occurs on a slide item.
> 
> ![actual](https://user-images.githubusercontent.com/6808172/64193604-b9178300-ce42-11e9-8de6-f4c8764ff128.gif) [ ![actual](https://user-images.githubusercontent.com/6808172/64193604-b9178300-ce42-11e9-8de6-f4c8764ff128.gif) ](https://user-images.githubusercontent.com/6808172/64193604-b9178300-ce42-11e9-8de6-f4c8764ff128.gif) [ ](https://user-images.githubusercontent.com/6808172/64193604-b9178300-ce42-11e9-8de6-f4c8764ff128.gif)

Hi, I have this exact problem (That is very well describe). Need to click inside a slide to play a video but it starts dragging in the click before you start swiping or dragging. 

### Enviroment

- Nuka 7.0.0
- React 18.2.0
- Mac Os
