### ISSUE TITLE
Version 4.5.11 is unavailable

### ISSUE THREAD

**Issue by Fouaib** [FormidableLabs/nuka-carousel#581]
# Bugs and Questions

First , thank you for your great library , i love it :)

I am unable to fetch the latest version of nuka carrousel ( 4.5.11 ) from npm registry. 

### Prerequisites

`npm install nuka-carousel`
or
`npm install nuka-carousel@latest`

**Feel free to delete this section if you have checked off all of the following.**

- [X] I've searched open [issues](https://github.com/FormidableLabs/nuka-carousel/issues) to make sure I'm not opening a duplicate issue
- [X] I have read through the docs before asking a question
- [?] I am using the latest version of nuka-carousel

### Describe the Problem

When i am trying to fetch the latest version the following error occurs: 

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for nuka-carousel@4.5.11
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**Comment by jflayhart** [comment]
It has no been officially release per

**Comment by sarmeyer** [comment]
It's been officially released - I just tried to install it in a test project and had no issues.
![image](https://user-images.githubusercontent.com/18433259/64206167-eb32e000-ce56-11e9-89eb-8fafbd6f0e8e.png)

**Comment by sarmeyer** [comment]
You can try removing your package-lock.json and running `npm i`

**Comment by Fouaib** [comment]
My bad. it was a config issue on our proxy. 

i m sorry :) but thank you guys for your really quick answer ;)
