### ISSUE TITLE
Changing slideIndex too fast on controlled carousel does not update current slide properly

### ISSUE THREAD

**Issue by EricVanDerDijs** [FormidableLabs/nuka-carousel#586]
# Bugs and Questions

Bug

### Describe Your Environment

- What version of nuka-carousel are you using?
v4.5.11 -- the issue appears after version 4.4.2

- What version of React are you using?
v16.9.0
- What browser are you using?
Chrome

- What machine are you on?
Ubuntu 18.04

### Describe the Problem

**Expected behavior:**
- When controlling the carousel with NEXT and PREV buttons I expect the carousel to skip as many slides as the times I have clicked the buttons.

**Actual behavior:** [What actually happens]
- After clicking the buttons rapidly, only one slide is skiped, even when the parent state (which controls the slideIndex) points to a diferent slide.

[Example](https://codesandbox.io/s/quizzical-brahmagupta-6yhou)

### Additional Information
if you switch to v4.4.1 the carousel works as expected, which is the version of the repo Demo

**Comment by fr-nevin** [comment]
Any updates on this  @sarmeyer ?

**Comment by dmorda** [comment]
Yep, having the same issue here too. Would love to know how to fix this.
