### ISSUE TITLE
Slides to scroll calculation wrong when cellspacing and slides to show set explicitly

### ISSUE THREAD

**Issue by jeffersondarcy** [FormidableLabs/nuka-carousel#59]
here the formula:
`slidesToScroll = Math.floor(frameWidth / (slideWidth + this.props.cellSpacing));`
problem is when I set slidesToShow = 3 and cellSpacing=18  
slidesToScroll 'auto' should result 3 slides to scroll but the result is two
In my case correct framewidths would be `frameWidth = 3*slideWidth + 2*cellSpacing` bacause cellSpacing is only visible twice
The current calculation would be correct if there would be 3*cellSpacing visible

actually in case of slidesToShow set in props, slidesToScroll in case 'auto' should just be equal to slidesToShow

**Comment by sarmeyer** [comment]
I've verified this works in the most recent version 6.0. If there are still issues with your current implementation of the carousel, please open a new issue to let us know!
