### ISSUE TITLE
Slides are a map array of images fetched from remote API? #178

### ISSUE THREAD

**Issue by dominick-designs** [FormidableLabs/nuka-carousel#590]
Is it possible to have each slide dynamically loaded from a remote API?

Rather than using static images from a local array, is it possible to integrate the results of a fetch so that slides are automatically created based on a map iteration of a fetch response?

I hope it's ok if I post this question here.

**Comment by sarmeyer** [comment]
Hi @dominick-designs Yes this is possible. You can pull the images from where ever you'd like and map over them inside of the Carousel component. If you need more assistance, let me know!
