### ISSUE TITLE
Request: Height calculation based on container

### ISSUE THREAD

**Issue by derwaldgeist** [FormidableLabs/nuka-carousel#594]
First of all, thanks a lot for this carousel component. So far, it worked best compared to all others I have tried out.

I have a problem with setting the height for the carousel, though. In my use-case, the height should be determined by CSS, based on the height settings of the container surrounding the carousel.

My container's height is set to this: 

`height: calc(100vh - 200px - env(safe-area-inset-top));`

I ensure (via CSS) that all slides crop themselves automatically, so they fit into the aspect ratio, also by using CSS.

Unfortunately, the carousel seems to calculate its own height. In my case, this results in `height: 0` on `.slider-list` and `.slider-slide`. (Actually, I don't know why, because the slides all set themselves to 100%).

I was able to workaround this by setting `height: 100% !important` in the CSS, but that's a weird hack. It would be better if one could disable height calculations completely by passing a property to the carousel. Or, even better, let the user send something like `height="100%"` or `height="40vh"`.

Another approach would be to detect if the slides set their heights themselves via CSS and in this case disable the heights in the `style` property.

**Comment by ValGeorgiev** [comment]
This should be fixed in v5. Please raise another issue or reopen this if you are still reproducing it. Thanks
