### ISSUE TITLE
Request: Disable swiping if carousel contains only one slide

### ISSUE THREAD

**Issue by derwaldgeist** [FormidableLabs/nuka-carousel#595]
Currently, even if the carousel contains only one slide, it is draggable via mouse (showing empty space to the left and right). This is counter-intuitive. It would be better if swiping is disabled completely in this case.

I solved this by setting `disableEdgeSwiping`, but this also means that I cannot swipe past the last / first slides now, if the carousel contains more than one slide.

**Comment by sarmeyer** [comment]
I'll work on adding this to the component. In the meantime, you could dynamically set the `disableEdgeSwiping` prop to false if `slides.length > 0` and true if `!slides.length`

**Comment by sarmeyer** [comment]
It's been determined that we will not be adding this functionality to the carousel at this time because it can be easily handled from the FE consumer code.

**Comment by cabbage-cart** [comment]
> It's been determined that we will not be adding this functionality to the carousel at this time because it can be easily handled from the FE consumer code.

How? `disableEdgeSwiping` doesn't work for me. This is my config

```tsx
        withoutControls
        cellSpacing={8}
        cellAlign="center"
        slidesToShow={slidesToShow}
        slidesToScroll={1}
        disableEdgeSwiping
        slideIndex={initialSlideIndex}
```

I can still swipe to other slides
