### ISSUE TITLE
Next/Prev-Btn & PagingDots not configurable

### ISSUE THREAD

**Issue by wsdt** [FormidableLabs/nuka-carousel#607]
It's very easy to make them via props configurable. 

E.g. color of paging dots, next/prev btn text/icon, etc.

**Comment by sarmeyer** [comment]
Hi @wsdt! You can pass in whichever elements/components you'd like for the Next and Prev buttons, as well as the paging dots. Check out the `render*Controls` section of the README.md file.

**Comment by wsdt** [comment]
@sarmeyer I know, that's how we solved it. 
But if you just want to make a fine configuration, like changing the color of the paging dots, then creating a whole component/extending the old one is a bit overkill and decreases code quality/readability.

As this feature is really simple to implement via props, I would love to see it in a future release.

**Comment by wsdt** [comment]
@sarmeyer please reopen
