### ISSUE TITLE
Carousel not switching slides on emulated mobile devices in Chrome

### ISSUE THREAD

**Issue by alex-lechner** [FormidableLabs/nuka-carousel#610]
# Bugs and Questions

### Prerequisites

**Feel free to delete this section if you have checked off all of the following.**

- [x] I've searched open [issues](https://github.com/FormidableLabs/nuka-carousel/issues) to make sure I'm not opening a duplicate issue
- [x] I have read through the docs before asking a question
- [x] I am using the latest version of nuka-carousel

### Describe Your Environment

- What version of nuka-carousel are you using?
4.5.12

- What version of React are you using?
16.8.4

- What browser are you using?
Chorem 78.0.3904.97

- What machine are you on?
macOS 10.15.1

### Describe the Problem

It's easier to show us than tell us what's going wrong with your code. Because of this, we ask that you do one of three things to help us reproduce the bug:

1. Open Chrome Dev Tools and click on `Toggle Device Bar` to emulate a mobile device
2. In your React component add a button which changes the slide index
3. Click the button. 

**Expected behavior:** Carousel should render/swipe to the next slide.
**Actual behavior:** Carousel doesn't switch slides. Only if `swiping` is set to `false`

```javascript
import React, { Component } from "react";
import Carousel from "nuka-carousel";

export default class ExampleComponent extends Component {
  constructor(props, context) {
    super(props, context);
    this.scrollDown = this.scrollDown.bind(this);
    this.state = {
      slideIndex: 0
    };
    this.carouselSettings = {
      withoutControls: true,
      vertical: true,
      disableEdgeSwiping: true,
      // swiping: false, // if this is uncommented then the scrolling down functionality works
      speed: 500,
      afterSlide: slideIndex => {
        this.setState({ slideIndex });
      }
    };
  }

  scrollDown() {
    const { slideIndex } = this.state;
    if (slideIndex === 0) {
      this.setState({ slideIndex: 1 });
    }
  }

  render() {
    const { data } = this.props;
    const { slideIndex } = this.state;

    return (
      <Carousel slideIndex={slideIndex} {...this.carouselSettings}>
        <div className="section-one">
          <img src={data.imgSrc} alt={data.title} title={data.title} />
          <div className="heading-scroll-wrapper">
            <div className="heading-section">
              <h1>{data.title}</h1>
              <h2>{data.subtitle}</h2>
            </div>
            <button className="scroll-btn" onClick={this.scrollDown}>
              Scroll Down
            </button>
          </div>
        </div>
        <div className="section-two">Some content goes here</div>
      </Carousel>
    );
  }
}
```

**Comment by sarmeyer** [comment]
Is this not working in the Demo for you either? I am testing it with the built in demo in chrome emulator (the buttons to change the slideIndex already exist too) and I am not able to reproduce

**Comment by alex-lechner** [comment]
The strange thing is: It seems not to work if the button is inside the carousel. But if I set it outside then it works 🤔

**Comment by alex-lechner** [comment]
To give a little bit more context: I was using nuka inside a modal box from the Material UI library which dynamically injects the carousel into the DOM as soon as the modal get's visible. So `ExampleComponent` was always a child property from Material UI's `Dialog` component. Maybe that's what causes the problem on mobile devices. However, the controls from the nuka lib worked or if I set `swiping` to `false` then it worked too. And as I mentioned before it also worked if my custom button was placed outside of the `Carousel` component. Nevertheless, the requirement is to have the button inside `<div className="section-one">...</div>`.

**Comment by sarmeyer** [comment]
@alex-lechner I did a little more testing and can definitely reproduce what you're seeing, but I'm not sure why setting `slideIndex` outside of the Carousel works, but not when the function call comes from within the component. Interestingly enough, I can't get it to work with `swiping=false` either. So I'm curious how your example is working when that prop is set to false. 

I'll keep trying to figure something out, but I wanted to give you an update
