### ISSUE TITLE
Next/Prev-Btn & PagingDots not configurable 

### ISSUE THREAD

**Issue by wsdt** [FormidableLabs/nuka-carousel#611]
It's very easy to make them via props configurable.

E.g. color of paging dots, next/prev btn text/icon, etc.

But if you just want to make a fine configuration, like changing the color of the paging dots, then creating a whole component/extending the old one is a bit overkill and decreases code quality/readability.

As this feature is really simple to implement via props, I would love to see it in a future release.

See #607

**Comment by sarmeyer** [comment]
hi @wsdt Thanks for the suggestion! You're welcome to submit a PR - otherwise I will add it the triage of requested features
