### ISSUE TITLE
Lag while swiping on wrapAround

### ISSUE THREAD

**Issue by jibin2706** [FormidableLabs/nuka-carousel#612]
The issue only exist on wrapAround. Is there any workaround this?
https://codesandbox.io/s/nuka-carousel-bug-sx9j6

**Comment by artemtam** [comment]
Spent 2 hours trying to debug this. Realised that the code is shitty and unmaintainable, so you'd rather use another library. I'm angry and depressed. @sarmeyer you're responsible for my mental health now.

**Comment by artemtam** [comment]
😡

**Comment by Saikava** [comment]
There is open issue for this bug #494

**Comment by sarmeyer** [comment]
@jibin2706 thanks for sending a codesandbox! Unfortunately, I am not able to reproduce any issue in the sandbox. I know other folks have had issues with the "wraparound flash" so in favor of #494 I'll close this issue. You can follow along there if you're still having issues
