### ISSUE TITLE
How can I only show bottom paging dots in all control options?

### ISSUE THREAD

**Issue by sanishkr** [FormidableLabs/nuka-carousel#616]
```
      renderCenterLeftControls={false}
      renderCenterRightControls={false}
      renderTopCenterControls={()=> null}
      renderBottomCenterControls={() => {....}} //this part or any other way
```
Also, how can I style the paging dots differently?

**Comment by YLemelin09** [comment]
This is in jss but it works the same in css

`@global": {
      ".slider-control-topright": {
        height: "100%"
      },
      ".slider-control-topleft": {
        height: "100%"
      },
      ".paging-item button span": {  <------------ THIS
        backgroundColor: `${somecolor} !important`,
        width: "100px !important",
        height: "5px !important",
        borderRadius: "3px !important",
        "@media (max-width: 400px)": {
          width: "15px !important"
        },
        "@media (min-width: 401px) and (max-width: 959px)": {
          width: "25px !important"
        },
        "@media (min-width: 961px)": {
          width: "50px !important"
        }
      },
      ".paging-item.active button span": {
        backgroundColor: `${somecolor} !important`
      },`

So pretty much, you have to use the global tag and target .paging-item > button > span

**Comment by sarmeyer** [comment]
@sanishkr did this answer help you?

From the Readme: `The default props are set as renderCenterLeftControls for Previous button, renderCenterRightControls for the Next button and renderBottomCenterControls for the "Paging dots". To change the position or remove "Paging dots", the default positions need to be disabled by setting them to null.`

**Comment by sanishkr** [comment]
@sarmeyer, I didn't try this approach by @YLemelin09 as I needed a way to have inline css without overriding library's classname styles via an external css and I had already implemented custom `renderDotControls` component like the approach below.

```
const renderDotControls = ({
  cellAlign,
  cellSpacing,
  currentSlide,
  frameWidth,
  goToSlide,
  nextSlide,
  previousSlide,
  slideCount,
  slidesToScroll,
  slidesToShow,
  slideWidth,
  wrapAround
}) => {
  return (
    <div
      className="slider-control-bottomcenter"
      style={{
        position: 'absolute',
        bottom: '0px',
        left: '50%',
        transform: 'translateX(-50%)'
      }}
    >
      <ul
        style={{
          position: 'relative',
          margin: '0px',
          top: '12px',
          padding: '0px',
          display: 'flex'
        }}
      >
        {[...Array(slideCount)].map((sc, i) => (
          <li
            style={{ listStyleType: 'none', display: 'inline-block' }}
            key={i + 1}
          >
            <div
              style={{
                border: '1px #45689a solid',
                width: '10px',
                height: '4px',
                background: currentSlide === i ? '#45689a' : 'transparent',
                borderRadius: '2px',
                margin: '0 3px'
              }}
            ></div>
          </li>
        ))}
      </ul>
    </div>
  );
};

.
.
.

<Carousel
      // .... other props
      renderCenterLeftControls={() => null}
      renderCenterRightControls={() => null}
      renderTopCenterControls={() => null}
      renderBottomCenterControls={props => renderDotControls(props)}
>
      ....
</Carousel>
```

**Comment by sarmeyer** [comment]
@sanishkr Do you still need help accomplishing your desired styles or implementation? It seems you have a good example there!

**Comment by sanishkr** [comment]
Nope. I am closing it. 👍
