### ISSUE TITLE
heightMode 'max' is not working

### ISSUE THREAD

**Issue by povilaspin** [FormidableLabs/nuka-carousel#618]
v4.5.13

When heightMode is set to 'max'  ul.slider-list receives correct inline height property value, but all of the slides have height set to 'auto', which pretty much blows all the things away. I can't use min-height: 100% on the slider-slide anyways, because the container which is inside of the slider-slide can't inherit the height neither from slider-slide nor from slider-list

**Comment by TreTuna** [comment]
This is affecting me as well. I would love to see a little acknowledgment of this issue. It also relates to https://github.com/FormidableLabs/nuka-carousel/issues/594

I implemented a hacky workaround for now. I put a ref on the main `<Carousel>` component and then on my slide element I added `style={{ height: carouselRef.current?.state.slideHeight }}`

**Comment by sarmeyer** [comment]
@povilaspin thanks for submitting this request. I am not able to reproduce the issue. I created this demo here (heightMode='max' is the default heightMode configuration for the Carousel). https://codesandbox.io/s/sad-solomon-gwd10

Do you have a codesandbox of reproducible steps for me to test it out on? Thanks!

**Comment by TreTuna** [comment]
I will see if I can make a Code Sandbox with a reproducible example of what I'm experiencing right this moment.

**Comment by TreTuna** [comment]
Here's where I have the issue. We are using the carousel for not just images: https://codesandbox.io/s/recursing-hill-ek50k

**Comment by sarmeyer** [comment]
That codesandbox was using an old version in which heightMode 'max' was broken. I updated Nuka and it works. https://codesandbox.io/s/long-hooks-doqph

**Comment by TreTuna** [comment]
First off, thanks for you help! I still have the same issue with your new sandbox, plus another oddity on load. This is happening in my app at work as well with the newest version as I just installed it yesterday.

![nuka-carousel-issue](https://user-images.githubusercontent.com/16496746/70650615-49185600-1c04-11ea-81c8-170d08feec73.gif)

**Comment by povilaspin** [comment]
@sarmeyer the point is that if i have heightMode set to 'max', I'm not able to equalize heights of the slides, because .slider-slide has height: auto.

**Comment by sarmeyer** [comment]
I see the issue - I'm wondering if this is only an issue for non-image slides? Is there a case when we would want image slides to also not have a `height: auto`? I found a solution, although I feel it's also kind of hacky and I want to make sure it's more bullet proof and covers edge cases

**Comment by TreTuna** [comment]
We actually aren't using this anywhere with just images so I'm not positive. If anything on our carousels, the images are at least wrapped in an `<a>` tag and they have overlays on them.
