### ISSUE TITLE
first and last slide are stacked

### ISSUE THREAD

**Issue by halorium** [FormidableLabs/nuka-carousel#62]
Forgive me if this is a dumb question but following the instructions / using the demo code, it displays the first and last slide stacked on top of each other rather than only displaying the first slide.

I can't seem to find what is missing to fix this.

Thanks.

UPDATE:

I just realized I had a 1px border on all items to help with layout development and once I removed that then it displayed appropriately.

So my next question is: Shouldn't the size calculation take into consideration any styling being applied?

**Comment by sarmeyer** [comment]
No longer an issue in 4.5.0
