### ISSUE TITLE
Using tab to scroll pushes the slider to the left

### ISSUE THREAD

**Issue by YLemelin09** [FormidableLabs/nuka-carousel#622]
# Bugs and Questions

### Prerequisites

**Feel free to delete this section if you have checked off all of the following.**

- [x] I've searched open [issues](https://github.com/FormidableLabs/nuka-carousel/issues) to make sure I'm not opening a duplicate issue
- [x] I have read through the docs before asking a question
- [x] I am using the latest version of nuka-carousel

### Describe Your Environment

- What version of nuka-carousel are you using?  4.5.13
- What version of React are you using? 16.9.0
- What browser are you using? Chrome
- What machine are you on? Macbook pro 15

### Describe the Problem

I cannot share my code but I dont think you will need it to understand the problem.

With a carousel showing multiple items, i use tab to check the accessibility in my page. It tabs on all slides and when it passes from the last visible slide to the ones that are hidden in the overflow, the .slider div is pushed on the left to show the hidden slides thus pushing the centerRightControl in the middle of the page where the last shown slide should be.

**Expected behavior:** Either when i tab the whole carousel is selected and the next tab skips to the DOM element after the carousel or I can tab only on the visible slides

**Actual behavior:** what i said earlier

### Additional Information

Expected:

![carrousel_working_1](https://user-images.githubusercontent.com/18009224/69755725-e06eab00-1126-11ea-8e78-1d901d090935.jpg)

Reality: 

![carrousel_notworking_2](https://user-images.githubusercontent.com/18009224/69755740-e9f81300-1126-11ea-8df3-4420552c5baa.jpg)

**Comment by sarmeyer** [comment]
reopened due to reverting fix in #643
