### ISSUE TITLE
Carousel keyboard controls trigger on all carousels

### ISSUE THREAD

**Issue by YLemelin09** [FormidableLabs/nuka-carousel#623]
# Bugs and Questions

**Expected behavior:** Press left or right when the focus is on a certain carousel and only this carousel behaves to the command
**Actual behavior:** All the carousels in the page scroll together

### Additional Information
I have a netflix like page with multiple carousels on the same page. If I tab to focus in a carousel and use the keyboard controls, all the carousels get the scroll trigger instead of just the one I'm focused in.

Maybe carousels could have a key prop and make sure to have a tab index just on the slider div and not the children.

**Comment by mtsandeep** [comment]
With the current implementation, the keyboard navigations are not checking if the carousel is in focus or not. I think we need to add that functionality to get this issue fixed
