### ISSUE TITLE
Video tag controls aren't clickable in MS Edge browser

### ISSUE THREAD

**Issue by andriy-onyshchenko** [FormidableLabs/nuka-carousel#631]
**Describe Your Environment**

- What version of nuka-carousel are you using?
4.5.8
- What version of React are you using?
16.8.6
- What browser are you using?
MS Edge
- What machine are you on?
Windows
### Describe the Problem
1. Create a slider with two slides. One of them must be video slide with HTML5 video tag;
2. Open slider in MS Edge browser;
3. Check video controls and try to click on them
4. Controls are not clickable.

**Comment by fritz-c** [comment]
I could not reproduce this on macOS+Edge with the latest version of nuka-carousel (v5.2.0).
demo: https://codesandbox.io/s/nuka-carousel-example-forked-10ep9v?file=/src/App.js
