### ISSUE TITLE
Vertical photo with horizontal

### ISSUE THREAD

**Issue by MarinaaaniraM** [FormidableLabs/nuka-carousel#64]
I want to show other different images. Vertical and horizontal together. I see free space after vertical photo.  It is possible to remove this space?

I tried to write `slideWidth="auto"`, but see, that `<li>` have width: 0 after this...

**Comment by ashika01** [comment]
Closing the issue because it has been fixed in a newer version. You should be able to achieve this now with `heightMode` set to `current`.
Please reopen if you still experience this issue with the latest stable version. Thank you.
