### ISSUE TITLE
ReferenceError: Element is not defined

### ISSUE THREAD

**Issue by vince1995** [FormidableLabs/nuka-carousel#658]
The newest version 4.6.2 includes an error referring `wicg-inert`: 

![image](https://user-images.githubusercontent.com/15120985/73442339-f3833e80-4354-11ea-9351-4b65caa6db06.png)

#622 #642 #643

**Comment by mrassili** [comment]
Same issue :(
cc @sarmeyer
sounds like a dependency of `nuka-carousel` caused the issue

**Comment by vince1995** [comment]
Yeah, it's `wicg-inert` like I wrote in the opening post.

**Comment by L2k13** [comment]
+1

**Comment by Maskyss** [comment]
+1

**Comment by red1hr** [comment]
+1

**Comment by JoviDeCroock** [comment]
Hey,

Are you getting this error when running in a Node environment, like SSR? That would clarify Element not being defined.

**Comment by lucasgerard** [comment]
Hey @JoviDeCroock we're facing the same issue running with SSR indeed (Next)

**Comment by JoviDeCroock** [comment]
It's possible that we'll need to fix this upstream by adding `Element = typeof Element === 'undefined' ? {} : Element;`

**Comment by matthaywardwebdesign** [comment]
Experienced the same issue with SSR with Next. Have raised a PR to lazy load the polyfill only in environments that have Element present.

**Comment by vamshi2000** [comment]
Still facing this issue with Node ssr 
![image](https://user-images.githubusercontent.com/25465644/73556008-3a843900-4414-11ea-81e0-c6550ee7f88d.png)

**Comment by azamatsmith** [comment]
+1

**Comment by yangxuanxing** [comment]
+1

**Comment by ngochieuvnu** [comment]
i still facing this issue when deploy in Azure devops, but work well on local

![error](https://user-images.githubusercontent.com/45206653/73738324-df857580-4776-11ea-98ad-bb559e466ca2.png)

**Comment by vince1995** [comment]
@ngochieuvnu even if you delete `node_modules` and rerun `npm install`?

**Comment by JoviDeCroock** [comment]
The PR on `wicg-inert` is open https://github.com/WICG/inert/pull/144, you can revert to previous version for the time being.

**Comment by ngochieuvnu** [comment]
> @ngochieuvnu even if you delete `node_modules` and rerun `npm install`?

yes, i tried to do that in local

**Comment by South-Paw** [comment]
Issue breaks Gatsby builds as well. Just roll back to `4.6.0` until https://github.com/WICG/inert/pull/144 is merged hopefully soon 😟

Side note to the 5 people that replied with `+1` comments - a thumbs up on the issue usually suffices and reduces the spam in the comments for the maintainers 😄

**Comment by sarmeyer** [comment]
Seems like we're close to getting WICG/inert#144 merged - I'll keep an eye on it today

**Comment by YLemelin09** [comment]
+1

**Comment by YLemelin09** [comment]
Will this fix the issue I'm having here? https://github.com/FormidableLabs/nuka-carousel/issues/622

**Comment by sarmeyer** [comment]
The fix for #622 introduced this issue

**Comment by sarmeyer** [comment]
Because I'm not sure how long the wicg-inert PR will take to get merged and released, and we have some other fixes in 4.6.2 that I think are valuable to get out, I'm reverting the commit that introduced wicg-inert for now. There is also a bug in how we are applying `inert` to elements (#664) that we would need to spend more time on to figure out the logic. I'll keep this issue open to track the issues/convo around wicg-inert SSR issue

**Comment by fe-linjin** [comment]
+1

**Comment by sarmeyer** [comment]
I believe this will be no longer be an issue with the new version of wicg-inert which includes the fix for WICG/inert#144. The update to Nuka was merged in PR #667 and will be released today
