### ISSUE TITLE
Change color of dots?

### ISSUE THREAD

**Issue by kid-three** [FormidableLabs/nuka-carousel#661]
Is there a way to change the default color of the dots. Like in the demo page, they are red.

Thanks

**Comment by frnk94** [comment]
This should work haven't tested it tho. 
```ts
<Carousel
  defaultControlsConfig={{
    pagingDotsStyle: {
      color: "red"
    }
  }}
/>
```

you can also target container or component with className
```ts
defaultControlsConfig={
  pagingDotsContainerClassName: style.dotContainer
  pagingDotsClassName: style.dot
}
```

**Comment by riceboyler** [comment]
In case somebody else finds this issue, the correct answer is to use `fill` rather than `color`. Like below:

```javascript
<Carousel
  defaultControlsConfig={{
    pagingDotsStyle: {
      fill: "red"
    }
  }}
/>
```

**Comment by JavierCanoy** [comment]
thanks ! @riceboyler
