### ISSUE TITLE
Slides become inactive when using cellSpacing

### ISSUE THREAD

**Issue by szujak** [FormidableLabs/nuka-carousel#664]
First of all I really like this project. It is very useful :)

# Bugs and Questions

### Prerequisites
- [x] I've searched open [issues](https://github.com/FormidableLabs/nuka-carousel/issues) to make sure I'm not opening a duplicate issue
- [x] I have read through the docs before asking a question
- [x] I am using the latest version of nuka-carousel

### Describe Your Environment

- What version of nuka-carousel are you using?
`v4.6.2`
- What version of React are you using?
`16.12.0`
- What browser are you using?
`chrome`
- What machine are you on?
`mac`

### Describe the Problem

After introduce `inert` attribute in `v4.6.2` when I set `cellSpacing` option then after changing slide I can't interact with links, buttons, etc. the `inert` is set wrongly on active slide

1. In `demo/app.js` add `cellSpacing={1}` to `Carousel` props
2. Run demo
3. Swipe slide
4. You can't click on link anymore

**Expected behavior:** After setting up `cellSpacing` option to something different than 0 it is possible to interact with slides after first swipe
**Actual behavior:** After setting up `cellSpacing` option to something different than 0 it is imposible to interact with slides after first swipe

**Comment by sarmeyer** [comment]
fixed in 4.6.3
