### ISSUE TITLE
How is accessibility supported with screen readers?

### ISSUE THREAD

**Issue by ghostaki** [FormidableLabs/nuka-carousel#681]
# Bugs and Questions

### Prerequisites

**Feel free to delete this section if you have checked off all of the following.**

- [x] I've searched open [issues](https://github.com/FormidableLabs/nuka-carousel/issues) to make sure I'm not opening a duplicate issue
- [x] I have read through the docs before asking a question
- [x] I am using the latest version of nuka-carousel

### Describe Your Environment

- What version of nuka-carousel are you using? **4.6.6**
- What version of React are you using? **16.11.0**
- What browser are you using? **Chrome latest**
- What machine are you on? **Mac/Win7**

### Describe the Problem

Apologies if this is more a question / how to, rather than an actual issue.

What I'm trying to figure out is how to make the carousel work nicely with screen readers and NVDA in particular.

**My scenario:** I have a carousel with multiple slides (say 4 slides, as an example)

**Expected behavior:** When the carousel is focused, the screen reader only reads out the visible slide. The screen reader will read out subsequent slides as and when they appear on the screen, after either user interaction or autoplay.

**Actual behavior:** When the carousel is focused, the screen reader reads out all the slides in one go, the one after the other (regardless of which slide is actually displayed). When a slide changes, either though user interaction or autoplay, the screen reader remains silent.

### Additional Information

Having inspected the DOM, it looks like all four slides are present in DOM when the carousel loads, regardless of which one is currently visible. So, technically the screen reader treats the whole slide set as a `<ul/>` with four <`li/>` children and reads the whole thing out. There seem to be no `aria-*` or `role` attributes that will help the reader know which slide is currently visible and which is not.

Any ideas on how the desired behavior can be achieved will be greatly appreciated! Hopefully I'm just missing something in the way I'm using nuka-carousel :) 

### Update after a bit of investigation 
I had a look at the code and realised the following:
- In `src/index` the `addAccessibility` method from `./utilities/bootstrapping-utilities` is imported. However, this method does nothing meaningful, as both routes of the conditional within do the same (no)thing. It looks like the `addAccessibility` method from `./utilities/utilities` should have been imported instead?
- Even so, this would only apply when more than ones slides are being shown at a time with `slidesToShoe` variable
- Again, even if we overcome the previous obstacle, the actual `aria-hidden` attribute is eventually being ignored by the renderer of the transition e.g. `scroll-transition`

So I think that the current version of the carousel is not really supporting screen readers with the a`aria-hidden` attribute. Whether this is intentional or I not I cannot say (maybe people prefer to have the screen reader read out all slides, even the hidden ones

**Comment by hcientist** [comment]
Seems like at the very least the `role` if not also the `aria-roledescription` should be set [[1](https://www.w3.org/TR/wai-aria-practices-1.1/#carousel)]?

**Comment by LorepRocks** [comment]
Any updates on this? I'm experiencing some issues with the screen reader

**Comment by XavierMeunier** [comment]
A start could be to implement `aria-selected="true"` to button under the `active` li.

**Comment by sarmeyer** [comment]
Hi all - I am opening a PR with some updates to hopefully improve accessibility of Nuka. I tested with the built in macOS screen reader, but of course I would love feedback from others.

Have you tried using the `renderAnnounceSlideMessage` prop to pass in a custom screen reader message? A default one is provided, but you can also pass in your own. 

Check out the PR here: https://github.com/FormidableLabs/nuka-carousel/pull/802
