### ISSUE TITLE
Center mode with cell align center and even slides to show

### ISSUE THREAD

**Issue by marconucara** [FormidableLabs/nuka-carousel#682]
# Center mode with cell align center and even slides to show

### Describe Your Environment

Latest versions of react and nuka, installed yesterday.

### Describe the Problem

If I use cell align center and 2 slides to show and I increase slideToShow value to 2.2 for see a bit of prev and next slides I actually see 1 full slide at center + 0.6 of prev and 0.6 of next. I would see instead 2 full slide and 0.1 of prev and 0.1 of next. Same problem with 4 slides and I suppose any even values.

Any way to achieve what I need?

**Comment by sarmeyer** [comment]
Hi @marconucara I don't believe there is a way to do this currently with the way we are calculating and rendering the slides when `cellAlign = center`. I'll keep playing around with it and see if I can come up with a way to make this possible.
