### ISSUE TITLE
getControlsContainerStyles type not released in 4.6.6

### ISSUE THREAD

**Issue by kasperekt** [FormidableLabs/nuka-carousel#685]
# Bugs and Questions

### Describe Your Environment

- What version of nuka-carousel are you using?
- What version of React are you using?
- What browser are you using?
- What machine are you on?

I'm using `nuka-carousel@4.6.6`, `react@16.12.0`. Browser -- not relevant. Linux -- Ubuntu 18.04.

### Describe the Problem

I've seen that there was a typo in index.d.ts file for `getControlsContainerStyles` prop. Latest version of this package (4.6.6) has still wrong type defined.

**Expected behavior:** [What you expect to happen]

No error

**Actual behavior:** [What actually happens]

TypeScript error.

**Comment by sarmeyer** [comment]
Fixed in #677
