### ISSUE TITLE
Is the plugin IE11 supported? 

### ISSUE THREAD

**Issue by fr-nevin** [FormidableLabs/nuka-carousel#686]
This is more of a question, Is the plugin IE 11 supported? 
Am currently working on a mac, and I wanted to test it, but my Virtual network seems quite slow for my usage of this plugin on IE11. 

I tried to check the sandbox link, but it doesn't open in IE11. 

I tried setting it up on my personal PC: 
Windows 10, IE 11.

**Comment by fr-nevin** [comment]
![IE 11 Nuka Carousel](https://user-images.githubusercontent.com/45579756/79538863-215c6180-80c0-11ea-97fc-cc83186e157f.PNG)

Seems it's not? Am I doing something wrong?

**Comment by amigolargo** [comment]
We are also experiencing this  – in 4.7.0, the demo is giving a syntax error:
<img width="553" alt="Screenshot 2020-06-05 at 16 01 03" src="https://user-images.githubusercontent.com/356134/83885033-1760f180-a746-11ea-8985-aaca0659da63.png">

**Comment by amigolargo** [comment]
Seems related to https://github.com/FormidableLabs/nuka-carousel/issues/696

**Comment by JoviDeCroock** [comment]
We're tracking this in #696 could you confirm that this is related to the `const` as well, this can be done by following the source-map.

I made an upstream issue report to `wicg-inert` to fix this.

**Comment by amigolargo** [comment]
I can confirm this was fixed in our application by transpiling the `wicg-inert` module as suggested in #696

**Comment by sarmeyer** [comment]
fixed in v4.7.3
