### ISSUE TITLE
Disabling dragging also disables swiping for Safari Responsive Design mode

### ISSUE THREAD

**Issue by StevieJayCee** [FormidableLabs/nuka-carousel#689]
# Bugs and Questions

### Describe Your Environment

- What version of nuka-carousel are you using?
4.6.7
- What version of React are you using?
16.12.0
- What browser are you using?
Safari Responsive Design Mode
- What machine are you on?
Mac OSX Catalina

### Describe the Problem

Disabling `dragging` only disables dragging for mouse interaction on Chrome, Firefox and Edge. Swiping still works for mobile views with these browsers

Disabling `dragging` on Safari also appears to disable `swiping` in Responsive Design mode. Is there something I am missing?

**Expected behavior:** Swiping should be enabled, but dragging should be disabled.
**Actual behavior:** Both are disabled

I hacked the demo playground to replicate this: https://codesandbox.io/s/recursing-ritchie-k1llh?file=/src/index.js

### Additional Information
Swiping actually appears to work on an old iPhone device I have. It only appears to be safari browser.

**Comment by sarmeyer** [comment]
@StevieJayCee thanks for submitting this bug report and including a demo - I'll have a look into it

**Comment by fritz-c** [comment]
This was a bug. It will be fixed in the next version release (right now it's v5.2.0, the next will probably be v5.3.0).
Demo of the fixed carousel: https://nuka-carousel-next.vercel.app/?slides=4&params=%7B%22dragging%22:false%7D

**Comment by fritz-c** [comment]
This is now fixed in v5.3.0
