### ISSUE TITLE
Feature request: Add active class name to the current slide.

### ISSUE THREAD

**Issue by mrsamse** [FormidableLabs/nuka-carousel#691]
Currently there is only a "slide-visible" class for all the slides, that are visible to the user. In my project I use the "slidesToShow " option. With that option, multiple slides are shown, which works fine. What I want now is, that I want to give the active slide in the middle a different styling. So I would prefer, to have an active class for that. My workaround for now is, to set the className with the the "innerRef" prop and listen on slide changes with the "beforeSlide" event. It's a bit messy, so it would be really nice to have this feature.

**Comment by sarmeyer** [comment]
Hi @mrsamse - thanks for submitting this request! I feel this would be a beneficial addition to the Carousel. I'll look into how we can do that!

**Comment by sarmeyer** [comment]
@mrsamse I'm assuming based on your comment that you're showing 3 slides and would like the middle one to be considered "active". Is that correct?

**Comment by mrsamse** [comment]
@sarmeyer Yeah that is correct.

**Comment by phurst-gh** [comment]
This would be really helpful. The documentation claims this already exists, although I can't seem to find it in my uses:

> The className slide-current is added to the currently "active" slide.

**Comment by sarmeyer** [comment]
@phurst-gh which version are you running? Do you have an example demo of your use case? the class can be seen here in the Nuka demo: 
![image](https://user-images.githubusercontent.com/18433259/90415022-c2a6f480-e06d-11ea-828c-fed76799107b.png)

**Comment by PHurst1** [comment]
My apologies, I hadn't had time to come back and edit this post yet. You are right though, I was 1 minor version behind.
