### ISSUE TITLE
Remove blue border from slide

### ISSUE THREAD

**Issue by YouKnowEno** [FormidableLabs/nuka-carousel#693]
Hello! I've been looking all around for how to delete the blue border from a slide.

![blueborder](https://user-images.githubusercontent.com/56950897/82268713-a6ca7e80-99aa-11ea-9ecb-18031173a79e.PNG)

I've tried using JSS, CSS, and inline styling to set 
'outline: none'
'boxShadow: none'
'border: none'

No dice. Any suggestions? Thanks in advance!

**Comment by YouKnowEno** [comment]
Hello! I do not have a codesandbox. Sorry, will do next time I ask a question. 

You are correct, it is when I am clicking on a slide. I was able to fix it by forking the repo and adding the following line of code to nuka-carousel/lib/transitions/scroll-transition.js/line 133:
outline: 'none'.

Here's what the code looks like now:
{
    key: "getSlideStyles",
    value: function getSlideStyles(index, positionValue) {
      var targetPosition = this.getSlideTargetPosition(index, positionValue);
      var transformScale = this.props.animation === 'zoom' && this.props.currentSlide !== index ? Math.max(Math.min(this.props.zoomScale, MAX_ZOOM_SCALE), MIN_ZOOM_SCALE) : 1.0;
      return {
        outline: 'none',
        boxSizing: 'border-box',
        display: this.props.vertical ? 'block' : 'inline-block',
        height: (0, _styleUtilities.getSlideHeight)(this.props),
        left: this.props.vertical ? 0 : targetPosition,
        listStyleType: 'none',
        marginBottom: this.props.vertical ? this.props.cellSpacing / 2 : 'auto',
        marginLeft: this.props.vertical ? 'auto' : this.props.cellSpacing / 2,
        marginRight: this.props.vertical ? 'auto' : this.props.cellSpacing / 2,
        marginTop: this.props.vertical ? this.props.cellSpacing / 2 : 'auto',
        MozBoxSizing: 'border-box',
        position: 'absolute',
        top: this.props.vertical ? targetPosition : 0,
        transform: "scale(".concat(transformScale, ")"),
        transition: 'transform .4s linear',
        verticalAlign: 'top',
        width: this.props.vertical ? '100%' : this.props.slideWidth
      };
    }

Sorry. I know my response is non-standard. This is the first time I've asked a question on GitHub before. I'll be more thorough next time. Merci.

**Comment by sarmeyer** [comment]
@YouKnowEno No worries at all! Thank you for sending over that info. Let me see if there might be an easier way for you to override that style so you don't have to rely on a forked version

**Comment by sarmeyer** [comment]
The blue outline you see is the native browser focus behavior for the slide. If you want to remove it, you can target it in css like so: 
```
  .slider-slide {
    :focus {outline: none;}
  }
```

However, the native behavior is usually beneficial for accessibility concerns, so I suggest still having some sort of focus state on the element. This article is a little old at this point, but the message is still valid: https://a11yproject.com/posts/never-remove-css-outlines/

**Comment by cihanbas** [comment]
I have the same problem, but i solved with this code 
```
//all.css
* {
  outline: none;
}
*:focus {
  outline: none; 
}
```
