### ISSUE TITLE
`wicg-inert` contain es6 const in src/index.js

### ISSUE THREAD

**Issue by doxiaodong** [FormidableLabs/nuka-carousel#696]
# Bugs and Questions

### Prerequisites

**Feel free to delete this section if you have checked off all of the following.**

- [ ] I've searched open [issues](https://github.com/FormidableLabs/nuka-carousel/issues) to make sure I'm not opening a duplicate issue
- [ ] I have read through the docs before asking a question
- [x] I am using the latest version of nuka-carousel

### Describe Your Environment

- What version of nuka-carousel are you using?
4.7.0
- What version of React are you using?
- What browser are you using?
- What machine are you on?

### Describe the Problem
My dist code has es6 code which may cause error in some old broswer

![image](https://user-images.githubusercontent.com/6927481/82652675-92a7ab00-9c50-11ea-9c53-080f805275e1.png)

see https://github.com/WICG/inert/issues/153

**Comment by doxiaodong** [comment]
How about this

**Comment by rmillener** [comment]
Just for clarity this breaks IE11 compatibility, even with Polyfills.

**Comment by tomsarduy** [comment]
Any plan to fix this or workaround?

**Comment by JoviDeCroock** [comment]
You can temporarily work around this by including `/node_modules/wicg-inert` in your babel-transformations, the fix for this will need to happen upstream in [wicg-inert](https://github.com/WICG/inert)

**Comment by goatandsheep** [comment]
@doxiaodong can we close this?

**Comment by andieromero** [comment]
> You can temporarily work around this by including `/node_modules/wicg-inert` in your babel-transformations, the permanent fix for this will need to happen upstream in [wicg-inert](https://github.com/WICG/inert). Made an issue on their repo to track the upstream fix.

Hi thanks for the workaround - how do you add `/node_modules/wicg-inert` in your babel-transformations? @JoviDeCroock

**Comment by andieromero** [comment]
Thanks! We have several apps that would require a workaround unfortunately. I see you have https://github.com/WICG/inert/pull/157 approved - would this fix the issue?

**Comment by JoviDeCroock** [comment]
It would yes

**Comment by aaronpflower** [comment]
>  I see you have WICG/inert#157 approved - would this fix the issue?

Is there a timeline on when this update would be released?

**Comment by MForMarlon** [comment]
Downgrading to v4.6.7 is another workaround solution, if you don't need any of the v4.7 features.

**Comment by goatandsheep** [comment]
Good news: the fix for inert has been merged and will be released soon!

**Comment by sarmeyer** [comment]
As far as I can tell, Jovi's PR was merged and released in 3.1.0 of WICG/inert - upgrading to that version should fix this issue
