### ISSUE TITLE
set autoplay and autoplayReverse to true, not make circular effect

### ISSUE THREAD

**Issue by sekonyong** [FormidableLabs/nuka-carousel#701]
nuka-carousel : 4.6.0
browser : google chrome
I tried to set this two props autoplay and autoplayReverse to true to have circular effect according to this explanation:
Only meaningful when autoplay is already true. When autoplayReverse is also true, autorotation cycles through slides indexes from high to low.
but what I got is only the reverse is running.
I tried in codesandbox and adding autoplay={true} autoplayReverse={true} and got same result.
I tried to update nuka-carousel library to latest (4.7.0) and still got the same result.

did I do it wrong?

**Comment by sarmeyer** [comment]
Hi @sekonyong - thanks for submitting this question! I see how these props might be confusing. `autoplay` initially determines if the carousel will scroll through slides automatically, then you can further configure this feature by setting `autoplayReverse` to make the slides run "backwards". So the behavior you see is the intended behavior of these two props. 

When you say you'd like to have a "circular" effect, what do you mean? If I am assuming correctly, I think you might want to set `wraparound=true` - this, in addition to the `autoplay` props, will keep the carousel cycling through the slides.

**Comment by sarmeyer** [comment]
Hey @sekonyong I'm going to close this due to inactivity. If you still have a question regarding these props or other concerns, please reopen with more details about what you expect. Thanks!

**Comment by musindo** [comment]
Hi @sekonyong i have 4 images in my Carousel, when the slider reaches the last image it stops. I tried using use autoplay and wraparound but still same behaviour

**Comment by ValGeorgiev** [comment]
Hey @musindo. Can you give me more details, like which version of nuka-carousel you are using. What properties you are passing and etc. Sandbox or github repo will do the job as well.

**Comment by musindo** [comment]
hi @ValGeorgiev 

Unfortunately i am still running it on my local machine. I hope the following will be helpful.

`<Carousel
      autoplayInterval={3000}
      autoplay={true}
    wraparound={true}
>`
- nuka-carousel: 4.8.4
- react: 17.0.2
- Chrome

**Comment by musindo** [comment]
@ValGeorgiev that was it thank you so much i had spend hours
