### ISSUE TITLE
Feature request: Add onSlideClick event handler

### ISSUE THREAD

**Issue by mrsamse** [FormidableLabs/nuka-carousel#702]
I would like to have an onSlideClick event handler, so I could set the slider index to that respective slide. Or is there an other way to do it? The dragging works fine, but some of my clients click on the slides, and nothing happens for them.

**Comment by sarmeyer** [comment]
Hi @mrsamse - thanks for submitting this question. What behavior are you (or your clients) expecting when the slide is clicked on? What's the general configuration of your carousel and props? If you have a demo or codesandbox I could take a look at, that would be great, too.

**Comment by mrsamse** [comment]
Hi @sarmeyer! 

Here is my codesandbox for the current case I have: https://codesandbox.io/s/naughty-mclaren-pmeq2
Some of my clients for example didn't swipe the slider but clicked on the number 4 or 2 and then nothing happens. For my case I solved it, by adding a "onClick" listener on all the divs inside the slides, and adding pointer events again to the slides with css.

**Comment by ValGeorgiev** [comment]
Hey @mrsamse, thanks for raising this with us and sorry that it took us so long to get back to you. We released v5 of nuka-carousel and now you can achieve this easily with just onClick on slides, this is a rare case, so if there is a big need for such feature we can add a custom event. I created a sandbox with an example, [here is a link](https://codesandbox.io/s/jovial-pike-6mip4c?file=/src/App.js). I will close this for now, please let me know if someone else expect such feature.
