### ISSUE TITLE
Importing dynamic array of images to carousel

### ISSUE THREAD

**Issue by rockdoctor79** [FormidableLabs/nuka-carousel#703]
I am trying to add a dynamic array of images to the carousel but I am rather new to react and unsure of how to go about doing this. Whenever I try to put a loop to parse through the array inside of the carousel tags it crashes. I was wondering if anyone could help me with this issue or by chance had an example of how to go about doing it. Thank you

**Comment by sarmeyer** [comment]
Hi @rockdoctor79 - Can you provide a bit more information about what you're trying to do? How are your images dynamic? This should definitely be possible, so I want to get more info so I can help you! If you have a codesandbox or demo of what you're trying to do, that would be great, too.

**Comment by sarmeyer** [comment]
Hey @rockdoctor79 I'm going to close this issue since no demo or code sample was provided. The Nuka demo has an example of an array of "slides" mapped over to populate the images, if you'd like to take a look there.
