### ISSUE TITLE
Carousel sliding not working properly for odd no. of slides

### ISSUE THREAD

**Issue by NishaUttawani** [FormidableLabs/nuka-carousel#710]
# Carousel sliding not working properly for odd no. of slides

### Describe Your Environment

- What version of nuka-carousel are you using? : 4.6.4
- What version of React are you using? 16.13
- What browser are you using? Chrome
- What machine are you on? : Macbook

### Describe the Problem
Facing issue while scrolling with odd of no. of total slides
total slides = 3
slidesToShow = 2
slidesToScroll = 2

While scrolling from the initial slide:  1st slide (0 indexes) instead of sliding to the last slide and display only last slide(3rd slide), it displays both 2nd and 3rd slide

**Expected behavior**: it should slide by 2 places and display only the last slide.
**Actual behavior**: it slides by 1 position only displaying both 2nd and 3rd slide.

### Additional Information
Not sure if this is an issue with nuka-carousel.
But any help would be appreciated.

**Comment by sarmeyer** [comment]
Hi @NishaUttawani Yes this is expected behavior - otherwise under these conditions, you would get an "empty" slide shown as the last slide, so when there is an odd number of slides and an even number of slidesToShow and slidesToScroll we don't show this "empty" slide at the end.
