### ISSUE TITLE
How to increase the size of dots.

### ISSUE THREAD

**Issue by pratik-walkhade** [FormidableLabs/nuka-carousel#712]
Hi, 

I was trying to increase the size of the dots of slider by using defaultControlsConfig > pagingDotsStyle.
Can you please help me out.

Thanks and regards,
Pratik W.

**Comment by hagaigold** [comment]
override the below classes:

```
circle {
  r: 6px;
  cx: 10px;
  cy: 10px;
}

.paging-dot {
  width: 20px;
  height: 20px;
}

```

**Comment by sarmeyer** [comment]
@pratik-walkhade Can you please provide a codesandbox or code sample of your use case and how you are using pagingDotStyle?

Thanks!
