### ISSUE TITLE
Properties slideOffset and zoomScale  do not exist on type..

### ISSUE THREAD

**Issue by dumitru-buda** [FormidableLabs/nuka-carousel#719]
# Bugs and Questions

### Describe Your Environment

- What version of nuka-carousel are you using? >4.7
- What version of React are you using? 16.13.1
- What browser are you using? Chrome
- What machine are you on? MacBook pro mid 2014

### Describe the Problem

I get the following error trying to use slideOffset or zoomScale:
Property 'slideOffset' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Carousel> & Readonly<CarouselProps> & Readonly<...>'.

**Comment by sarmeyer** [comment]
Fixed in 4.7.1
