### ISSUE TITLE
variable slides width is breaking the layout...

### ISSUE THREAD

**Issue by YarivGilad** [FormidableLabs/nuka-carousel#72]
Hi there,
It will be ideal to support any aspect ratio like in the case of users uploads, then scale the slides to result in the same height with a variable width...
What do you think?
Is there a way to set this at the current version?

Simple visual reference from a carousel written in php... 
http://jquery.lemmonjuice.com/plugins/slider-variable-widths.php

**Comment by Ajar-Ajar** [comment]
react-slick also supports variable width...
http://webrafter.com/opensource/react-slick

**Comment by shilpan** [comment]
@kenwheeler are there any plans on supporting this?

**Comment by ValGeorgiev** [comment]
I will close this for now due to inactivity, please raise another issue if this is still needed.
