### ISSUE TITLE
Easing on Current SlideHeight resizing

### ISSUE THREAD

**Issue by city17** [FormidableLabs/nuka-carousel#721]
I'm using the Current slide height for the carousel height. This makes the content below move up or down depending on the height of the current slide's image.

Is there any way to make this change in height more smooth? As in an easing animation for the change in height? Because right now it really pops in hard, which doesn't look too good.

For example, [this site](https://wakawaka.world/cylinder-back/) does have such an effect in place (mobile only).

Any help would be much appreciated.

**Comment by city17** [comment]
Solved: You can add transition to the class 'slider-list', like so:

```css
.slider-list {
  transition: height 0.2s ease-out;
}
```

The only (small) downside is that this animation will also show on entry, not just when changing slides.

**Comment by sarmeyer** [comment]
Hey @city17 Thank you for submitting this issue and subsequent solution! We'll look into adding this to the Carousel styling. I want to make sure it doesn't cause any unforeseen issues
