### ISSUE TITLE
nuka-carousel's demo in top page is broken because `src` is wrong.

### ISSUE THREAD

**Issue by yumemi-omi** [FormidableLabs/nuka-carousel#724]
nuka-carousel's demo in top page is broken because `src` is wrong.
http://kenwheeler.github.io/nuka-carousel/#/
<img width="1714" alt="Screen Shot 2020-09-15 at 14 02 01" src="https://user-images.githubusercontent.com/38467746/93167703-23544a80-f75c-11ea-8682-15e0a7dfbb2e.png">

Expected
`https://placehold.it/1000x400/ffffff/c0392b/&text=slide1`
Actual
`http://placehold.it/1000x400/ffffff/c0392b/&text=slide1`

**Comment by sarmeyer** [comment]
Hey @yumemi-omi - this isn't a site I maintain or have access to. There is a working demo in this repo if you need one.
