### ISSUE TITLE
Feature Request: lifecycle hook(s)

### ISSUE THREAD

**Issue by jperegoy** [FormidableLabs/nuka-carousel#727]
### Prerequisites

- [ x] I've searched open [issues](https://github.com/FormidableLabs/nuka-carousel/issues) to make sure I'm not opening a duplicate issue
- [ x] I have read through the docs before asking a question
- [x ] I am using the latest version of nuka-carousel

### Describe the Problem

There are times when actions need to be taken once the carousel has loaded (`onLoad`), gone through its first render cycle (`onReady`), etc. Including props (or similar method) which allows state to be set, functions to fire, etc at certain points in the carousels lifecycle would greatly aid this. Slides already have similar hooks, but nothing is currently configured for the wholistic carousel itself.

**Comment by fritz-c** [comment]
Detecting the loading of the slide contents is more the responsibility of the library user (e.g., if you want to detect when all the slide images loaded, etc, you'd pass in your own `onLoad` handler to each image's props). As for the first render, React's lifecycles or `React.useEffect` could be used to detect such timing. I will close this for the time being. If you have a more specific example that I didn't cover in my comment here, please share it and we can discuss it.
