### ISSUE TITLE
wrapAround, slidesToShow = number of items results in no animation when advancing slides

### ISSUE THREAD

**Issue by msimla** [FormidableLabs/nuka-carousel#743]
# Bugs and Questions

### Describe Your Environment

- What version of nuka-carousel are you using?
4.7.2
- What version of React are you using?
16.10.2
- What browser are you using?
Chrome
- What machine are you on?
MacOS Mojave

### Describe the Problem
When wrapAround is true and slidesToShow and number of items are the same, there is a blank space on the right when advancing to the next slide.

**Expected behavior:**
When wrapAround is true, and when slidesToShow and the number of items are the same, when advancing the slide, we should see the last slide animate in.
**Actual behavior:**
When advancing the slide, there is a blank space and the slide appears without animation.

### Additional Information
Codesandbox illustrating the issue is here:
https://codesandbox.io/s/floral-monad-nob7q?file=/src/index.js

**Comment by ValGeorgiev** [comment]
Hi @msimla, Thank you for raising this with us. I can say that we finally has a fix for it. Here is an [example](https://nuka-carousel.vercel.app/?slides=3&params=%7B%22wrapAround%22:true,%22slidesToShow%22:3%7D). I will close this for now. Feel free to raise another issue if you have any feedback for us.
