### ISSUE TITLE
SSR (next.js) & No-JS Support?

### ISSUE THREAD

**Issue by jayhack** [FormidableLabs/nuka-carousel#748]
Hey folks!

Our team loves the project and is contemplating using it in an SEO-optimized Next.js app. Two quick questions:

1. Does `nuka-carousel` support SSR?
2. What happens when JS is disabled and the page is SSR'd with`nuka-carousel`?

Thanks in advance!

**Comment by sarmeyer** [comment]
Hi @jayhack - thanks for your question! Nuka Carousel does support SSR. From my testing, it doesn't seem as though the Carousel will work with JS disabled. it will render, but the built-in Next and Previous slide methods don't work. It's possible you could implement your own methods with the `render*Controls` props that don't rely on JS to work.
