### ISSUE TITLE
Partially show unselected slides

### ISSUE THREAD

**Issue by DTAPigeons** [FormidableLabs/nuka-carousel#753]
Hello,
I am currently using the carousel to display several react components which are a combination of text and images. Is there a way to implement a behaviour where one component is shown in focus and the next and/or previous components are only partially visible on both sides of the focused component?

**Comment by sarmeyer** [comment]
Hi @DTAPigeons - you can do this by adjusting the `slidesToShow` prop. By passing a non-whole number (ex 1.25) you will show partial slides. From there you can adjust `cellAlign` to display the slides how you'd like. 

Let me know if you have any other questions!

**Comment by FrankFan** [comment]
hello, I met the same issue in 2024.

use nuka-carousel: 7.0.0

<img width="374" alt="image" src="https://github.com/FormidableLabs/nuka-carousel/assets/1589433/7dc53ffc-e40e-46d1-9ab0-8be2a19e47fe">

only partially visible on right, how to also partially visible on left ?
