### ISSUE TITLE
Center mode causes the initial left slide to not show

### ISSUE THREAD

**Issue by thanhvuong** [FormidableLabs/nuka-carousel#754]
### Describe Your Environment

- What version of nuka-carousel are you using?
4.7.5
- What version of React are you using?
17.0.1
- What browser are you using?
Chrome
- What machine are you on?
OSX Big Sur

### Describe the Problem

The Carousel is not working with certain prop values. I stumbled on an old example using a version from awhile back and it behaved as it should. Then, I tried upgrading the Carousel to 4.7.5 in codesandbox and it doesn't work. 

v4.7.5: (Changing slides behavior is broken)
https://codesandbox.io/s/dazzling-almeida-v8qr1?file=/src/index.js

v4.7.4: (Cell Align works but last slide (Slide 6) is not showing when cellAlign is center and wraparound is true slideToShow is 1.5)
https://codesandbox.io/s/musing-liskov-8jy0j?file=/src/index.js

v4.6.0: (Last working version with expected behavior)
https://codesandbox.io/s/determined-moon-xkd8u?file=/src/index.js

**Comment by carlosmori** [comment]
Any update on this ?

**Comment by sarmeyer** [comment]
Hi @carlosmori thanks for following up on this - I'll take a look today

**Comment by sarmeyer** [comment]
On a first pass, I don't see any issues with this example: 
v4.7.4: (Cell Align works but last slide (Slide 6) is not showing when cellAlign is center and wraparound is true slideToShow is 1.5)
https://codesandbox.io/s/musing-liskov-8jy0j?file=/src/index.js

**Comment by sarmeyer** [comment]
I think I've pinned down where the issue is happening after some digging - it seems our left-offset `deltaX` isn't being calculated properly on initial load. Strangely, if you use the demo and use state to change the `cellAlign` prop from `left` to `center` this issue isn't present. I'm working on a fix!

**Comment by carlosmori** [comment]
Thanks @sarmeyer !! We managed to find a workaround in React by setting the cell align center in a useEffect hook

**Comment by sarmeyer** [comment]
Nice! Yea it's an interesting bug, in the demo Center cellAlign seemingly works because it's usually carried out as a state change after the first mount, but this issue highlighted some flaky tests so it was good to rework those anyways.

**Comment by carlosmori** [comment]
Thanks @sarmeyer , amazing carousel! :)
