### ISSUE TITLE
React 17 adaptive

### ISSUE THREAD

**Issue by mutoe** [FormidableLabs/nuka-carousel#758]
# Bugs and Questions

### Prerequisites

**Feel free to delete this section if you have checked off all of the following.**

- [x] I've searched open [issues](https://github.com/FormidableLabs/nuka-carousel/issues) to make sure I'm not opening a duplicate issue
- [x] I have read through the docs before asking a question
- [x] I am using the latest version of nuka-carousel

### Describe Your Question

When I install nuka-carousel + react17, I got those warnings.

```
warning " > nuka-carousel@4.7.5" has incorrect peer dependency "react@^0.14.9 || ^15.3.0 || ^16.0.0".
warning " > nuka-carousel@4.7.5" has incorrect peer dependency "react-dom@^0.14.9 || ^15.3.0 || ^16.0.0".
```

Is there have any plan to upgrade React 17 as peer dependencies?

**Comment by sarmeyer** [comment]
Hi @mutoe! Yes, I have a draft PR to upgrade to React 17, however I'm waiting on an enzyme adapter package for v17. More information is detailed here! https://github.com/enzymejs/enzyme/issues/2429

**Comment by c7hulhu** [comment]
Any news about this issue with the PR mentioned?
