### ISSUE TITLE
ios Safari Swiping Transition Jerky with wrapAround is set to true

### ISSUE THREAD

**Issue by buzzguy** [FormidableLabs/nuka-carousel#769]
# Bugs and Questions

### Describe Your Environment

- What version of nuka-carousel are you using?
-4.77
- What version of React are you using?
- 17.01
- What browser are you using?
safari
### Describe the Problem

Open safari on phone and open up sandbox link below, then start swiping. The slide will go to the very next one without the normal ease. To get the expected behavior, click "Toggle Wrap" button. 

Sandbox:
https://codesandbox.io/s/kind-galileo-nq4ux?file=/src/index.js

**Expected behavior:** 
Each slide will ease from one to the next
(in same sandbox, toggle Wrap off and transition is what's expected)

**Actual behavior:** 
Ease transition has been short circuited in some way

### Additional Information
Any additional information, configuration or data that might be necessary to reproduce the issue.
It looks fine in safari and chrome on desktop in mobile view, just not on an actual phone

thanks!

**Comment by ValGeorgiev** [comment]
Hey @buzzguy, thanks for raising this with us. Could you try with the new version v5, please? I am not able to reproduce it with iPhone 10 - latest iOS on safari. Here is a [link](https://nuka-carousel-next.vercel.app/?slides=6&params=%7B%22wrapAround%22:true%7D)
