### ISSUE TITLE
Server-side-rendered markup does not pass HTML validation (scoped style tag required)

### ISSUE THREAD

**Issue by sompylasar** [FormidableLabs/nuka-carousel#77]
Here: https://github.com/kenwheeler/nuka-carousel/blob/111b6f16f8304b3c9fea17f192d087de264ec603/src/carousel.js#L181

The tag should have `scoped` attribute.

The W3 Validator at https://validator.w3.org/nu/ shows the following error:

```
Error: Element style not allowed as child of element div in this context. (Suppressing further errors from this subtree.)
From line 69, column 58948; to line 69, column 59018
div></div><style type="text/css" data-reactid=".10kyjyg7ojk.0.4.0.1.0.4.0.0.0.2">.slide
Contexts in which element style may be used:
If the scoped attribute is absent: where metadata content is expected.
If the scoped attribute is absent: in a noscript element that is a child of a head element.
If the scoped attribute is present: where flow content is expected, but before any other flow content other than inter-element whitespace and style elements, and not as the child of an element whose content model is transparent.
Content model for element div:
Flow content.
```

**Comment by BuffaloBuffalo** [comment]
As an alternative, it'd be great to have a way to suppress the style tag injection entirely and instead import the css into a webpack bundle.

**Comment by sompylasar** [comment]
> As an alternative, it'd be great to have a way to suppress the style tag injection entirely and instead import the css into a webpack bundle.

Yes.

**Comment by otajor** [comment]
@sompylasar @BuffaloBuffalo Did either of you find a workaround for this? It's the only thing that's messing up my server-side rendering :(

**Comment by sompylasar** [comment]
@otajor There is no viable workaround for this, only change the library code. But the issue is with the HTML validation by the W3C Validator. How is it messing up the server-side rendering? Could you elaborate please? Maybe it's a different issue you're talking about.

**Comment by otajor** [comment]
I was getting the following error on my server-rendered pages (only the ones with carousels on): 
`uncaught Error: Unable to find element with ID 173`

I googled and found [this SO answer](https://stackoverflow.com/questions/43185992/error-unable-to-find-element-with-id-275) which said it was caused by invalid HTML structure. So when I saw this thread I figured it was the cause of my bug. 

Seems I was right as I seem to have fixed the problem by adding a hacky `.replace(/<style/g, '<style scoped')` to my rendered html on the server before serving it. I'll see if I can come up with something less dangerous though!

**Comment by sompylasar** [comment]
@otajor Interesting... Just checked. I don't get this error while still having ```<style type="text/css" data-reactid="507">.slider-slide > img {width: 100%; display: block;}</style>``` rendered by the server-side.

**Comment by sompylasar** [comment]
@otajor Which browser are you observing the error in?

**Comment by otajor** [comment]
@sompylasar Chrome 58 - nothing fancy! And nuka-carousel 2.0.4.

**Comment by sompylasar** [comment]
@otajor I'm sticking with 1.2.0 but I don't see any clear difference in this part.

**Comment by sompylasar** [comment]
@otajor Maybe it's React? I use 15.5.4.
