### ISSUE TITLE
With cell align 'center' the last image is not displayed centered. 

### ISSUE THREAD

**Issue by peak3d** [FormidableLabs/nuka-carousel#773]
# Bugs and Questions

### Prerequisites

**Feel free to delete this section if you have checked off all of the following.**

- [X] I've searched open [issues](https://github.com/FormidableLabs/nuka-carousel/issues) to make sure I'm not opening a duplicate issue
- [X] I have read through the docs before asking a question
- [X] I am using the latest version of nuka-carousel

### Describe Your Environment

CodeSandbox (your playground) with nuka 4.7.7

### Describe the Problem

With cell align 'center' the last image is not displayed centered.
Open Sandbox below, and click "next" until third image should be selected.

**Expected behavior:** last image is centered
**Actual behavior:** last image is displayed right

https://codesandbox.io/s/sad-mestorf-geg5o?file=/src/index.js

code:
```import React from "react";
import Carousel from "nuka-carousel";
import ReactDom from "react-dom";

const colors = ["7732bb", "047cc0", "00884b", "e3bc13", "db7c00"];
// eslint-disable-next-line complexity
const App = () => {
  const slides = colors.slice(0, 3).map((color, index) => (
    <img
      src={`https://via.placeholder.com/400/${color}/ffffff/&text=slide${
        index + 1
      }`}
      alt={`Slide ${index + 1}`}
      key={color}
      style={{
        width: "100px",
        height: "200px"
      }}
    />
  ));

  return (
    <>
      <div style={{ width: "100%", margin: "auto" }}>
        <h2 style={{ textAlign: "center" }}>Nuka Carousel Demo</h2>
        <Carousel slideWidth="120px" cellAlign="center">
          {slides}
        </Carousel>
      </div>
    </>
  );
};

ReactDom.render(<App />, document.getElementById("root"));
```

**Comment by South-Paw** [comment]
@sarmeyer it looks like #760 was a breaking change. I bumped nuka-carousel to `4.7.8` and came across this bug as well.

**Comment by callmemonky** [comment]
Facing the exact same problem.

![image](https://user-images.githubusercontent.com/25193916/119479104-eec67300-bd6d-11eb-9e37-91d1148cb7cc.png)

**Comment by South-Paw** [comment]
Almost been 2 months now since it was broken and not even so much as a reply from a maintainer.

**Comment by sarmeyer** [comment]
I'm curious if anyone has any other examples of their prop configuration - after playing around with the sandbox, it seems the width set on each slide element in addition to the `slideWidth` prop was causing some issues from the first example. The `scrollMode` prop is also helpful here - setting it to `page` will show white space at the end of the carousel (it defaults to `remainder` which will scroll only the remainder of the slides without showing any blank space at the end).

Here's the sandbox with cellAlign working as expected: https://codesandbox.io/s/ecstatic-night-jj2uq?file=/src/index.js

If you comment out the `scrollMode` prop, you can see the default `remainder` value working as expected, as well

**Comment by South-Paw** [comment]
Hi @sarmeyer, thanks for your reply. I tried setting the `scrollMode` prop to `page` as you suggested and the white space at the end of the carousel has reappeared 🥳

If it helps, the prop configuration for my carousel (before adding `scrollMode`) was:

```tsx
const SLIDE_WIDTH = 176;

<NukaCarousel
  autoGenerateStyleTag={false}
  autoplay={false}
  cellAlign="center"
  dragging
  frameOverflow="visible"
  heightMode="current"
  slideWidth={`${SLIDE_WIDTH}px`}
  slidesToShow={3}
  renderCenterLeftControls={null}
  renderCenterRightControls={null}
  renderBottomCenterControls={null}
  swiping
  wrapAround={false}
  afterSlide={/* update state to index */}
  slideIndex={/* find index from state */}
>
  {/* render items in divs with widths = SLIDE_WIDTH */}
</NukaCarousel>
```

**Comment by sarmeyer** [comment]
does scrollMode solve this issue for you? It appears to me cellAlign is working as expected

**Comment by South-Paw** [comment]
> does scrollMode solve this issue for you? It appears to me cellAlign is working as expected

Yes, `scrollMode` being set to `page` resolves the issue thanks.

**Comment by ValGeorgiev** [comment]
Hi all, this issue should be fixed with v5, here is an [example ](https://nuka-carousel.vercel.app/?slides=6&params=%7B%22slidesToShow%22:3,%22cellAlign%22:%20%22center%22%7D). I will close it for now.

**Comment by palakdua95** [comment]
> https://codesandbox.io/s/ecstatic-night-jj2uq?file=/src/index.js

It is not seems to be working with nuka-carousel version 5.1.1

**Comment by ValGeorgiev** [comment]
Hey @palakdua95 could you clarify what is not working. I can see that the last image is center aligned in the provided sandbox. Also I saw my example link is not working any more so, here is another [example](https://nuka-carousel-next.vercel.app/?slides=6&params=%7B%22slidesToShow%22:3,%22cellAlign%22:%20%22center%22%7D)

**Comment by palakdua95** [comment]
> 

Hi @ValGeorgiev , currently carousel center align  is working fine with version "4.7.9". As soon as I change version of nuka-carousel to 5.1.1 , images are not getting center aligned as expected . To replicate the same , please change the version of nuka to 5 and above and see the carousel behaviour. codesandbox example link of yours is working fine now. There was some intermittent issue with codesandbox

**Comment by ValGeorgiev** [comment]
Hey @palakdua95 yes, it's not working out of the box when you upgrade the library. There some changes needed, as we rebuilt the whole library from scratch in v5. Here is an example with [code sandbox](https://codesandbox.io/s/shy-sun-qm2qtk?file=/src/index.js). We are giving more freedom to the developers with the library now, just to be more flexible. On the other side we are aware of an issue about floating numbers as slidesToShow property, which we will resolve very soon. Let me know if this is not working for you and you are looking for some other behaviour. Thanks

**Comment by palakdua95** [comment]
> Hey @palakdua95 yes, it's not working out of the box when you upgrade the library. There some changes needed, as we rebuilt the whole library from scratch in v5. Here is an example with [code sandbox](https://codesandbox.io/s/shy-sun-qm2qtk?file=/src/index.js). We are giving more freedom to the developers with the library now, just to be more flexible. On the other side we are aware of an issue about floating numbers as slidesToShow property, which we will resolve very soon. Let me know if this is not working for you and you are looking for some other behaviour. Thanks

Hi @ValGeorgiev , was going through your example and could see that center aligning is resolved, but in our case , we want slidesToShow in 1.25 floating number. We will be very thankful to you if you could suggest any workaround to achieve this.

**Comment by palakdua95** [comment]
Hi @ValGeorgiev , could you please let me know the tentative time where we will start getting support of floating numbers as well. Counting on it , as we have already plugged this carousel and finding it really great and lightweight. Thanks in advance.

**Comment by ValGeorgiev** [comment]
Hi @palakdua95 we have a PR already https://github.com/FormidableLabs/nuka-carousel/pull/901 which I need to review, test and merge. So I will say 1 week. I am very busy at the moment, but will do it asap

**Comment by ValGeorgiev** [comment]
@palakdua95 cellAlign with 1.5/1.25 should work with nuka-carousel@5.1.2

**Comment by palakdua95** [comment]
> @palakdua95 cellAlign with 1.5/1.25 should work with nuka-carousel@5.1.2

Yes, it is working perfectly fine now. Thanks a ton :)
