### ISSUE TITLE
Peer dependency issue with npm 7 and React 17

### ISSUE THREAD

**Issue by andtos90** [FormidableLabs/nuka-carousel#783]
# Bugs and Questions

### Prerequisites

**Feel free to delete this section if you have checked off all of the following.**

- [x] I've searched open [issues](https://github.com/FormidableLabs/nuka-carousel/issues) to make sure I'm not opening a duplicate issue
- [x] I have read through the docs before asking a question
- [x] I am using the latest version of nuka-carousel

### Describe Your Environment

- What version of nuka-carousel are you using? latest
- What version of React are you using? 17

### Describe the Problem

Doing an `npm install` with npm v7 will trigger a peer dependency issue if React version `17` is used instead of version `16`.

### Solution

The dependency `react-move` should be updated to version `6.5.0` in the next round of dependencies update. See https://github.com/sghall/react-move/issues/73#issuecomment-860158682

**Comment by sarmeyer** [comment]
@andtos90 thanks for submitting this - I've got a PR up to update react-move and resolve the peer dep issue
#785
