### ISSUE TITLE
Memory Leak - touchmove event listeners

### ISSUE THREAD

**Issue by markphilpot** [FormidableLabs/nuka-carousel#787]
### Describe Your Environment

- What version of nuka-carousel are you using? **4.7.8**
- What version of React are you using? **16.10**
- What browser are you using? **Chrome**

### Describe the Problem

Then handling of `touchmove` event listeners produces a memory leak as they are never cleaned up.

```
getLockScrollEvents() {
    const blockEvent = (e) => {
      if (this.state.dragging) {
        const direction = swipeDirection(
          this.touchObject.startX,
          e.touches[0].pageX,
          this.touchObject.startY,
          e.touches[0].pageY,
          this.props.vertical
        );
        if (direction !== 0) {
          e.preventDefault();
        }
      }
    };

    const lockTouchScroll = () => {
      document.addEventListener('touchmove', blockEvent, {
        passive: false
      });
    };

    const unlockTouchScroll = () => {
      document.removeEventListener('touchmove', blockEvent, {
        passive: false
      });
    };

    return {
      lockTouchScroll,
      unlockTouchScroll
    };
  }
```

Because the `blockEvent` function is recreated every time the method is run, the `unlockTouchScroll` cleanup that happens through `componentWillUnmount` never removes the original handler.  `blockEvent` should probably be bound to `this` (like the other event handlers) so it can be properly removed.

<img width="329" alt="CleanShot 2021-07-02 at 11 41 09@2x" src="https://user-images.githubusercontent.com/46191/124316417-6d12f380-db2a-11eb-97d1-dfb6319149f1.png">

*^^ After repeated mount/unmount cycles of the carousel component*

### Additional Information
Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by sarmeyer** [comment]
Good call out, @markphilpot - how are you testing the mount/unmount cycles of the carousel?

**Comment by markphilpot** [comment]
Using `react-router`

Page A -> 2 carousels, 9 items for each, 3 of which are visible
Page B -> Empty Page

Navigating back and forth between the two pages. Every render of Page A adds two handlers to `document`'s `touchmove` event listener.
