### ISSUE TITLE
Memory Leak - InertManager retaining references all detached dom elements

### ISSUE THREAD

**Issue by markphilpot** [FormidableLabs/nuka-carousel#789]
# Bugs and Questions

### Describe Your Environment

- What version of nuka-carousel are you using? 4.7.8
- What version of React are you using? 16.10, 17.x
- What browser are you using? Chrome

### Describe the Problem

`wicg-inert` polyfill seems to be retaining a reference to all `Detached HTML*Elements` that enter it's system (I'm assuming it's all DOM elements with `inert` set to true. Any repeated mount/unmount cycle of the Carousel where there are more elements that can be visible at once (so that nuka marks them as inert) will show this behavior.

<img width="1321" alt="CleanShot 2021-07-06 at 14 54 52@2x" src="https://user-images.githubusercontent.com/46191/124796359-eda86a00-df05-11eb-9eaa-53f4c370208f.png">

**Comment by fritz-c** [comment]
We do not bundle in `wicg-inert` since v5.0.0, so I am assuming this issue is not present in the newest versions.
