### ISSUE TITLE
Allow dynamic slideToShow updating

### ISSUE THREAD

**Issue by Joneser** [FormidableLabs/nuka-carousel#79]
When binding the slidesToShow attribute to a dynamic variable, it takes some time to update, I believe this is because the slidesToShow pop is not being updated in componentWillReceiveProps().

**Comment by mankittens** [comment]
See PR #131

**Comment by mariano-formidable** [comment]
The latest version of `nuka-carousel` (4.3.2) does handle `slidesToShow` prop updates within `componentWillReceiveProps`.  This issue should now be resolved.
