### ISSUE TITLE
When `slidesToScroll="auto"` and `cellSpacing={10}` are set at the same time, the page will crash

### ISSUE THREAD

**Issue by zzkaqq** [FormidableLabs/nuka-carousel#793]
# Bugs and Questions

### Prerequisites

**Feel free to delete this section if you have checked off all of the following.**

- [x] I've searched open [issues](https://github.com/FormidableLabs/nuka-carousel/issues) to make sure I'm not opening a duplicate issue
- [x] I have read through the docs before asking a question
- [x] I am using the latest version of nuka-carousel

### Describe Your Environment

- What version of nuka-carousel are you using?
- v4.7.0
- What version of React are you using?
- 16.13.1
- What browser are you using?
- chrome 91

### Describe the Problem

When `slidesToScroll="auto"` and `cellSpacing={10}` are set at the same time, the page will crash

### Additional Information
<img width="915" alt="截屏2021-07-31 下午5 57 41" src="https://user-images.githubusercontent.com/9392200/127736280-8fac90af-692f-4b61-96df-7b0ab9e5af13.png">

<img width="788" alt="截屏2021-07-31 下午5 58 09" src="https://user-images.githubusercontent.com/9392200/127736295-52630f60-09e6-4eb2-8bfd-5a9544b281b1.png">

**Comment by sarmeyer** [comment]
@zzkaqq I'm able to replicate your issue in a sandbox. I'd like to understand your implementation a bit more - What is your intention with `slidesToScroll`? this prop is used to always scroll the current number of visible slides, but I don't see you showing more than 1 slide at a time in this example.

**Comment by renanrider** [comment]
Hi, thanks for this libray. I am with the same bug here

Describe Your Environment

    What version of nuka-carousel are you using?
    v4.8.1
    What version of React are you using?
    17.0.2
    What browser are you using?
    Firefox 94.0.1 (64-bits)

Describe the Problem

When cellSpacing > = 10, memory starts increasing until browser crashes, if you remove cellSpacing or decrease the value, the problem disappears.

**Comment by ValGeorgiev** [comment]
Hey @zzkaqq thanks for rising this with us. The issue should be fixed in the latest v4.8.4. Please feel free to reopen this if you still see the bug
