### ISSUE TITLE
Dynamic slides ignores scroll animation

### ISSUE THREAD

**Issue by bhimeshchauhan** [FormidableLabs/nuka-carousel#795]
# Bugs and Questions

### Prerequisites

**Feel free to delete this section if you have checked off all of the following.**

- [X] I've searched open [issues](https://github.com/FormidableLabs/nuka-carousel/issues) to make sure I'm not opening a duplicate issue
- [X] I have read through the docs before asking a question
- [ ] I am using the latest version of nuka-carousel

### Describe Your Environment

- What version of nuka-carousel are you using? - 4.4.6
- What version of React are you using? - 16.8.6
- What browser are you using? - Chrome

### Describe the Problem

Is there a way to trigger a recalculation of `transform` property on an unordered list for dynamically loaded elements in the carousel?

Current behavior makes the scroll animation not work for anything loaded dynamically.

### Additional Information
Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by ValGeorgiev** [comment]
Hey @bhimeshchauhan, can you provide a sandbox or public repository where we can reproduce the issue, please. Thanks for raising this with us.
