### ISSUE TITLE
Unable to append the nav button events for the dynamically rendered buttons, also is there any navContainer option available?

### ISSUE THREAD

**Issue by SKcbe** [FormidableLabs/nuka-carousel#797]
# Bugs and Questions

### Prerequisites

**Feel free to delete this section if you have checked off all of the following.**

- [ ] I've searched open [issues](https://github.com/FormidableLabs/nuka-carousel/issues) to make sure I'm not opening a duplicate issue
- [ ] I have read through the docs before asking a question
- [ ] I am using the latest version of nuka-carousel

### Describe Your Environment

- What version of nuka-carousel are you using?
- What version of React are you using?
- What browser are you using?

### Describe the Problem

It's easier to show us than tell us what's going wrong with your code. Because of this, we ask that you do one of three things to help us reproduce the bug:

1. Create a public minimal repository that we can `git clone`, with install + error reproduction steps in the README.
2. Create a sandbox, reproduce your issue in the code, and paste the link here.
3. Open up a PR, include "WIP" and the Issue # in the title, and point us to the failing regression tests.

**Expected behavior:** [What you expect to happen]
**Actual behavior:** [What actually happens]

### Additional Information
Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by ValGeorgiev** [comment]
Hey @SKcbe can you give us more information about the issue, so we can help with resolving it. Also providing sandbox to reproduce the issue it will be great. Thanks

**Comment by SKcbe** [comment]
@ValGeorgiev Animation is not working for prev navigation when on fist slide and next navigation when on last slide, if we set wraparound true

**Comment by ValGeorgiev** [comment]
> @ValGeorgiev Animation is not working for prev navigation when on fist slide and next navigation when on last slide, if we set wraparound true

Hi @SKcbe, thanks for raising this with us. This should be fixed now with v5. You can test it [here](https://nuka-carousel-next.vercel.app/?slides=6&params=%7B%22wrapAround%22:true,%22slidesToShow%22:3%7D). I will close it, please open another issue if it's still reproducible for you.
