### ISSUE TITLE
First image not rendering at left side when having three images 

### ISSUE THREAD

**Issue by satinP** [FormidableLabs/nuka-carousel#809]
# Bugs and Questions

### Prerequisites

**Feel free to delete this section if you have checked off all of the following.**

- [x] I've searched open [issues](https://github.com/FormidableLabs/nuka-carousel/issues) to make sure I'm not opening a duplicate issue
- [x] I have read through the docs before asking a question
- [x] I am using the latest version of nuka-carousel

### Describe Your Environment

- What version of nuka-carousel are you using?
  v4.8.1
- What version of React are you using?
  v17.0.2
- What browser are you using?
  Google Chrome v95

### Describe the Problem

When `cellAlign="center"`, `wrapAround=true`, `transitionMode="scroll"` and `slidesToShow` is greater than 1, the 3rd image is not shown at the left side of the first image in the carousel, if we change the list to show more than three image this does not happen and the last image is shown as expected at the left side.

I've forked the sandbox demo link and made those changes, you can check here: [Code SandBox Demo](https://codesandbox.io/s/flamboyant-hooks-68z3j?file=/src/index.js:1661-1667)

**Expected behavior:**
![Carousel with five images](https://user-images.githubusercontent.com/33128737/140815296-61b21d2f-58a8-4b9b-97f3-cb9b39f0b0ec.png)

**Actual behavior:**
![Carousel with three images](https://user-images.githubusercontent.com/33128737/140815241-57907db4-b78b-4f69-8c63-48126d9f4548.png)

**Comment by ValGeorgiev** [comment]
Hey @satinP, thanks for raising this issue with us. I raised a PR to fix this weirdo 🤞 ☝️
