### ISSUE TITLE
Pinch to Zoom Touch Action freezes on image

### ISSUE THREAD

**Issue by csmith17-chwy** [FormidableLabs/nuka-carousel#848]
# Bugs and Questions

### Prerequisites

**Feel free to delete this section if you have checked off all of the following.**

- [x] I've searched open [issues](https://github.com/FormidableLabs/nuka-carousel/issues) to make sure I'm not opening a duplicate issue
- [x] I have read through the docs before asking a question
- [x] I am using the latest version of nuka-carousel

### Describe Your Environment

- What version of nuka-carousel are you using? 4.8.3
- What version of React are you using? 17.0.2
- What browser are you using? Safari and Chrome on iOS 15 specifically

### Describe the Problem

It's easier to show us than tell us what's going wrong with your code. Because of this, we ask that you do one of three things to help us reproduce the bug:

1. Create a public minimal repository that we can `git clone`, with install + error reproduction steps in the README.
Can replicate in your sandbox environment.
https://codesandbox.io/s/silly-rosalind-6y7f3

2. Create a sandbox, reproduce your issue in the code, and paste the link here.
https://codesandbox.io/s/silly-rosalind-6y7f3

3. Open up a PR, include "WIP" and the Issue # in the title, and point us to the failing regression tests.
N/A

Expected: Be able to pinch to zoom as a touch action on the image in the carousel.
Actual: Sometimes it freezes while zoomed in, and becomes difficult for the user to zoom out of. Please note it doesn't always happen. Clearing cache and cookies seems to help but then it starts doing it again.

To Reproduce: 
- Open in Safari or Chrome on an iphone with iOS 15
- Attempt to pinch zoom on the image slider. Once it is zoomed in, stop.
- Now try to zoom out. It becomes frozen, and eventually I can get out by scrolling down or up and zooming out on a different element.

### Additional Details
I have videos of it happening in our application, and in the sandbox but the files are too big here so Justin Gardner added it to his Dropbox. Links below:
https://www.dropbox.com/s/3xfjh6gw5ov4jw7/RPReplay_Final1643746545.MP4?dl=0
https://www.dropbox.com/s/yx96441ie0gabhj/RPReplay_Final1643747201.MP4?dl=0

**Comment by ValGeorgiev** [comment]
Hi @csmith17-chwy, could you verify the issue with nuka-carousel v5, please, here is some [brief documentation](https://github.com/FormidableLabs/nuka-carousel/tree/main/src-v5#v5-nuka-carousel). TBH I cannot reproduce it, so it will be great someone to reconfirm. Thanks for raising this with us
