### ISSUE TITLE
slider-container has hardCoded padding

### ISSUE THREAD

**Issue by Amit-Kaplan** [FormidableLabs/nuka-carousel#852]
# Bugs and Questions

### Prerequisites

**Feel free to delete this section if you have checked off all of the following.**

- [X] I've searched open [issues](https://github.com/FormidableLabs/nuka-carousel/issues) to make sure I'm not opening a duplicate issue
- [x] I have read through the docs before asking a question
- [x] I am using the latest version of nuka-carousel

### Describe Your Environment

- What version of nuka-carousel are you using? 5.0.2
- What version of React are you using? 16-17
- What browser are you using? chrome

### Describe the Problem
slider-container has hardCoded padding in case of using visual controls.
`<div
      className={'slider-container'}
      style={{
        position: 'relative',
        padding: props.withoutControls ? 0 : '0 60px 50px'
      }}
      onMouseEnter={onMouseEnter}
      onMouseLeave={onMouseLeave}
    >
......
`

**Expected behavior:** padding can be change by props
**Actual behavior:** hard coded

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by ValGeorgiev** [comment]
Hey @Amit-Kaplan thanks for this, I will look to submit a PR today and tomorrow about that.

**Comment by ValGeorgiev** [comment]
This should be fixed with v5.0.3. Please reopen and let me know if you still have this issue.
