### ISSUE TITLE
Images not sliding continuously

### ISSUE THREAD

**Issue by musindo** [FormidableLabs/nuka-carousel#853]
# Bugs and Questions

### Prerequisites

**Feel free to delete this section if you have checked off all of the following.**

- [x] I've searched open [issues](https://github.com/FormidableLabs/nuka-carousel/issues) to make sure I'm not opening a duplicate issue
- [x] I have read through the docs before asking a question
- [x] I am using the latest version of nuka-carousel

### Describe Your Environment

- nuka-carousel: 4.8.4
- react: 17.0.2
- Chrome

### Describe the Problem
i have 4 images in my Carousel, when the slider reaches the last image it stops. I tried using use autoplay with wraparound but still same behaviour

**Expected behavior:** Continuous looping of images
**Actual behavior:** Sliding stopping on the last image

**Comment by ValGeorgiev** [comment]
I am closing this as its not an issue. More info here https://github.com/FormidableLabs/nuka-carousel/issues/701
