### ISSUE TITLE
Doesn't work in Deno with React SSR

### ISSUE THREAD

**Issue by nnmrts** [FormidableLabs/nuka-carousel#856]
This is an upstream issue of https://github.com/WICG/inert/issues/178, but I wanted to point it out here because https://github.com/WICG/inert doesn't really seem to be actively maintained.

So the only fix for this inside nuka-carousel would be to remove the dependency.

**Comment by ValGeorgiev** [comment]
Hey @nnmrts you can use nuka-carousel@5.0.2 which doesn't have any dependencies and the inert should be included by the users if they want to use it. Also v5+ is supporting SSR. Please let me know if you still has the issue after upgrading.

**Comment by ValGeorgiev** [comment]
I am closing this for now, please let me now if you still have an issue

**Comment by nnmrts** [comment]
@ValGeorgiev Sorry for not answering before. I am pretty sure I used nuka-carousel when this issue came up but I can check it out and try to make a reproduction repository on the weekend.

**Comment by ValGeorgiev** [comment]
@nnmrts please let me know how this went. Feel free to reopen it if it's still reproducible and I can work on a fix
