### ISSUE TITLE
Discrepancy of npm and github v5.0.5 versions

### ISSUE THREAD

**Issue by David245M** [FormidableLabs/nuka-carousel#863]
# Bugs and Questions

### Prerequisites

**Feel free to delete this section if you have checked off all of the following.**

- [x] I've searched open [issues](https://github.com/FormidableLabs/nuka-carousel/issues) to make sure I'm not opening a duplicate issue
- [x] I have read through the docs before asking a question
- [x] I am using the latest version of nuka-carousel

### Describe Your Environment

- What version of nuka-carousel are you using? v5.0.5
- What version of React are you using? v16.8.6
- What browser are you using? Google Chrome

### Describe the Problem

There is discrepancy of v5.0.5 deployed to npm and v5.0.5 on github. you can see it if you check inline styles in `slider-container`: in npm padding rule [is presence](https://unpkg.com/nuka-carousel@5.0.5/lib-v5/carousel.js), in github [it is absent](https://github.com/FormidableLabs/nuka-carousel/blob/b24512a7ae0782b96a9767bd6eb9bc34138473b4/src-v5/carousel.tsx#L368).

**Expected behavior:** Conformity of versions, absent of inline padding rule.
**Actual behavior:** Discrepancy of versions, presense of inline padding rule.

**Comment by ValGeorgiev** [comment]
Hey @David245M Thanks for raising this with us. I just fixed it and released a new version v5.0.6. Here is a [link](https://unpkg.com/nuka-carousel@5.0.6/lib-v5/carousel.js). I will close this now, feel free to reopen it.
