### ISSUE TITLE
Vertical mode not working

### ISSUE THREAD

**Issue by tamdao** [FormidableLabs/nuka-carousel#869]
I try to use this lib with vertical mode is true. But it work the same with vertical mode is false

```
<NukaCarousel
      wrapAround
      autoplay
      vertical
      heightMode="current"
      renderCenterLeftControls={() => null}
      renderCenterRightControls={() => null}
      defaultControlsConfig={{
        pagingDotsStyle: {
          fill: 'white',
        },
      }}
    >
      {props.children}
</NukaCarousel>
```

**Comment by ValGeorgiev** [comment]
Hey @tamdao, nuka-carousel v5 is not supporting vertical carousel yet. We have a ticket for this and it's the main priority for v5.1. If you want to use the vertical carousel now you need to install v4.8.4. `npm install nuka-carousel@4.8.4`

**Comment by ValGeorgiev** [comment]
I will close this for now, as it's a known issue in v5. If you want to use vertical carousel you can use v4 or wait for v5.1

**Comment by tamdao** [comment]
@ValGeorgiev Thanks for quick reply. I have tried to use v4.8.4 and got another issue related to transition to another slide when I use `autoplay` property. It show black screen

I need to add `autoplayReverse` to fix this. Do you have any solution for this?
