### ISSUE TITLE
Some slides only render when animation is complete if multiple slides are shown at once

### ISSUE THREAD

**Issue by rngyn** [FormidableLabs/nuka-carousel#870]
# Bugs and Questions

### Prerequisites

**Feel free to delete this section if you have checked off all of the following.**

- [x] I've searched open [issues](https://github.com/FormidableLabs/nuka-carousel/issues) to make sure I'm not opening a duplicate issue
- [x] I have read through the docs before asking a question
- [x] I am using the latest version of nuka-carousel

### Describe Your Environment

- What version of nuka-carousel are you using? 4.8.4
- What version of React are you using? 17.0.2
- What browser are you using? Chrome

### Describe the Problem

It's easier to show us than tell us what's going wrong with your code. Because of this, we ask that you do one of three things to help us reproduce the bug:

1. Create a public minimal repository that we can `git clone`, with install + error reproduction steps in the README.
2. Create a sandbox, reproduce your issue in the code, and paste the link here. https://codesandbox.io/s/snowy-darkness-prjpfs
3. Open up a PR, include "WIP" and the Issue # in the title, and point us to the failing regression tests.

**Expected behavior:** [What you expect to happen] - All slides should already be rendered when clicking through.
**Actual behavior:** [What actually happens] - Slides 1 & 2 only render when slide animation stops when going backwards. Slides 3 & 4 only render when animation stops when going forwards.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

Setting wrapAround to true, slideWidth to 0.72 (something smaller than 1), cellSpacing to 7 (any int), and slide length of 4 (lower numbers cause issues as well) will reproduce this problem. Can also be reproduced with slidesToShow. Basically any time more than one slide is shown at a time will cause rendering issues.

**Comment by ValGeorgiev** [comment]
Hey @rngyn, this is fixed with v5. Please use the latest version. [Demo](https://nuka-carousel-next.vercel.app/?slides=6&params=%7B%22slidesToShow%22:2,%22cellAlign%22:%20%22center%22%7D) . I will close this issue, please let me know if you have any questions

**Comment by ValGeorgiev** [comment]
Hey @rngyn definitely agree and this is my fault. I am currently preparing a documentation update (I will create a PR today) and maybe later this week I will prepare quick migration guide. On the heightMode="current" I would use `animation="zoom"` instead. Here is a [demo](https://nuka-carousel-next.vercel.app/?slides=6&params=%7B%22wrapAround%22:true,%22slidesToShow%22:3,%22animation%22:%20%22zoom%22%7D). Please let me know if this is not working for you.

**Comment by rngyn** [comment]
Thanks for the suggestion @ValGeorgiev. Unfortunately the zoom animation doesn't fit my needs. Here's how I need to use the carousel with heightMode="current":

- Animation needs to be 'fade'
- Each slide is a different height, so I need the carousel to dynamically change heights for each slide. This will move surrounding components around with it. This is why heightMode="current" fit my needs.

I can try recording a demo if you'd like. Let me know, thank you!

**Comment by ValGeorgiev** [comment]
Hey @rngyn I missed your comment, sorry. Demo will be very useful yes. I think this should work out of the box.. In the v4 we fixed and manipulated the height of the slides, thats why heightMode was useful. In v5 we are not doing this, so the carousel should render the images/slides depending on their height.

**Comment by ValGeorgiev** [comment]
@rngyn Thanks for raising this with us. I will have a look tomorrow if we can fix it easily, otherwise it will be added to our v5.1 backlog. I will come back to you tomorrow

**Comment by ValGeorgiev** [comment]
Hey @rngyn I created a [PR](https://github.com/FormidableLabs/nuka-carousel/pull/875) to add `adaptiveHeight` property in nuka. It will be deployed to v5.0.9 soon

**Comment by ValGeorgiev** [comment]
v5.0.9 is live, please check the `adaptiveHeight` property!
