### ISSUE TITLE
Install with React V18.0.0

### ISSUE THREAD

**Issue by daxamayac** [FormidableLabs/nuka-carousel#876]
# Bugs and Questions

### Prerequisites
- React project with version 18.0.0

**Feel free to delete this section if you have checked off all of the following.**

- [x] I've searched open [issues](https://github.com/FormidableLabs/nuka-carousel/issues) to make sure I'm not opening a duplicate issue
- [x] I have read through the docs before asking a question
- [x] I am using the latest version of nuka-carousel

### Describe Your Environment

- What version of nuka-carousel are you using?
   5.0.8
- What version of React are you using?
18.0.0
- What browser are you using?
Brave

### Describe the Problem

Installation problems with React V18.0.0

### Additional Information

```npm ERR! code ERESOLVE  
npm ERR! ERESOLVE unable to resolve dependency tree  
npm ERR! 
npm ERR! While resolving: eva.insurtech.web.majormedicalexpenses@0.1.0
npm ERR! Found: react@18.0.0
npm ERR! node_modules/react
npm ERR!   react@"^18.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.3.0 || ^16.0.0 || ^17.0.1" from nuka-carousel@5.0.8
npm ERR! node_modules/nuka-carousel
npm ERR!   nuka-carousel@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See C:\Users\DavidAmaya\AppData\Local\npm-cache\eresolve-report.txt for a full report.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dx\AppData\Local\npm-cache\_logs\2022-04-08T19_32_03_782Z-debug-0.log```

**Comment by ValGeorgiev** [comment]
Hey @daxamayac Thanks for raising this with us. We just released a new version v5.0.9 and this should be fixed there. Please let me know if you still has issues.
