### ISSUE TITLE
Bug with React 18, (infinity, cellSpacing, flicker)

### ISSUE THREAD

**Issue by daxamayac** [FormidableLabs/nuka-carousel#879]
# Bugs and Questions

### Prerequisites
- [x] I've searched open [issues](https://github.com/FormidableLabs/nuka-carousel/issues) to make sure I'm not opening a duplicate issue
- [x] I have read through the docs before asking a question
- [x] I am using the latest version of nuka-carousel

### Describe Your Environment

- What version of nuka-carousel are you using?
5.0.10
- What version of React are you using?
18.0.0
- What browser are you using?
Brave

### Describe the Problem
Multiple Problems
1. Infinity mode: the carousel goes blank after a while, (work if remove  <React.StrictMode> in _app)
2. When remove <React.StrictMode> work infinity mode, but there is a flicker in the transition.
3. cellSpacing: create double row (click in prev button)

**Sandbox:** https://codesandbox.io/s/nuka-carousel-react-18-3oelyx

**Expected behavior:** infinity mode without flicker and with cellSpacing
**Actual behavior:** infinity mode no work, flicker in transition, and cellSpacing crete double row

**Comment by ValGeorgiev** [comment]
Hey @daxamayac, thanks for raising this with us. I am able to reproduce the bugs with the StrictMode. I will try to ship a fix asap.

**Comment by daxamayac** [comment]
Hi all problems are resolved.
