### ISSUE TITLE
slideIndex doesn't seem to be respected in v5

### ISSUE THREAD

**Issue by geoffharcourt** [FormidableLabs/nuka-carousel#884]
# Bugs and Questions

### Prerequisites

**Feel free to delete this section if you have checked off all of the following.**

- [x] I've searched open [issues](https://github.com/FormidableLabs/nuka-carousel/issues) to make sure I'm not opening a duplicate issue
- [x] I have read through the docs before asking a question
- [x] I am using the latest version of nuka-carousel

### Describe Your Environment

- What version of nuka-carousel are you using?
5.0.11 and 5.0.12

- What version of React are you using?
17.0.2

- What browser are you using?
Chrome 100

### Describe the Problem

It's easier to show us than tell us what's going wrong with your code. Because of this, we ask that you do one of three things to help us reproduce the bug:

I'm still working up a small reproduction, but in the course of trying to upgrade from nuka-carousel v4 to v5, our carousels that control the active slide by external controls (and update the `slideIndex` prop vs. triggering next/previous) don't seem to be working. When I trigger the changes and observe in the React Dev Tools Components browser, I can see that `slideIndex` changes, but the displayed slides does not change. This seems to happen if we override to start on a slide other than the first slide as well.

**Expected behavior:** [What you expect to happen]

Rendering with a new `slideIndex` prop changes the displayed slide.

**Actual behavior:** [What actually happens]

Nothing changes on the screen.

### Additional Information

This works in v4 in the components we use the leverage nuka-carousel.

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by ValGeorgiev** [comment]
Hey @geoffharcourt thanks for raising this with us. I created a PR with a fix and will deploy it in a bit.

**Comment by ValGeorgiev** [comment]
slideIndex should work as expected in v5.0.13. Thanks for raising this again
