### ISSUE TITLE
`@types/react` requires explicit children in props starting with v18

### ISSUE THREAD

**Issue by riceboyler** [FormidableLabs/nuka-carousel#889]
# Bugs and Questions

### Describe Your Environment

- What version of nuka-carousel are you using?
  5.0.13
- What version of React are you using?
  18.0.0
- What browser are you using?
  Irrelevant, but Microsoft Edge (Chromium)

### Describe the Problem
As of `@types/react@18.0.0` children is no longer included as an implicit prop, which causes issues for Carousel as `children` is not an explicit prop in `CarouselProps` in index.d.ts.

I created a code sandbox, but it doesn't replicate the issue I'm seeing because I don't think it uses TypeScript quite the same as a build process would. 

Instead using https://github.com/riceboyler/nuka-types and opening index.tsx (after running `yarn`) should demonstrate the Type errors.

**Expected behavior:** No errors from VSCode or my build process related to Carousel not having children as an available prop
**Actual behavior:** 

![image](https://user-images.githubusercontent.com/2243596/164800756-03f3e734-f0fb-4380-b32f-95826fcdfa8f.png)

**Comment by ValGeorgiev** [comment]
Hey @riceboyler thanks for raising this with us and specially about your PR. I merged and publish it to v5.0.14. Thanks again
