### ISSUE TITLE
How to change the content of Previous & Next buttons? 

### ISSUE THREAD

**Issue by Fprince333** [FormidableLabs/nuka-carousel#9]
Let's say I want to have an icon or something rather than the default "Prev" and "Next" - is there a way to do that?

**Comment by abhilashsajeev** [comment]
You can create your own decorators and pass them to carousel as properties.
```
var Decorators = [{
  component: React.createClass({
    render() {
      return (
        <button
          onClick={this.props.previousSlide}>
          Previous Slide
        </button>
      )
    }
  }),
  position: 'CenterLeft',
  style: {
    padding: 20
  }
}];

```
[carousel](http://kenwheeler.github.io/nuka-carousel/#/)

**Comment by Fprince333** [comment]
Perfect, thanks. This was the step I was missing.

![nuka_carousel](https://cloud.githubusercontent.com/assets/1648240/7960962/672985a4-09d2-11e5-9438-6130201bcc9c.png)

**Comment by Chinaski1979** [comment]
I created my own decorators using the decorator={Decortors} example. But how would I go about making the button transparent when there are no more slides available to that direction?

**Comment by Kerumen** [comment]
Look at the source file [decorator.js](https://github.com/kenwheeler/nuka-carousel/blob/master/src/decorators.js).
It gives an exemple of how is it achieved: `this.props.currentSlide === 0` which set a `bool` to true and then style the button with an opacity. You can reuse this to custom your carousel.


    {
        component: React.createClass({
          render() {
            return (
              <button
                style={this.getButtonStyles(this.props.currentSlide === 0)}
                onClick={this.props.previousSlide}>PREV</button>
            )
          },
          getButtonStyles(disabled) {
            return {
              border: 0,
              background: 'rgba(0,0,0,0.4)',
              color: 'white',
              padding: 10,
              outline: 0,
              opacity: disabled ? 0.3 : 1,
              cursor: 'pointer'
            }
          }
        }),
        position: 'CenterLeft'
    }

**Comment by freshmilkdev** [comment]
@Kerumen great solution, thanks!

**Comment by ahmedsoliman92** [comment]
Is it possible to remove the buttons only leaving the dots ?

**Comment by freshmilkdev** [comment]
@ahmedsoliman92 you can just hide them with css:
```css
 .slider-decorator-0, .slider-decorator-1 { 
    display: none;
 }
```

**Comment by susheelachoudry** [comment]
Is it possible to change only color/styles of center dots and buttons(prev and next) ?
