### ISSUE TITLE
Body scroll disabled

### ISSUE THREAD

**Issue by chocovelod** [FormidableLabs/nuka-carousel#913]
Hey!
The body does not scroll vertically on the carousel, how can this be fixed?

**Comment by ValGeorgiev** [comment]
Hey @chocovelod, could you give more information, what you mean about body doesn't scroll vertically? Screenshot and code sandbox it will be useful

**Comment by chocovelod** [comment]
<img width="378" alt="Снимок экрана 2022-06-21 в 10 41 56" src="https://user-images.githubusercontent.com/65286428/174744150-a96acfe5-9b56-4f7f-96bb-e5aac03bd598.png">

I cant scroll page when my finger on carousel container. Only carousel items swiping.

**Comment by ValGeorgiev** [comment]
I was able to reproduce it on real device, I will have a look. Thanks for letting us know

**Comment by ValGeorgiev** [comment]
FYI: this was disabled because of this issue. #874 . I am looking for a fix, that will make everyone happy :)

**Comment by chocovelod** [comment]
I think it's nice to have some property that can change overflow-y to "auto". Might be helpful

**Comment by fritz-c** [comment]
As of 5.2.0, this has been fixed. You can test here to see:
https://codesandbox.io/s/blazing-moon-duy07s
