### ISSUE TITLE
serverside rendering

### ISSUE THREAD

**Issue by fluse** [FormidableLabs/nuka-carousel#92]
Hi guys,

i have a issue.

if you use markup insteed of image tag, this component will not render the correct width of slide-slide and list and dont show any element.

http://wkj.herokuapp.com/ 
got to headline
"Die beliebtesten DJs  für Köln"

and turn off js.

maybe if window object not set, you can insert default widths?

**Comment by Lukavyi** [comment]
Set initialSlideWidth and initialSlideHeight

**Comment by robr24** [comment]
initialSlideWidth is required for the carousel to appear before componentDidMount is called, indeed. The problem is, that you cannot pass in an initialSlideWidth of 100% currently, you must know the pixel value. And we don't have access to the window object until the component has mounted.

**Comment by kenwheeler** [comment]
@robr24 a technique that I have used in the past, is to get the window width on each client load, and set it in a cookie, which is then retrievable on the server in subsequent loads and used to take a best guess at width, asserting that width has not changed since the previous and current page loads.

**Comment by robr24** [comment]
Thanks @kenwheeler, I thought about that as well. One approach we can take in this carousel is to allow for an initialWidth of % also, and separate the get styles between componentWillMount and componentDidMount. Then if the initialSlideWidth had been set to a percentage, we can override it in setDimensions...?

**Comment by ijsnow** [comment]
Is there any work around or solution for this in place yet?
