### ISSUE TITLE
Cloned slides exhibit zoom animation behavior

### ISSUE THREAD

**Issue by zdolin** [FormidableLabs/nuka-carousel#928]
### Describe Your Environment

- What version of nuka-carousel are you using? 5.1.3
- What version of React are you using? 17.0.2
- What browser are you using? Chrome

### Describe the Problem

See example here https://codesandbox.io/s/upbeat-pateu-ylg2v9

**Expected behavior:** When setting animation to "zoom", only the current slide should scale.
**Actual behavior:** When setting animation to "zoom", the prev/next cloned slides also exhibit the scaling effect.

**Comment by zdolin** [comment]
@ValGeorgiev any thoughts on fixing this one?

**Comment by ValGeorgiev** [comment]
Hey @zdolin sorry for the late response, but I am super busy on other stuffs. I will prepare a PR for you asap. Thanks for raising this with us.

**Comment by zdolin** [comment]
@ValGeorgiev understood! much appreciated

**Comment by ValGeorgiev** [comment]
I will prepare a release today, which will include this fix

**Comment by ValGeorgiev** [comment]
This fix is included in v5.2.0, please reopen or open other issue if you are still reproducing it. Thanks again for raising this with us
