### ISSUE TITLE
Empty slide rendered with false conditional

### ISSUE THREAD

**Issue by victorakioz** [FormidableLabs/nuka-carousel#951]
# Bugs and Questions

### Describe Your Environment

- What version of nuka-carousel are you using?
5.2.0
- What version of React are you using?
18.2.0
- What browser are you using?
Brave

### Describe the Problem

When having a slide that should be conditionally rendered, if false an empty slide is rendered instead of none.

Code sandbox reproduction: https://codesandbox.io/s/heuristic-stonebraker-3pn8jc?file=/src/App.js:233-383

**Expected behavior:** 
Not having the empty slide when a condition is false

**Actual behavior:**
Empty slide being rendered.

**Comment by ValGeorgiev** [comment]
Hey @victorakioz Thanks for raising this with us. Fix is coming

**Comment by ValGeorgiev** [comment]
Still not released, I will reopen it for now

**Comment by ValGeorgiev** [comment]
This should be fixed with the latest release 5.3.0. Thanks for raising this with us.
