### ISSUE TITLE
Do not set "inert" for half visible slides

### ISSUE THREAD

**Issue by mrsamse** [FormidableLabs/nuka-carousel#961]
Describe Your Environment
What version of nuka-carousel are you using? 5.2.0
What version of React are you using? 18.0.0
What browser are you using? Chrome Version 103.0.5060.114

Is it possible to remove the "inert" tags on slides which are not completely visible? 
You can achieve this behaviour if you set the slidesToShow parameter to "1.5" and the cellAlign parameter to Alignment.Center.
I want to add clickHandler on those slides, so that the user can also navigate by slide click.

I've produced [a minimal reproduction at this codesandbox](https://codesandbox.io/s/nuka-carousel-playground-forked-bcri3m?file=/src/App.js)

**Comment by fritz-c** [comment]
Here's a minimal example of that working on v5.3.0
https://codesandbox.io/s/nuka-carousel-click-slide-to-change-example-spge74?file=/src/App.js

It appears the `inert` issue you mentioned was fixed in v5.3.0

**Comment by mrsamse** [comment]
Works with v5.3. Thanks!
