### ISSUE TITLE
failed to parse source map from 'E:\merit\node_modules\nuka-carousel\src\announce-slide.tsx' 

### ISSUE THREAD

**Issue by MrHumble21** [FormidableLabs/nuka-carousel#976]
# Bugs and Questions

### Prerequisites

- [x] I've searched open [issues](https://github.com/FormidableLabs/nuka-carousel/issues) to make sure I'm not opening a duplicate issue
- [x] I have read through the docs before asking a question
- [x] I am using the latest version of nuka-carousel

### Describe Your Environment

- What version of nuka-carousel are you using? 
- What version of React are you using? 
- What browser are you using? 

### Describe the Problem
WARNING in ./node_modules/nuka-carousel/lib/announce-slide.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'E:\merit\node_modules\nuka-carousel\src\announce-slide.tsx' file: Error: ENOENT: no such file or directory, open 'E:\merit\node_modules\nuka-carousel\src\announce-slide.tsx'

WARNING in ./node_modules/nuka-carousel/lib/carousel.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'E:\merit\node_modules\nuka-carousel\src\carousel.tsx' file: Error: ENOENT: no such file or directory, open 'E:\merit\node_modules\nuka-carousel\src\carousel.tsx'

WARNING in ./node_modules/nuka-carousel/lib/control-styles.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'E:\merit\node_modules\nuka-carousel\src\control-styles.ts' file: Error: ENOENT: no such file or directory, open 'E:\merit\node_modules\nuka-carousel\src\control-styles.ts'

WARNING in ./node_modules/nuka-carousel/lib/controls.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'E:\merit\node_modules\nuka-carousel\src\controls.tsx' file: Error: ENOENT: no such file or directory, open 'E:\merit\node_modules\nuka-carousel\src\controls.tsx'

WARNING in ./node_modules/nuka-carousel/lib/default-carousel-props.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'E:\merit\node_modules\nuka-carousel\src\default-carousel-props.tsx' file: Error: ENOENT: no such file or directory, open 'E:\merit\node_modules\nuka-carousel\src\default-carousel-props.tsx'

WARNING in ./node_modules/nuka-carousel/lib/default-controls.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'E:\merit\node_modules\nuka-carousel\src\default-controls.tsx' file: Error: ENOENT: no such file or directory, open 'E:\merit\node_modules\nuka-carousel\src\default-controls.tsx'

WARNING in ./node_modules/nuka-carousel/lib/hooks/use-frame-height.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'E:\merit\node_modules\nuka-carousel\src\hooks\use-frame-height.ts' file: Error: ENOENT: no such file or directory, open 'E:\merit\node_modules\nuka-carousel\src\hooks\use-frame-height.ts'

WARNING in ./node_modules/nuka-carousel/lib/hooks/use-state-with-ref.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'E:\merit\node_modules\nuka-carousel\src\hooks\use-state-with-ref.ts' file: Error: ENOENT: no such file or directory, open 'E:\merit\node_modules\nuka-carousel\src\hooks\use-state-with-ref.ts'

WARNING in ./node_modules/nuka-carousel/lib/hooks/use-tween.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'E:\merit\node_modules\nuka-carousel\src\hooks\use-tween.ts' file: Error: ENOENT: no such file or directory, open 'E:\merit\node_modules\nuka-carousel\src\hooks\use-tween.ts'

WARNING in ./node_modules/nuka-carousel/lib/slide.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'E:\merit\node_modules\nuka-carousel\src\slide.tsx' file: Error: ENOENT: no such file or directory, open 'E:\merit\node_modules\nuka-carousel\src\slide.tsx'

WARNING in ./node_modules/nuka-carousel/lib/slider-list.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'E:\merit\node_modules\nuka-carousel\src\slider-list.tsx' file: Error: ENOENT: no such file or directory, open 'E:\merit\node_modules\nuka-carousel\src\slider-list.tsx'

WARNING in ./node_modules/nuka-carousel/lib/types.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'E:\merit\node_modules\nuka-carousel\src\types.ts' file: Error: ENOENT: no such file or directory, open 'E:\merit\node_modules\nuka-carousel\src\types.ts'

WARNING in ./node_modules/nuka-carousel/lib/utils.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'E:\merit\node_modules\nuka-carousel\src\utils.ts' file: Error: ENOENT: no such file or directory, open 'E:\merit\node_modules\nuka-carousel\src\utils.ts'

**Comment by MrHumble21** [comment]
{
  "name": "merit",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "nuka-carousel": "^5.4.0",
    "react": "^18.2.0",
    "react-countup": "^6.3.1",
    "react-dom": "^18.2.0",
    "react-icons": "^4.4.0",
    "react-scripts": "^5.0.1",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

**Comment by fritz-c** [comment]
Could you make a minimal reproduction repo on github and share the link with me?

**Comment by prophet-of-distortion** [comment]
@MrHumble21 How are you importing the carousel? 

@fritz-c 
`import Carousel from 'nuka-carousel/lib/carousel';`

instead of

`import Carousel from 'nuka-carousel';`

causes the warnings to show up.
