### ISSUE TITLE
centering images inside the carousel

### ISSUE THREAD

**Issue by kevinmachstudio** [FormidableLabs/nuka-carousel#978]
is there a way to center the images in the carousel? I've tried the following although it's still being aligned left

```
     <Carousel
        style={{
          textAlign: "center",
        }}
        cellAlign={Alignment.Center}
        defaultControlsConfig={{
          nextButtonText: (<MdNavigateNext className="z-10" />) as any,
          prevButtonText: (<MdNavigateBefore className="z-10" />) as any,

        }}
      >
        {photos.map((photo, idx) => {
          return (
            <Image
              src={photo.url}
              key={idx}
              width={250}
              height={250}
              className="object-cover rounded"
            />
          
          );
        })}
      </Carousel>
```

<img width="400" alt="image" src="https://user-images.githubusercontent.com/6373887/196081986-d94818aa-785e-444c-b10d-5306c6073697.png">

<img width="959" alt="image" src="https://user-images.githubusercontent.com/6373887/196081885-95316fa6-a322-48e6-b04b-630369f8d888.png">

^ if you take out the `text-align: left` it will center as shown below

<img width="350" alt="image" src="https://user-images.githubusercontent.com/6373887/196082327-8486cf07-3998-40fe-87db-1e543d50aa57.png">

**Comment by vaishal** [comment]
You can wrap the image in a wrapper that centers it.

Example: https://codesandbox.io/s/romantic-dijkstra-m5igvb?file=/src/App.js
