### ISSUE TITLE
possible to replicate slidesToScroll="auto" in v5?

### ISSUE THREAD

**Issue by allypalanzi** [FormidableLabs/nuka-carousel#979]
# Bugs and Questions

### Prerequisites

- [x] I've searched open [issues](https://github.com/FormidableLabs/nuka-carousel/issues) to make sure I'm not opening a duplicate issue
- [x] I have read through the docs before asking a question
- [x] I am using the latest version of nuka-carousel

### Describe Your Environment

- What version of nuka-carousel are you using? 5.4

### Describe the Problem

I'm working on updating from v4 to v5, and am wondering how I might replicate `slidesToScroll="auto"`. I don't know how many slides will be visible, and I want all slides visible to scroll using the scrollMode="page" like previously in v4.

**Comment by ValGeorgiev** [comment]
Hey @allypalanzi, Sorry for the slow response. Could you share a sandbox with an example, please? I am wondering about `I don't know how many slides will be visible`, what did you pass as `slidesToShow` in your scenario?

**Comment by allypalanzi** [comment]
looks like what i need should be covered by https://github.com/FormidableLabs/nuka-carousel/pull/985

**Comment by allypalanzi** [comment]
is this going to be released in v5?

**Comment by gksander** [comment]
Hi @allypalanzi – sorry for the waaaay long delay on this! Let me take a peak into this and see if we can safely release this as part of V5!

**Comment by allypalanzi** [comment]
amazing!!!!!!

**Comment by allypalanzi** [comment]
@gksander any update on this?

**Comment by carlos-kelly** [comment]
Hi :wave: We're going to fix up a couple cypress tests and get a release here cut soon. Sorry for the delay on this!

**Comment by carlos-kelly** [comment]
@allypalanzi 5.5.0 should be published.
