### ISSUE TITLE
Controlled Carousel using afterSlide and slideIndex results in infinite loop

### ISSUE THREAD

**Issue by panigrah** [FormidableLabs/nuka-carousel#980]
This was closed in #416 - but still there in latest.

###Recreating issue
Sandbox with behavior

https://codesandbox.io/s/inspiring-nightingale-6felod?file=/src/App.js

Am using the latest Nuka 5.4, React 18.2

### Describe the Problem
Controlled Carousel ends up in an infinite loop if the "next" and "prev" buttons are clicked really fast.

**Comment by fritz-c** [comment]
Try with `beforeSlide`:
https://codesandbox.io/s/laughing-tree-gzoru1?file=/src/App.js
