### ISSUE TITLE
Unable to interact with slides with content on them because of `inert="false"`

### ISSUE THREAD

**Issue by allypalanzi** [FormidableLabs/nuka-carousel#999]
# Bugs and Questions

### Prerequisites

- [x] I've searched open [issues](https://github.com/FormidableLabs/nuka-carousel/issues) to make sure I'm not opening a duplicate issue
- [x] I have read through the docs before asking a question
- [x] I am using the latest version of nuka-carousel

### Describe Your Environment

- What version of nuka-carousel are you using? 5.5
- What version of React are you using? 17
- What browser are you using? Chrome latest

### Describe the Problem

When slides have interactive content on them, users are unable to click anything because `inert` is on all slides. `inert="false"` is invalid, i believe, it needs to not have any value for inert in order to remove that parameter.

#### Expected behavior:

Slides should be able to have links/buttons/interactive elements on them

#### Actual behavior

Slides are not able to be interacted with

### Additional Information

Code sandbox: https://codesandbox.io/s/mystifying-tereshkova-1z47si?file=/src/App.js

**Comment by aksdevac** [comment]
yes it works with 5.4.1, broken with 5.5.

**Comment by alexjs-dev** [comment]
I confirm. Slides are not clickable, all hover effects are broken too.
